force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Is_LEDES_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_LEDES_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is LEDES Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/API_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>API_Request_ID__c</fullName>
    <label>API Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send Create Request</fullName>
            </value>
            <value>
                <fullName>Send Update Request</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Downloaded Info</fullName>
            </value>
            <value>
                <fullName>Downloaded Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/batchRenewalInvoiceInfo.cls
//renewal/invoice/info/{invoiceref}/download/{type}
public class batchRenewalInvoiceInfo implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful
{
    public string query{set;get;}
    public boolean callAttachmentsBatch{set;get;}
    public string AccessToken{set;get;}
    public API_Credentials__c credentials{set;get;}
    public string strAuditTrail = '';
    public batchRenewalInvoiceInfo()
    {
        //AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        callAttachmentsBatch = false;
        AccessToken = '';
        credentials = [SELECT Id,Name,URL__c,Username__c,Password__c FROM API_Credentials__c WHERE Name=: 'Invoice Info' Limit 1];
        query = 'Select id,Name,Order__r.Client__c,API_Request_ID__c,API_Status__c from Invoice__c where API_Status__c=\'Completed\'';
    }
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Invoice__c> scope)
    {
        AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        boolean saveAudit = false;
        string status = 'Success';
        try
        {
            strAuditTrail +='Renewal Invoice Info : ';
            List<Clients__c> clientConfig=new List<Clients__c>();
            if(scope.size()>0)
            	clientConfig =[SELECT 	Id,Is_LEDES_Required__c FROM Clients__c WHERE id=:scope[0].Order__r.Client__c ];
            for(Invoice__c ci : scope)
            {
                string fileName='';
                HttpResponse res=new HttpResponse();
                string URL = credentials.URL__c;                
                string ledesURL=URL.replace('invoiceref',ci.Name).replace('type','ledes');
                URL=URL.replace('invoiceref',ci.Name).replace('/type','');
                strAuditTrail +='Invoice file download URL - '+URL;
                res = CallAPI(URL,AccessToken);
                if(clientConfig.size()>0 && clientConfig[0].Is_LEDES_Required__c)
                {
                    AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
                    strAuditTrail +='LEDES file download URL - '+ledesURL;
                    HttpResponse ledesResponse = new HttpResponse();
                    ledesResponse = CallAPI(ledesURL,AccessToken);
                    fileName='LEDESInvoice-'+ ci.Name+' INFO';
                    callAttachmentsBatch=UploadFile(ledesResponse,ci.Name,ci.Id,fileName);
                }
                fileName='Invoice-'+ ci.Name+' INFO';
                callAttachmentsBatch=UploadFile(res,ci.Name,ci.Id,fileName);
                if(callAttachmentsBatch)
                	ci.API_Status__c = 'Downloaded Info';
            }
            if(callAttachmentsBatch)
            	update scope;
        }
        catch(Exception e)
        {
            strAuditTrail += ' || Error :'+e.getMessage()+'|| Stacktrace-'+e.getStackTraceString()+'|| linenumber-'+e.getLineNumber();
            status = 'Fail';
        }
        finally
        {
            system.debug(strAuditTrail);
            AuditTrailHelper.UpdateAudit('batchRenewalInvoiceInfo-download',strAuditTrail,status);
        }
    }
    
    //Makes a call to the MaxvalAPI to get the csv file
    public HttpResponse CallAPI(string URL,string AccessToken)
    {
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint(URL);
        req.setHeader('Authorization', 'Bearer ' + AccessToken);
        req.setHeader('Content-Type','application/json;charset=UTF-8');
        req.setHeader('Content-Length', '0');
        req.setTimeout(120000);
        HttpResponse res = http.send(req);
        return res;
    }
    
    //This function is used to upload the file against the particular order
    public boolean UploadFile(HttpResponse response,string invoiceRef,Id invoiceID,string fileName)
    {
        boolean callAttachmentsBatch=false;
        if(response.getstatusCode() == 200)
        {
            strAuditTrail +=' |Res Status:'+response.getStatus()+' Code:'+response.getStatusCode();
            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S';
            conVer.PathOnClient =fileName+'.csv';
            conVer.Title =fileName; // Display name of the files
            conVer.VersionData = response.getBodyAsBlob(); // converting your binary string to Blog
            insert conVer;
            System.debug(conVer.Id);
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
            ContentDocumentLink cDe = new ContentDocumentLink();
            cDe.ContentDocumentId = conDoc;
            cDe.LinkedEntityId = invoiceID; // you can use objectId,GroupId etc
            cDe.ShareType = 'I'; // Inferred permission, checkout description of ContentDocumentLink object for more details
            insert cDe;
            callAttachmentsBatch = true;
        }
        return callAttachmentsBatch;
    }
    
    public void finish(Database.BatchableContext BC)
    {
        if(callAttachmentsBatch)
        {
            batchRenewalInvoiceAttachment ab = NEW batchRenewalInvoiceAttachment();
            database.executeBatch(ab,1);
        }
    }
}