force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Jurisdiction__c/Jurisdiction__c.object-meta.xml
<CustomObject>
    <label>Jurisdiction</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jurisdictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PTO_Validation_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>PTO_Validation_Request_ID__c</fullName>
    <label>PTO Validation Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PTO_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>PTO_Validation_Status__c</fullName>
    <label>PTO Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request to Validate</fullName>
            </value>
            <value>
                <fullName>Validation Requested</fullName>
            </value>
            <value>
                <fullName>Validation Passed</fullName>
            </value>
            <value>
                <fullName>Validation Failed</fullName>
            </value>
            <value>
                <fullName>Payment Success</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Close_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Close_Date_To_Pay__c</fullName>
    <label>Suggested Close Date to Pay</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Open_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Open_Date_To_Pay__c</fullName>
    <label>Suggested Payment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Auth_Details__c/User_Auth_Details__c.object-meta.xml
<CustomObject>
    <label>User Auth Detail</label>
    <nameField>
        <displayFormat>User-{000}</displayFormat>
        <label>User Auth Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Auth Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>EP</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PTOFeePaidServiceClassTest.cls
@istest public class PTOFeePaidServiceClassTest {
@isTest public static void TestMethod1()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
        Order_Item__c Objorderitem = new Order_Item__c();
        Objorderitem.order__c=Objorder.id; 
        Objorderitem.Jurisdiction__c='US';
        //Objorderitem.Suggested_Open_Date_To_Pay__c=system.today()-1; 
        Objorderitem.Suggested_Close_Date_To_Pay__c=system.today()-1; 
        Objorderitem.Payment_Status__c='Payment Received'; 
        Objorderitem.Paid_Status__c=null;
        Objorderitem.Renewal_Instruction__c='Renew';
    Objorderitem.Patent_No__c='US232434';
    Objorderitem.Application_No__c ='US1233234';
        Objorderitem.Application_Date__c =System.today();
	    Objorderitem.PTO_Validation_Request_ID__c ='28c30658-9c8d-4c43-8135-4afc2e649d6f';
        Insert Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        //User_Auth_Details__c ObjAOql =[select name from User_Auth_Details__c limit 1];
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"28c30658-9c8d-4c43-8135-4afc2e649d6f","Status":3,"Items":[{"ApplicationNumber":"14513841","PatentNumber":"10565402","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
@isTest public static void TestMethod2()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
     	List<Order_Item__c> Objorderitem = new List<Order_Item__c>{new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US232434',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US8543217',Application_No__c ='US78901234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1233234',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551')};
        INSERT Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"PTO-21545455221445551","Status":3,"Items":[{"ApplicationNumber":"1233234","PatentNumber":"232434","Status":"VP","Error":[]},{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
@isTest public static void TestMethod3()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
     	List<Order_Item__c> Objorderitem = new List<Order_Item__c>{new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US232434',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US8543217',Application_No__c ='US78901234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1233234',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
        	new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1230234',Application_No__c ='US1234234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551')};
                INSERT Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"PTO-21545455221445551","Status":3,"Items":[{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"7890234","PatentNumber":"853217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}],{"ApplicationNumber":"1234234","PatentNumber":"1230234","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod4()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
     	List<Order_Item__c> Objorderitem = new List<Order_Item__c>{new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US232434',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US8543217',Application_No__c ='US7890134',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1233234',Application_No__c ='US12334',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
        	new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1230234',Application_No__c ='US1234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551')};
                INSERT Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"PTO-2154545522144551","Status":3,"Items":[{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"7890234","PatentNumber":"853217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}],{"ApplicationNumber":"1234234","PatentNumber":"1230234","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod5()
{
    	API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
     	List<Order_Item__c> Objorderitem = new List<Order_Item__c>{new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US232434',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US8543217',Application_No__c ='US7890134',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1233234',Application_No__c ='US12334',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
        	new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1230234',Application_No__c ='US1234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551')};
                INSERT Objorderitem;
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":null,"RequestID":null,"Status":3,"Items":[{"ApplicationNumber":"1233","PatentNumber":"123334","Status":"VP","Error":""},{"ApplicationNumber":"US7890134","PatentNumber":"US8543217","Status":"VP","Error":""},{"ApplicationNumber":"78234","PatentNumber":"8532","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}],{"ApplicationNumber":"1234234","PatentNumber":"1230234","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod6()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
     	List<Order_Item__c> Objorderitem = new List<Order_Item__c>{new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US232434A',Application_No__c ='US1233234A',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US8543217A2',Application_No__c ='US78901234A2',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1233234',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-21545455221445551')};
        INSERT Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"PTO-21545455221445551","Status":3,"Items":[{"ApplicationNumber":"US1233234A","PatentNumber":"US232434A","Status":"VP","Error":[]},{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"US78901234A2","PatentNumber":"US8543217A2","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod7()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
     	List<Order_Item__c> Objorderitem = new List<Order_Item__c>{new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US232434A',Application_No__c ='US1233234A',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-2154545522144555'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US8543217A2',Application_No__c ='US78901234A2',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-2154545522144555'),
            new Order_Item__c(order__c=Objorder.id,Jurisdiction__c='US',Suggested_Close_Date_To_Pay__c=system.today()-1,Payment_Status__c='Payment Received',Paid_Status__c=null,Renewal_Instruction__c='Renew',Patent_No__c='US1233234',Application_No__c ='US1233234',Application_Date__c =System.today(),PTO_Validation_Request_ID__c ='PTO-2154545522144555')};
        INSERT Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
    String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"PTO-21545455221445551","Status":3,"Items":[{"ApplicationNumber":"US1233234A","PatentNumber":"US232434A","Status":"VP","Error":[]},{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"US78901234A2","PatentNumber":"US8543217A2","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"},{"Description":"Code is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod8()
	{
		Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"","RequestID":"","Status":3,"Items":[{"ApplicationNumber":"US1233234A","PatentNumber":"US232434A","Status":"VP","Error":[]},{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"US78901234A2","PatentNumber":"US8543217A2","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();    
	}
    @isTest public static void TestMethod9()
	{
		Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"sample","RequestID":"","Status":3,"Items":[{"ApplicationNumber":"US1233234A","PatentNumber":"US232434A","Status":"VP","Error":[]},{"ApplicationNumber":"1233230","PatentNumber":"1233234","Status":"VP","Error":[]},{"ApplicationNumber":"US78901234A2","PatentNumber":"US8543217A2","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();    
	}
    @isTest public static void TestMethod10()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='Dropbox';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
        Order_Item__c Objorderitem1 = new Order_Item__c();
        Objorderitem1.order__c=Objorder.id; 
        Objorderitem1.Jurisdiction__c='EP';
        //Objorderitem.Suggested_Open_Date_To_Pay__c=system.today()-1; 
        Objorderitem1.Suggested_Close_Date_To_Pay__c=system.today()-1; 
        Objorderitem1.Payment_Status__c='Payment Received'; 
        Objorderitem1.Paid_Status__c=null;
        Objorderitem1.Renewal_Instruction__c='Renew';
    Objorderitem1.Patent_No__c='US232434';
    Objorderitem1.Application_No__c ='US1233234';
        Objorderitem1.Application_Date__c =System.today();
	    Objorderitem1.PTO_Validation_Request_ID__c ='28c30658-9c8d-4c43-8135-4afc2e649d6f';
    	Objorderitem1.PTO_Validation_Status__c = 'Validation Passed';
        Insert Objorderitem1;
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        //User_Auth_Details__c ObjAOql =[select name from User_Auth_Details__c limit 1];
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"28c30658-9c8d-4c43-8135-4afc2e649d6f","Status":3,"Items":[{"ApplicationNumber":"14513841","PatentNumber":"10565402","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod11()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
        Order_Item__c Objorderitem = new Order_Item__c();
        Objorderitem.order__c=Objorder.id; 
        Objorderitem.Jurisdiction__c='US';
        //Objorderitem.Suggested_Open_Date_To_Pay__c=system.today()-1; 
        Objorderitem.Suggested_Close_Date_To_Pay__c=system.today()-1; 
        Objorderitem.Payment_Status__c='Payment Received'; 
        Objorderitem.Paid_Status__c=null;
        Objorderitem.Renewal_Instruction__c='Renew';
    Objorderitem.Patent_No__c='US232434';
    Objorderitem.Application_No__c ='US1233234';
        Objorderitem.Application_Date__c =System.today();
	    Objorderitem.PTO_Validation_Request_ID__c ='28c30658-9c8d-4c43-8135-4afc2e649d6f';
        Insert Objorderitem;
    
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        //User_Auth_Details__c ObjAOql =[select name from User_Auth_Details__c limit 1];
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
    	String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"28c30658-9c8d-4c43-8135-4afc2e649d6f","Status":3,"Items":[{"ApplicationNumber":"14513841","PatentNumber":"10565402","FeeCode":"1551","Status":"VP","Error":[]},{"ApplicationNumber":"14513841","PatentNumber":"10565402","FeeCode":"1551","Status":"VP","Error":[]}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod12()
{
    API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='Dropbox';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
        Order_Item__c Objorderitem1 = new Order_Item__c();
        Objorderitem1.order__c=Objorder.id; 
        Objorderitem1.Jurisdiction__c='US';
        //Objorderitem.Suggested_Open_Date_To_Pay__c=system.today()-1; 
        Objorderitem1.Suggested_Close_Date_To_Pay__c=system.today()-1; 
        Objorderitem1.Payment_Status__c='Payment Received'; 
        Objorderitem1.Paid_Status__c=null;
        Objorderitem1.Renewal_Instruction__c='Renew';
    Objorderitem1.Patent_No__c='US232434';
    Objorderitem1.Application_No__c ='1234S5';
        Objorderitem1.Application_Date__c =System.today();
	    Objorderitem1.PTO_Validation_Request_ID__c ='28c30658-9c8d-4c43-8135-4afc2e649d6f';
        Insert Objorderitem1;
        Test.startTest();
        RestRequest req =new RestRequest();
        RestResponse res = RestContext.response;
        //User_Auth_Details__c ObjAOql =[select name from User_Auth_Details__c limit 1];
        req.requestURI = '/services/apexrest/pto/payment/validate/status/';  //Request URL
        req.httpMethod = 'PUT';//HTTP Request Type
        RestContext.request = req;
        String JSONMsg ='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","RequestID":"28c30658-9c8d-4c43-8135-4afc2e649d6f","Status":3,"Items":[{"ApplicationNumber":"14513841","PatentNumber":"10565402","Status":"VP","Error":[]},{"ApplicationNumber":"78901234","PatentNumber":"8543217","FeeCode":"1551","Status":"VF","Error":[{"Description":"Amount is missing"}]}],"BillDetails":{"Status":"True","BillNo":"B202011001","Error":[{"Description":"Amount is missing"}]},"Error":[{"Description":"Amount is missing"}],"Warning":[{"Description":"Amount is missing"}]}';
        req.requestBody = Blob.valueof(JSONMsg);
        PTOFeePaidServiceClass.PTOFeePaid();
        Test.stopTest();
}
    @isTest public static void TestMethod13()
{
    
        Test.startTest();
        
    	PTOFeePaidServiceClass.responcebody rb = new PTOFeePaidServiceClass.responcebody();
    	rb.MVRefId = 'ABC123';
    	rb.Status = 'VP';
    
    	PTOFeePaidServiceClass.requestbody reqb = new PTOFeePaidServiceClass.requestbody();
    	reqb.Status = 3;
    	reqb.Error = null;
    	reqb.Warning = null;
    
    	PTOFeePaidServiceClass.requestbodyItem rbi = new PTOFeePaidServiceClass.requestbodyItem();
    	rbi.Status = 'VF';
    	rbi.Error = null;
    
    	PTOFeePaidServiceClass.errorbody eb = new PTOFeePaidServiceClass.errorbody();
    	eb.Description = 'Empty';
    
    	PTOFeePaidServiceClass.error er = new PTOFeePaidServiceClass.error();
    	er.Description = 'Empty';
    	er.Staus = 'Error123';
           
    	PTOFeePaidServiceClass.warning warn = new PTOFeePaidServiceClass.warning();
    	warn.Description = 'Empty';
    
    	PTOFeePaidServiceClass.reqBillDetails rbd = new PTOFeePaidServiceClass.reqBillDetails();
    	rbd.Status = 'VF';
    	rbd.BillNo = 'ABC123';
    	rbd.Warning = null;
    
        Test.stopTest();
}
}