force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Jurisdiction__c/Jurisdiction__c.object-meta.xml
<CustomObject>
    <label>Jurisdiction</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jurisdictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Amount_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount_When_Pay__c</fullName>
    <formula>if 
(
(TEXT(Fee_Currency__c) == TEXT(Billing_Currency__c))
,(Fee__c +  Claim_Fee__c +  Surcharge__c)
,(((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate_When_Pay__c)/Billing_Currency_Unit_Rate_When_Pay__c)
+((((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate_When_Pay__c)/Billing_Currency_Unit_Rate_When_Pay__c) * (CE_Markup_Percentage__c /100))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTO Fee (Payable)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice_Type_Name_Value__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name_Value__c</fullName>
    <formula>if(
     TEXT(Order__r.Client__r.Invoice_Type__c) == &apos;Regular Invoice&apos;
     ,  Order__r.Client__r.Id + &apos;_&apos; +  Order__r.Id + &apos;_&apos; +  TEXT(Billing_Currency__c )
     , if ( 
          Path__c == null
          , Order__r.Client__r.Id + &apos;_&apos; +  Order__r.Id + &apos;_&apos; +  TEXT(Billing_Currency__c)
          , Order__r.Client__r.Id + &apos;_&apos; +  Order__r.Id + &apos;_&apos; +  Path__c  + &apos;_&apos; +  TEXT(Billing_Currency__c) 
     )
)</formula>
    <label>Invoice Type Name Value</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/MV_API_Ref_Id__c.field-meta.xml
<CustomField>
    <fullName>MV_API_Ref_Id__c</fullName>
    <label>MV API Ref Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTO_Credentials__c/PTO_Credentials__c.object-meta.xml
<CustomObject>
    <label>PTO Credentials</label>
    <nameField>
        <displayFormat>CRE-{00000}</displayFormat>
        <label>PTO Credentials No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchRequestingToPayPTO.cls
//pto/payment/validate
public class batchRequestingToPayPTO implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful
{
    public string query{set;get;}
    public string AccessToken{set;get;}
    public API_Credentials__c credentials{set;get;}
    public List<string> lstOIIds{set;get;}
    public List<string> lstPersonIds{set;get;}
    public Map<string,string> countryAuth{set;get;}
    public set<string> lstPersonEmails{set;get;}
    public List<string> disclosureIds{set;get;}
    public batchRequestingToPayPTO(List<string> oiIds)
    {
        AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        lstOIIds = NEW List<string>();
        lstOIIds = oiIds;
        countryAuth = NEW Map<string,string>();
        List<PTO_Credentials__c> PTOCredentials = [Select id,Name, Country_Code__c FROM PTO_Credentials__c];
        for(PTO_Credentials__c pc : PTOCredentials)
        {
            countryAuth.put(pc.Country_Code__c,pc.Name);
        }
        credentials = [SELECT Id,Name,URL__c,Username__c,Password__c FROM API_Credentials__c WHERE Name=: 'Pto Payment Validate'];
        //query = 'SELECT id,Name,Paid_Status__c,Payment_Status__c,Order_Number__c,Client__c,Billing_Currency__c,Fee_Amount_When_Pay__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c FROM Order_Item__c where ID IN : lstOIIds';
        query = 'SELECT id,Name,Paid_Status__c,Payment_Status__c,Order_Number__c,Client__c,Jurisdiction__c,Billing_Currency__c,Fee_Amount_When_Pay__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c,Invoice_Type_Name_Value__c,Invoice__c,Invoice__r.Name FROM Order_Item__c where ID IN : lstOIIds';
    }
    public batchRequestingToPayPTO()
    {
        countryAuth = NEW Map<string,string>();
        List<PTO_Credentials__c> PTOCredentials = [Select id,Name, Country_Code__c FROM PTO_Credentials__c];
        for(PTO_Credentials__c pc : PTOCredentials)
        {
            countryAuth.put(pc.Country_Code__c,pc.Name);
        }
        AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        credentials = [SELECT Id,Name,URL__c,Username__c,Password__c FROM API_Credentials__c WHERE Name=: 'Pto Payment Validate'];
        //query = 'SELECT id,Name,Paid_Status__c,Payment_Status__c,Order_Number__c,Client__c,Billing_Currency__c,Fee_Amount_When_Pay__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c FROM Order_Item__c where Paid_Status__c=\'Requesting to Pay PTO\' AND Payment_Status__c=\'Payment Received\'';
        query = 'SELECT id,Name,Paid_Status__c,Payment_Status__c,Order_Number__c,Client__c,Jurisdiction__c,Billing_Currency__c,Fee_Amount_When_Pay__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c,Invoice_Type_Name_Value__c,Invoice__c,Invoice__r.Name FROM Order_Item__c where Payment_Status__c=\'Payment Received\'';//Paid_Status__c=\'Requesting to Pay PTO\' AND 
        system.debug(query);
    }
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Order_Item__c> scope)
    {
        boolean saveAudit = false;
        string strAuditTrail = '';
        try
        {
            strAuditTrail += 'Requesting To Pay PTO : ';
            List<Order_Item__c> ois = NEW List<Order_Item__c>();
            //String AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
            Map<String,List<Order_Item__c>> OrderItemMap = new Map<String,List<Order_Item__c>>();
            for(Order_Item__c oi : scope)
            {
                List<Order_Item__c> temp = OrderItemMap.get(oi.Invoice__r.Name);
                if(temp != null)
                {
                    temp.add(oi);
                }
                else
                {
                    OrderItemMap.put(oi.Invoice__r.Name, new List<Order_Item__c>{oi});
                }
            }
            for(string keyOI : OrderItemMap.keyset())
            {
                set<string> countryCode = NEW set<string>();
                ReqData woi = NEW ReqData();               
                List<objectitem> Items = NEW List<objectitem>();                
                for(Order_Item__c oi : OrderItemMap.get(keyOI))
                {
                    countryCode.add(oi.Jurisdiction__c);
                    objectitem oitem = NEW objectitem();
                    oitem.ApplicationNumber = oi.Application_No__c;
                    oitem.PatentNumber = oi.Patent_No__c;
                    oitem.SerialNumber = oi.Application_No__c;
                    oitem.PublicationNumber = oi.Application_No__c;
                    oitem.AttorneyDocketNumber= oi.Application_No__c;
                    oitem.RenewalYear= '';
                    oitem.FilingDate= '';
                    oitem.FeeCode= oi.Billing_Currency__c;
                    oitem.Fee= String.valueof(oi.Fee_Amount_When_Pay__c);
                    Items.add(oitem);
                }
                woi.ClientRequestHandle = keyOI;
                list<string> strs = NEW list<string>();
                strs.addall(countryCode);
                string code=strs[0];
                system.debug('C Code:'+code);
                if(countryAuth.containsKey(code))
                    woi.AuthHandleRef = countryAuth.get(code);
                system.debug(woi.AuthHandleRef);
                woi.Jurisdiction = code;
                woi.Items = Items;
                string jsonbody = JSON.serialize(woi);
                //string jsonbody='{"ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669","AuthHandleRef":"b772a5ac-7565-48de-b3ff-15168aa72c3a","Jurisdiction":"US","Items":[{"ApplicationNumber":"14513841","PatentNumber":"10565402","SerialNumber":"","PublicationNumber":"","AttorneyDocketNumber":"P491US1","RenewalYear":"","FilingDate":"","FeeCode":"1551","Fee":"1500.55"}]}';
                
                system.debug('Request Body :'+jsonbody);
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setMethod('POST');
                req.setEndpoint(credentials.URL__c);
                req.setHeader('Authorization', 'Bearer ' + AccessToken);
                req.setHeader('Content-Type','application/json;charset=UTF-8');
                req.setHeader('Content-Length', string.valueOf(jsonbody.length()));            
                req.setBody(jsonbody);
                HttpResponse res = http.send(req);  
                system.debug('Response status code :'+res.getStatusCode() +' |Status :'+res.getStatus() +' |Body '+res.getBody());          
                strAuditTrail += res.getBody();
                List<Order_Item__c> oits = NEW List<Order_Item__c>();
                if(res.getStatusCode() == 200)
                {
                    string strres = res.getBody();
                    responsebody resb = (responsebody)JSON.deserialize(strres, responsebody.Class);
                    for(Order_Item__c oi : OrderItemMap.get(keyOI))
                    {
                        oi.Paid_Status__c = 'Requested to Pay PTO';
                        oi.MV_API_Ref_Id__c = resb.RequestID;
                        oits.add(oi);
                    }
                }            
                update oits;
            }
        }
        catch(Exception e)
        {
            strAuditTrail += ' || Error :'+e.getMessage();
        }
        finally
        {
            system.debug(strAuditTrail);
        }
    }
    public void finish(Database.BatchableContext BC)
    {
        
    }
    public class ReqData
    {
        public string ClientRequestHandle{get;set;}
        public string AuthHandleRef{get;set;}
        public string Jurisdiction{get;set;}
        public List<objectitem> Items{get;set;}
    }
    public class objectitem
    {
        public string ApplicationNumber{get;set;}
        public string PatentNumber{get;set;}
        public string SerialNumber{get;set;}        
        public string PublicationNumber{get;set;}
        public string AttorneyDocketNumber{get;set;}
        public string RenewalYear{get;set;}
        public string FilingDate{get;set;}
        public string FeeCode{get;set;}
        public string Fee{get;set;}
    }
    public class responsebody
    {
        public string RequestID{ get; set; }
    }
    /*
    {
        "ClientRequestHandle":"d0cb82fc-a85a-42ea-b549-27ee7a3d3669",
        "AuthHandleRef":"b772a5ac-7565-48de-b3ff-15168aa72c3a",
        "Jurisdiction":"US",
        "Items":
        [
            {
                "ApplicationNumber":"14513841",
                "PatentNumber":"10565402",
                "SerialNumber":"",
                "PublicationNumber":"",
                "AttorneyDocketNumber":"P491US1",
                "RenewalYear":"",
                "FilingDate":"",
                "FeeCode":"1551",
                "Fee":"1500.55"
            },
            {
                "ApplicationNumber":"14513841",
                "PatentNumber":"10565402",
                "SerialNumber":"",
                "PublicationNumber":"",
                "AttorneyDocketNumber":"P491US1",
                "RenewalYear":"",
                "FilingDate":"",
                "FeeCode":"1551",
                "Fee":"1500.55"
            }
        ]
    }
    */
}