force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Close_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Close_Date_To_Pay__c</fullName>
    <label>Suggested Close Date to Pay</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Open_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Open_Date_To_Pay__c</fullName>
    <label>Suggested Payment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UploadAgentInvoiceTest.cls
@isTest
public class UploadAgentInvoiceTest {
    @isTest 
    public static void Method1()
    {
	API_Credentials__c cre=new API_Credentials__c();
        cre.name='PTO Payment Validate';
        cre.Username__c='test';
        cre.URL__c='https://google.com';
        cre.Password__c='test';
        insert cre;
        Clients__c objclient =new Clients__c();
        objclient.Name='QCOMM';
        Insert objclient ;
        order__c Objorder = new order__c();
        Objorder.Client__c=objclient.id;
        Insert Objorder;
        Order_Item__c Objorderitem = new Order_Item__c();
        Objorderitem.order__c=Objorder.id; 
        //Objorderitem.Client__c=objclient.id;
        //Objorderitem.Suggested_Open_Date_To_Pay__c=system.today()-1; 
        Objorderitem.Suggested_Close_Date_To_Pay__c=system.today()-1; 
        Objorderitem.Payment_Status__c='Payment Received'; 
        Objorderitem.Paid_Status__c=null;
        Objorderitem.Renewal_Instruction__c='Renew';
        Insert Objorderitem;
        Attachment oAttachment = new Attachment();
        oAttachment.parentId = Objorderitem.id;
        
        oAttachment.Body = EncodingUtil.base64Decode('base64Data');
        oAttachment.Name = 'fileName';
        oAttachment.ContentType = 'pdf'; 
        
        insert oAttachment;  
        list<String> ListOfStr =new list<String>{Objorderitem.id};
            String Str = '[ '+Objorderitem.id+','+Objorderitem.id+' ]';
        UploadAgentInvoice.ValidationCheck(Str);
        UploadAgentInvoice.saveTheFile(Objorderitem.id, 'fileName', 'base64Data', 'pdf');
        UploadAgentInvoice.saveFile(Objorderitem.id, 'fileName', 'base64Data', 'pdf', '');
        UploadAgentInvoice.appendToFile(oAttachment.id, 'base64Data');
        
    }
}