force-app/main/default/objects/QB_Customer__c/QB_Customer__c.object-meta.xml
<CustomObject>
    <label>QB Customer</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Customer__c/fields/Currency_Reference__c.field-meta.xml
<CustomField>
    <fullName>Currency_Reference__c</fullName>
    <label>Currency Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/IsDeleted_In_QB__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted_In_QB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDeleted In QB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/LastUpdatedTime__c.field-meta.xml
<CustomField>
    <fullName>LastUpdatedTime__c</fullName>
    <label>LastUpdatedTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/QB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/Qualified_Name__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Name__c</fullName>
    <label>Qualified Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <label>Sub Customer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchQBCustomerDetails.cls
global class BatchQBCustomerDetails implements Database.Batchable<QBCustomerDetails.Customer>,Database.Stateful,Database.AllowsCallouts { 
    public List<String> EmployeeIdsList{get;set;}
    public List<QBCustomerDetails.Customer> CustomerDataList{get;set;}
    public string  AccessToken{get;set;}
    public map<string, string> MapOfQBCustomerid = new map<string, string>();
    public Set<String> UniqueKeyParam = new Set<String>();
   
    public Iterable<QBCustomerDetails.Customer> start(Database.BatchableContext BC)
    {       
        QBCustomerDetails QB=new QBCustomerDetails();
        AccessToken=QB.accesstoken;
        CustomerDataList = QB.getCustomerDetails(AccessToken);
        System.debug(CustomerDataList.size());
        for(QBCustomerDetails.Customer Rcd :CustomerDataList)
        {
            UniqueKeyParam.add(Rcd.Id);
            MapOfQBCustomerid.put(Rcd.Id,Rcd.Id);
           //
        }
         System.debug('UniqueKeyParam'+UniqueKeyParam);
        return CustomerDataList;
        
    } 
    public void execute(Database.BatchableContext BC,List<QBCustomerDetails.Customer> CustomerDetail) 
    {
        map<string, string> ExistingRecordsCustomerid = new map<string, string>();
        
        Set<String> SetOfDeletedRcdIds = new Set<String>();
        set<string> AddedToList = new set<string>();
        
        list<QB_Customer__c> ListOfDeletedRecordsInQB = new List<QB_Customer__c>();
        list<QB_Customer__c> ListOfQBCustomer =new List<QB_Customer__c>();
        string strAuditTrail = '';
        string status = 'Success';
        strAuditTrail += 'QB Customer Record Creation: ';
        strAuditTrail += CustomerDetail;
        try
        { 
           
            
            List<QB_Customer__c> ListOfExistingQBCustomer = [SELECT Id,Name,QB_Customer_Id__c FROM QB_Customer__c WHERE QB_Customer_Id__c IN:UniqueKeyParam AND IsDeleted_In_QB__c =false];
            for(QB_Customer__c CustRcd :ListOfExistingQBCustomer)
            {
                ExistingRecordsCustomerid.put(CustRcd.QB_Customer_Id__c, CustRcd.Id);
              
            }
           List<QB_Customer__c> ListOfDeletedQBCustomerRcds = [SELECT Id,Name,QB_Customer_Id__c FROM QB_Customer__c WHERE QB_Customer_Id__c NOT IN:UniqueKeyParam AND IsDeleted_In_QB__c =false];
           for(QB_Customer__c CustRcd :ListOfDeletedQBCustomerRcds)
            {
                
               SetOfDeletedRcdIds.add(CustRcd.id);
               System.debug('SetOfDeletedRcdIds'+SetOfDeletedRcdIds);
                //System.debug('ExistingRecordsCustomerid'+ExistingRecordsCustomerid);
            }
            for(QBCustomerDetails.Customer Rcd :CustomerDetail)
            {
                
                Boolean addToList = False;
                QB_Customer__c CustomerRecord =new QB_Customer__c();
                CustomerRecord.QB_Customer_Id__c = Rcd.Id;
                CustomerRecord.Name =Rcd.DisplayName;
                CustomerRecord.Active__c =Rcd.Active;
                CustomerRecord.Currency_Reference__c =Rcd.CurrencyRef.value;
                String formatedDt = Rcd.MetaData.CreateTime;
                DateTime date1 = (DateTime)Json.deserialize('"'+formatedDt+'"', DateTime.class);
                CustomerRecord.Record_Create_Time__c = date1;
                CustomerRecord.Qualified_Name__c = Rcd.FullyQualifiedName;
                CustomerRecord.LastUpdatedTime__c =(DateTime)Json.deserialize('"'+Rcd.MetaData.LastUpdatedTime+'"', DateTime.class);  
                System.debug(date1);
                
                if(Rcd.PrimaryEmailAddr != null )
                {
                    if(Rcd.PrimaryEmailAddr.Address != null )
                    CustomerRecord.Primary_Email__c = Rcd.PrimaryEmailAddr.Address;
                }
				else
                {
                    CustomerRecord.Primary_Email__c  = '';
                }
                if(Rcd.PrimaryPhone != null )
                {
                    if(Rcd.PrimaryPhone.FreeFormNumber != null )
                    CustomerRecord.Phone_Number__c = Rcd.PrimaryPhone.FreeFormNumber;
                }
                else
                {
                    CustomerRecord.Phone_Number__c =  '';
                }
                if(Rcd.ParentRef != null )
                {
                    if(Rcd.ParentRef.value != null )
                    CustomerRecord.Sub_Customer__c =decimal.valueOf(Rcd.ParentRef.value);
                }
                else
                {
                    CustomerRecord.Sub_Customer__c   = null;
                }
                System.debug(ExistingRecordsCustomerid.get(Rcd.Id));
                if(ExistingRecordsCustomerid.get(Rcd.Id) !=  null)//Rcd.Id is the unique name which stored in name field
                {
                    CustomerRecord.Id = ExistingRecordsCustomerid.get(Rcd.Id);
                    System.debug(ExistingRecordsCustomerid.get(Rcd.Id));
                }
                if(CustomerRecord.Id != null)
                {
                    if(AddedToList.contains(CustomerRecord.Id))
                    {
                        addToList = False;
                    }
                    else
                    {
                        addToList = True;
                        AddedToList.add(CustomerRecord.Id);
                    }
                }
                else
                {
                    addToList = True;
                }
                if(addToList == True)
                {
                    ListOfQBCustomer.add(CustomerRecord);
                }
            }
            
            if(ListOfQBCustomer.size() > 0)
            {
                System.debug('ListOfQBCustomer>>>>>>'+ListOfQBCustomer);
                upsert ListOfQBCustomer;
            }
            if(SetOfDeletedRcdIds.size() > 0)
            {
                List<QB_Customer__c> ListOfDeletedQBCustomer = [SELECT Id,IsDeleted_In_QB__c FROM QB_Customer__c WHERE Id IN:SetOfDeletedRcdIds AND IsDeleted_In_QB__c =false];
                for(QB_Customer__c Cust: ListOfDeletedQBCustomer)
                {
                    Cust.IsDeleted_In_QB__c = true;
                    ListOfDeletedRecordsInQB.add(Cust);
                }
                if(ListOfDeletedRecordsInQB.size() > 0)
                {
                    update ListOfDeletedRecordsInQB;
                } 
            }
           
        }
        catch(Exception e)
        {
            strAuditTrail += ' || Error :'+e.getMessage();
            status = 'Fail';
        }
        finally
        {
            //system.debug(strAuditTrail);
            AuditTrailHelper.UpdateAudit('batchQBCustomerDetails',strAuditTrail,status);
        }
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
         //List<QB_Customer__c> ListOfDeletedQBCustomerRcds = [SELECT Id,Name,QB_Customer_Id__c FROM QB_Customer__c ]; 
        
    }  
    
    
}