force-app/main/default/objects/LEDESClientId__mdt/LEDESClientId__mdt.object-meta.xml
<CustomObject>
    <label>LEDESClientId</label>
    <pluralLabel>LEDESClientIds</pluralLabel>
</CustomObject>

force-app/main/default/objects/LEDESClientId__mdt/fields/LawFirmMatterId__c.field-meta.xml
<CustomField>
    <fullName>LawFirmMatterId__c</fullName>
    <label>LawFirmMatterId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LEDESClientId__mdt/fields/LineItemExpensesCode__c.field-meta.xml
<CustomField>
    <fullName>LineItemExpensesCode__c</fullName>
    <label>LineItemExpensesCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LEDESClientId__mdt/fields/MatterId__c.field-meta.xml
<CustomField>
    <fullName>MatterId__c</fullName>
    <label>MatterId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LEDESClientId__mdt/fields/MatterName__c.field-meta.xml
<CustomField>
    <fullName>MatterName__c</fullName>
    <label>MatterName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataHelper.cls
public with sharing class MetadataHelper
{
    public static List<LEDESClientId__mdt> GetLEDESDetails(string client){      
        List<LEDESClientId__mdt> ledesClientIds = new List<LEDESClientId__mdt>();
         ledesClientIds   = [SELECT LineItemExpensesCode__c,ClientId__c,MatterId__c,MatterName__c,LawFirmMatterId__c,MasterLabel FROM LEDESClientId__mdt WHERE MasterLabel =:client LIMIT 1];
       	return ledesClientIds;
    }    
}