force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Amount_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount_When_Pay__c</fullName>
    <formula>if 
(
(TEXT(Fee_Currency__c) == TEXT(Billing_Currency__c))
,(Fee__c +  Claim_Fee__c +  Surcharge__c)
,(((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate_When_Pay__c)/Billing_Currency_Unit_Rate_When_Pay__c)
+((((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate_When_Pay__c)/Billing_Currency_Unit_Rate_When_Pay__c) * (CE_Markup_Percentage__c /100))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTO Fee (Payable)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/MV_API_Ref_Id__c.field-meta.xml
<CustomField>
    <fullName>MV_API_Ref_Id__c</fullName>
    <label>MV API Ref Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTO_Credentials__c/PTO_Credentials__c.object-meta.xml
<CustomObject>
    <label>PTO Credentials</label>
    <nameField>
        <displayFormat>CRE-{00000}</displayFormat>
        <label>PTO Credentials No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PTOCredentialsServiceAPI.cls
@RestResource(urlMapping='/pto/authentication/*')
global class PTOCredentialsServiceAPI
{
    @HttpGet
    global static resp getCredentials() 
    {
        String UniqueName = '';
        String strLeadSource = '';
        RestRequest restReq = RestContext.request;
        RestResponse restRes = RestContext.response;
        // Reading parametrs from URL
        system.debug('Req URL: '+restReq.requestURI);
        string req =  restReq.requestURI;
        integer li= req.lastIndexOf('/detail');
        string s = req.substring(0, li);
        UniqueName =s.substring(s.lastIndexOf('/') + 1);
        system.debug('1 : '+UniqueName);
        strLeadSource = restReq.requestURI.substring(restReq.requestURI.lastIndexOf('&') + 1);
        //List<Order_Item__c > orderItems = [SELECT id,Name,Paid_Status__c,Payment_Status__c,Order_Number__c,Client__c,Billing_Currency__c,Fee_Amount_When_Pay__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c FROM Order_Item__c WHERE MV_API_Ref_Id__c = :MVRefId];
        List<PTO_Credentials__c> ptocreds = [SELECT id,Name,Country_Code__c,Username__c,Password__c FROM PTO_Credentials__c WHERE Name =: UniqueName];
        //list<rep> reslst = NEW list<rep>();
        resp reslst = NEW resp();
        List<Error> errors = NEW List<Error>();
        try
        {
            reslst.Status = true;            
            if (ptocreds != null && ptocreds.size()>0)
            {                
                reslst.Username = ptocreds[0].Username__c;
                reslst.Password = ptocreds[0].Password__c;
                system.debug(Json.serialize(reslst));
            }
            else
            {
                Error er = NEW Error();
                er.ErrorCode = 'NOT_FOUND';
                er.Message= 'Could not find a match for request...';
                errors.add(er);
            }
        }
        catch(exception e)
        {
            Error er = NEW Error();
            er.ErrorCode = '-';
            er.Message= e.getMessage();
            errors.add(er);            
        }
        finally
        {
            reslst.error = errors;
            if(errors.size()>0)
                reslst.Status = false;            
        }
        return  reslst;
        //return  Json.serialize(reslst);
    }
    global class resp
    {
        public boolean Status{set;get;}
        public string Username{set;get;}
        public string Password{set;get;}
        Public List<Error> Error{set;get;}
    }
    global class Error
    {
        public string ErrorCode{set;get;}
        public string Message{set;get;}
    }
}