force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Regular Invoice</fullName>
                <default>true</default>
                <label>Regular Invoice</label>
            </value>
            <value>
                <fullName>BU Wise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request to be Sent</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Sent to Client</fullName>
            </value>
            <value>
                <fullName>Invoice Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Jurisdiction Wise</fullName>
            </value>
            <value>
                <fullName>Business Unit Wise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name__c</fullName>
    <label>Invoice Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Billing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billing_Amount__c</fullName>
    <label>Billing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name__c</fullName>
    <label>Invoice Type Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceController.cls
public with sharing class InvoiceController
{
    public static string GenerateInvoice(List<Id> SelectedOrderIds)
    {
        string strAuditText = '';
        try
        {
            List<Order__c> objOrderList = [SELECT Id, Client__r.Invoice_Type__c, Payment_Status__c, Order_Status__c FROM Order__c WHERE Id = :SelectedOrderIds];
            Map<Id, Order__c> mapOrders = new Map<Id, Order__c>();
            for(Order__c objOrder : objOrderList)
            {
                if (mapOrders.containsKey(objOrder.Id)==false)
                    mapOrders.put(objOrder.Id, objOrder);   
            }
            
            List<Order_Item__c> objOrderItemList = [
                SELECT 
                Id
                , Order__c
                , Path__c
                , Billing_Currency__c
                , Billing_Amount__c
                , Payment_Status__c
                , Invoice__c
                FROM Order_Item__c
                WHERE Payment_Status__c= 'Waiting to Invoice'
                AND Order__c IN :SelectedOrderIds];
            strAuditText += 'SelectedOrderIds:' + SelectedOrderIds;
            strAuditText += '| objOrderItemList:' + objOrderItemList.size();
            for(Order_Item__c objOrderItem: objOrderItemList)
            {
                if (objOrderItem.Path__c == null)
                    objOrderItem.Path__c = '';
                    
                Order__c objOrder = mapOrders.get(objOrderItem.Order__c);
                string UniqueId = '';
                if (objOrder.Client__r.Invoice_Type__c == 'Regular Invoice') 
                    UniqueId = objOrderItem.Order__c + '_' + objOrderItem.Billing_Currency__c;
                else if (objOrder.Client__r.Invoice_Type__c == 'BU Wise') 
                    UniqueId = objOrderItem.Order__c + '_' + objOrderItem.Path__c + '_' + objOrderItem.Billing_Currency__c;
                
                Invoice__c objCurrentInvoice = null;
                List<Invoice__c> objInvoices = [SELECT Id, Invoice_Currency__c, Invoice_Date__c, Invoice_No__c, Invoice_Amount__c, Invoice_Status__c, Invoice_Type_Name__c, Is_Active__c, Order__c FROM Invoice__c WHERE Invoice_Type_Name__c = :UniqueId AND Is_Active__c = true];
                if (objInvoices != null && objInvoices.size()>0)
                {
                    objCurrentInvoice = objInvoices[0];
                    objCurrentInvoice.Invoice_Amount__c += objOrderItem.Billing_Amount__c;
                    UPDATE objCurrentInvoice;
                    objOrderItem.Invoice__c = objCurrentInvoice.Id;
                }
                else
                {
                    objCurrentInvoice = new Invoice__c();
                    objCurrentInvoice.Invoice_Amount__c = objOrderItem.Billing_Amount__c;
                    objCurrentInvoice.Invoice_Date__c = DateTime.Now();
                    objCurrentInvoice.Invoice_Status__c = 'Created'; 
                    objCurrentInvoice.Is_Active__c = true; 
                    objCurrentInvoice.Invoice_No__c = '-'; 
                    objCurrentInvoice.Order__c = objOrderItem.Order__c; 
                    objCurrentInvoice.Invoice_Currency__c = objOrderItem.Billing_Currency__c; 
                    objCurrentInvoice.Invoice_Type_Name__c = UniqueId; 
                    INSERT objCurrentInvoice;
                    
                    Invoice__c objCreatedInvoice = [SELECT Id FROM Invoice__c WHERE Invoice_Type_Name__c = :UniqueId LIMIT 1];
                    objOrderItem.Invoice__c = objCreatedInvoice.Id;
                }
                objOrderItem.Payment_Status__c ='Payment Requested';
            }
            UPDATE objOrderItemList;
            
            for(Order__c objOrder : objOrderList)
            {
                objOrder.Payment_Status__c = 'Invoiced';
                objOrder.Order_Status__c = 'In Progress';
            }
            UPDATE objOrderList;    
        }
        catch(Exception exp)
        {
            strAuditText += 'Error:' + exp.getMessage() + '|' + exp.getStackTraceString();
        }
        finally
        {
            AuditTrailHelper.UpdateAudit('Invoice', strAuditText, 'None');
        }
        return strAuditText;
    }
}