force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_EUR__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_EUR__c</fullName>
    <label>Order Amount EUR</label>
    <summarizedField>Order_Item__c.Invoice_Amount_When_Instruct__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Item__c.Billing_Currency__c</field>
        <operation>equals</operation>
        <value>EUR</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Order_Item__c.Renewal_Instruction__c</field>
        <operation>equals</operation>
        <value>Renew</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_USD_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_USD_Total__c</fullName>
    <formula>Order_Amount_USD__c +  Late_Fee__c +  Rush_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Amount USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <displayFormat>OID-{000000000}</displayFormat>
    <label>Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Renewals__c.field-meta.xml
<CustomField>
    <fullName>Total_Renewals__c</fullName>
    <label>Total Renewals</label>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_ADU_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_ADU_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ADU Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailHelper.cls
public with sharing class EmailHelper
{
    public static List<string> GetEmailIds(boolean IsAdmin, boolean IsADU, boolean IsRTU)
    {
        List<string> lstProfileName = new List<string>();
        if (IsAdmin)
            lstProfileName.add('System Administrator');
        if (IsADU)
            lstProfileName.add('ADU');
        if (IsRTU)
            lstProfileName.add('RTU');
        
        List<Id> lstProfileId = new List<Id>();
        List<Profile> lstProfile = [SELECT Id, Name FROM Profile WHERE Name IN :lstProfileName];
        for(Profile objProfile : lstProfile)
        {
            lstProfileId.add(objProfile.Id); 
        }
        
        List<string> lstUserEmailId = new List<string>();
        List<User> objUserList = [SELECT Id, Email, Is_ADU_Manager__c FROM User WHERE ProfileId IN :lstProfileId AND IsActive= true];
        for(User objUser : objUserList)
        {
            lstUserEmailId.add(objUser.Email);
        }
        return lstUserEmailId;
    }
    public static string Body_WhenNewOrderReceived(List<Order__c> objOrderList)
    {
        string MessageBody = '';
        string TableContent = '';
        string OrderDate = '';
        List<EmailTemplate> objEmailTemplateList = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'To_ADU_when_Order_Received'];
        if (objEmailTemplateList != null && objEmailTemplateList.size()>0)
        {
            MessageBody = objEmailTemplateList[0].Body;
            //MessageBody = 'Hi, order.......{!TableContent} Thanks MaRS...';
            TableContent = '<p><table cellspacing=0 cellpadding=5 border=1 style="border-collapse:collapse;border-style:dotted;border-width:1px;border-color:#888;">';
            TableContent+= '<tr>';
            TableContent+= '<td><b>Client</b></td>';
            TableContent+= '<td><b>Order No.</b></td>';
            TableContent+= '<td><b>Order Date</b></td>';
            TableContent+= '<td><b>No. of Renewals</b></td>';
            TableContent+= '<td><b>Order Amount (USD)</b></td>';
            TableContent+= '<td><b>Order Amount (EUR)</b></td>';
            TableContent+= '</tr>';
            for(Order__c objOrder : objOrderList)
            {
                if (OrderDate != null)
                {
                    string[] OrderDates = String.valueOf(objOrder.Order_Date__c).split(' ');
                    OrderDate = OrderDates[0];
                }
                TableContent+= '<tr>';
                TableContent+= '<td>' + objOrder.Client__r.Client_Name__c  + '</td>';
                TableContent+= '<td>' + objOrder.Order_Number__c + '</td>';
                TableContent+= '<td>' + OrderDate  + '</td>';
                TableContent+= '<td>' + objOrder.Total_Renewals__c + '</td>';
                TableContent += '<td>' + objOrder.Order_Amount_USD_Total__c + '</td>';
                TableContent+= '<td>' + objOrder.Order_Amount_EUR__c + '</td>';
                TableContent+= '</tr>';
            }
            TableContent+= '</table></p>';
            MessageBody = MessageBody.replace('{!TableContent}', TableContent);
        }  
        return MessageBody;     
    }
    public static string Body_WhenNewOrderReceived_ToBeDepricated(List<Order__c> objOrderList)
    {
        string MessageBody = '';
        string OrderDate = '';
        MessageBody += '<html>';
        MessageBody += '<body>';
        MessageBody += 'Hi,';
        MessageBody += '<p>New order has been received from the clients successfully</p>';
        MessageBody += '<p>Order details are given below</p>';
        MessageBody += '<table cellspacing=0 cellpadding=5 border=1 style="border-collapse:collapse;border-style:dotted;border-width:1px;border-color:#888;">';
        MessageBody += '<tr>';
        MessageBody += '<td><b>Client</b></td>';
        MessageBody += '<td><b>Order No.</b></td>';
        MessageBody += '<td><b>Order Date</b></td>';
        MessageBody += '<td><b>No. of Renewals</b></td>';
        MessageBody += '<td><b>Order Amount (USD)</b></td>';
        MessageBody += '<td><b>Order Amount (EUR)</b></td>';
        MessageBody += '</tr>';
        for(Order__c objOrder : objOrderList)
        {
            if (OrderDate != null)
            {
                string[] OrderDates = String.valueOf(objOrder.Order_Date__c).split(' ');
                OrderDate = OrderDates[0];
            }
            MessageBody += '<tr>';
            MessageBody += '<td>' + objOrder.Client__r.Client_Name__c  + '</td>';
            MessageBody += '<td>' + objOrder.Order_Number__c + '</td>';
            MessageBody += '<td>' + OrderDate  + '</td>';
            MessageBody += '<td>' + objOrder.Total_Renewals__c + '</td>';
            MessageBody += '<td>' + objOrder.Order_Amount_USD_Total__c + '</td>';
            MessageBody += '<td>' + objOrder.Order_Amount_EUR__c + '</td>';
            MessageBody += '</tr>';
        }
        MessageBody += '</table>';
        
        MessageBody += '<br/><p>Regards</p>';
        MessageBody += '<p>MARS</p>';
        MessageBody += '</body>';
        MessageBody += '</html>';
        return MessageBody;
    }
    public static string Body_Client_WhenNewOrderReceived(List<Order__c> objOrderList)
    {
        string MessageBody = '';
        string OrderDate = '';
        MessageBody += '<html>';
        MessageBody += '<body>';
        MessageBody += 'Hi,';
        MessageBody += '<p>New order(s) placed successfully</p>';
        MessageBody += '<p>Order details are given below</p>';
        MessageBody += '<table cellspacing=0 cellpadding=5 border=1 style="border-collapse:collapse;border-style:dotted;border-width:1px;border-color:#888;">';
        MessageBody += '<tr>';
        MessageBody += '<td><b>Order No.</b></td>';
        MessageBody += '<td><b>Order Date</b></td>';
        MessageBody += '<td><b>No. of Renewals</b></td>';
        MessageBody += '<td><b>Order Amount (USD)</b></td>';
        MessageBody += '<td><b>Order Amount (EUR)</b></td>';
        MessageBody += '</tr>';
        for(Order__c objOrder : objOrderList)
        {
            if (OrderDate != null)
            {
                string[] OrderDates = String.valueOf(objOrder.Order_Date__c).split(' ');
                OrderDate = OrderDates[0];
            }
            MessageBody += '<tr>';
            MessageBody += '<td>' + objOrder.Order_Number__c + '</td>';
            MessageBody += '<td>' + OrderDate  + '</td>';
            MessageBody += '<td>' + objOrder.Total_Renewals__c + '</td>';
            MessageBody += '<td>' + objOrder.Order_Amount_USD_Total__c + '</td>';
            MessageBody += '<td>' + objOrder.Order_Amount_EUR__c + '</td>';
            MessageBody += '</tr>';
        }
        MessageBody += '</table>';
        
        MessageBody += '<br/><p>Regards</p>';
        MessageBody += '<p>MARS</p>';
        MessageBody += '</body>';
        MessageBody += '</html>';
        return MessageBody;
    }
    public static string Body_WhenPaymentRequested(List<Invoice__c> objInvoiceList)
    {
        string MessageBody = '';
        string OrderDate = '';
        MessageBody += '<html>';
        MessageBody += '<body>';
        MessageBody += 'Hi,';
        MessageBody += '<p>Invoice generated for the received orders</p>';
        MessageBody += '<p>Invoice details are given below</p>';
        MessageBody += '<table cellspacing=0 cellpadding=5 border=1 style="border-collapse:collapse;border-style:dotted;border-width:1px;border-color:#888;">';
        MessageBody += '<tr>';
        MessageBody += '<td><b>Client</b></td>';
        MessageBody += '<td><b>Invoice No.</b></td>';
        MessageBody += '<td><b>Order No.</b></td>';
        MessageBody += '<td><b>Order Date</b></td>';
        MessageBody += '<td><b>Invoice Amount</b></td>';
        MessageBody += '</tr>';
        for(Invoice__c objInvoice : objInvoiceList)
        {
            if (objInvoice != null)
            {
                string[] OrderDates = String.valueOf(objInvoice.Order__r.Order_Date__c).split(' ');
                OrderDate = OrderDates[0];
            }
            MessageBody += '<tr>';
            MessageBody += '<td>' + objInvoice.Order__r.Client__r.Client_Name__c  + '</td>';
            MessageBody += '<td>' + objInvoice.Invoice_No__c + '</td>';
            MessageBody += '<td>' + objInvoice.Order__r.Order_Number__c + '</td>';
            MessageBody += '<td>' + OrderDate  + '</td>';
            MessageBody += '<td align=right>' + objInvoice.Invoice_Currency__c + ' ' + objInvoice.Invoice_Amount__c + '</td>';
            MessageBody += '</tr>';
        }
        MessageBody += '</table>';
        
        MessageBody += '<br/><p>Regards</p>';
        MessageBody += '<p>MARS</p>';
        MessageBody += '</body>';
        MessageBody += '</html>';
        return MessageBody;
    }
    public static string Body_Client_WhenPaymentRequested(List<Invoice__c> objInvoiceList)
    {
        string MessageBody = '';
        string OrderDate = '';
        MessageBody += '<html>';
        MessageBody += '<body>';
        MessageBody += 'Hi,';
        MessageBody += '<p>Invoice generated for the received orders</p>';
        MessageBody += '<p>Invoice details are given below</p>';
        MessageBody += '<table cellspacing=0 cellpadding=5 border=1 style="border-collapse:collapse;border-style:dotted;border-width:1px;border-color:#888;">';
        MessageBody += '<tr>';
        MessageBody += '<td><b>Invoice No.</b></td>';
        MessageBody += '<td><b>Order No.</b></td>';
        MessageBody += '<td><b>Order Date</b></td>';
        MessageBody += '<td><b>Invoice Amount</b></td>';
        MessageBody += '</tr>';
        for(Invoice__c objInvoice : objInvoiceList)
        {
            if (objInvoice != null)
            {
                string[] OrderDates = String.valueOf(objInvoice.Order__r.Order_Date__c).split(' ');
                OrderDate = OrderDates[0];
            }
            MessageBody += '<tr>';
            MessageBody += '<td>' + objInvoice.Invoice_No__c + '</td>';
            MessageBody += '<td>' + objInvoice.Order__r.Order_Number__c + '</td>';
            MessageBody += '<td>' + OrderDate  + '</td>';
            MessageBody += '<td align=right>' + objInvoice.Invoice_Currency__c + ' ' + objInvoice.Invoice_Amount__c + '</td>';
            MessageBody += '</tr>';
        }
        MessageBody += '</table>';
        
        MessageBody += '<br/><p>Regards</p>';
        MessageBody += '<p>MARS</p>';
        MessageBody += '</body>';
        MessageBody += '</html>';
        return MessageBody;
    }
}