force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/trgOrderTest.cls
@isTest
public class trgOrderTest {
    @testSetup static void setup() {
        
        //List<Clients__c> testC = new List<Clients__c>();
        Clients__c clients = new Clients__c();
        insert clients;
        //testC.add(new Clients__c());
        
        //List<Order__c> testCand = new List<Order__c>();
        Order__c cand = new Order__c();
        cand.Client__c = clients.Id;
        cand.Payment_Status__c = 'To be Invoiced';
        insert cand;
        //testCand.add(new Order__c(Client__c = clients.Id, Payment_Status__c = 'To be Invoiced'));
        //insert testCand;  
        /*
        cand.Client__c = clients.Id;
        cand.Payment_Status__c = 'Invoiced';
        testCand.add(new Order__c(Client__c = clients.Id, Payment_Status__c = 'Invoiced'));
        upsert testCand;
        */
    }
    @isTest public static void TestMethod1()
    {
     test.startTest();
     //List<Order__c> testCand = [SELECT Client__c, Payment_Status__c FROM Order__c WHERE Payment_Status__c = 'To be Invoiced'];
     Order__c cand = [SELECT Client__c, Payment_Status__c FROM Order__c WHERE Payment_Status__c = 'To be Invoiced'];
     cand.Payment_Status__c = 'Invoiced';
     update cand;
     test.stopTest();
     System.assertEquals('Invoiced', cand.Payment_Status__c);
    }
}