force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Jurisdiction__c/Jurisdiction__c.object-meta.xml
<CustomObject>
    <label>Jurisdiction</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jurisdictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <displayFormat>OID-{000000000}</displayFormat>
    <label>Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Validation_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Request_Status__c</fullName>
    <label>Validation Request Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Entity_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_Name__c</fullName>
    <label>Entity Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PTO Fee (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Amount_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount_When_Pay__c</fullName>
    <formula>if 
(
(TEXT(Fee_Currency__c) == TEXT(Billing_Currency__c))
,(Fee__c +  Claim_Fee__c +  Surcharge__c)
,(((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate_When_Pay__c)/Billing_Currency_Unit_Rate_When_Pay__c)
+((((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate_When_Pay__c)/Billing_Currency_Unit_Rate_When_Pay__c) * (CE_Markup_Percentage__c /100))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTO Fee (Payable)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice_Type_Name_Value__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name_Value__c</fullName>
    <formula>if(
     TEXT(Order__r.Client__r.Invoice_Type__c) == &apos;Regular Invoice&apos;
     ,  Order__r.Client__r.Id + &apos;_&apos; +  Order__r.Id + &apos;_&apos; +  TEXT(Billing_Currency__c )
     , if ( 
          Path__c == null
          , Order__r.Client__r.Id + &apos;_&apos; +  Order__r.Id + &apos;_&apos; +  TEXT(Billing_Currency__c)
          , Order__r.Client__r.Id + &apos;_&apos; +  Order__r.Id + &apos;_&apos; +  Path__c  + &apos;_&apos; +  TEXT(Billing_Currency__c) 
     )
)</formula>
    <label>Invoice Type Name Value</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/MV_API_Ref_Id__c.field-meta.xml
<CustomField>
    <fullName>MV_API_Ref_Id__c</fullName>
    <label>MV API Ref Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PTO_Validation_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>PTO_Validation_Request_ID__c</fullName>
    <label>PTO Validation Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Term_Name__c.field-meta.xml
<CustomField>
    <fullName>Term_Name__c</fullName>
    <label>Term</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchValidateWithPTO.cls
public class batchValidateWithPTO implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful
{
    public string query{set;get;}
    public List<ptoValidationReqWrapper> mapData{set;get;}
    public List<string> orderIds{set;get;}
    public List<Id> assetIds{set;get;}
    List<Order__c> orders{set;get;}
    public Map<string,List<Order_Item__c>> mapOrderItem{set;get;}
    public string strAuditTrail{set;get;}
    public string status{set;get;}
    public batchValidateWithPTO()
    {
        query = '';
        mapData = NEW List<ptoValidationReqWrapper>();
        orderIds = NEW List<string>();
        orders = NEW List<Order__c>();
        mapOrderItem = NEW Map<string,List<Order_Item__c>>();
        orders = [SELECT Id,Validation_Request_Status__c FROM Order__c WHERE Order_Status__c=:'Order Placed' AND Validation_Request_Status__c!='Success'];
        for(Order__c order:orders)
        {
            orderIds.add(order.Id);
        }
        query = 'Select id,Name,Order__r.Client__c,PTO_Validation_Request_ID__c,Paid_Status__c,Surcharge__c,'+
                    'Payment_Status__c,Order_Number__c,Client__c,Jurisdiction__c,Billing_Currency__c,Entity_Type_Name__c,'+
                    'Fee_Amount_When_Pay__c,Fee__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c,Filing_Date__c,'+
                    'Invoice_Type_Name_Value__c,Invoice__c,Invoice__r.Name,Term_Name__c FROM Order_Item__c '+
                    'WHERE Order__c IN: orderIds';
    }
    public batchValidateWithPTO(List<Id> assetId)
    {
        assetIds = NEW List<Id>(); 
        assetIds=assetId;
        orders = NEW List<Order__c>();
        orderIds = NEW List<string>();
        query = '';
        mapData = NEW List<ptoValidationReqWrapper>();
        mapOrderItem = NEW Map<string,List<Order_Item__c>>();
        query = 'Select id,Name,Order__r.Client__c,PTO_Validation_Request_ID__c,Paid_Status__c,Surcharge__c,'+
                    'Payment_Status__c,Order_Number__c,Client__c,Jurisdiction__c,Billing_Currency__c,Entity_Type_Name__c,'+
                    'Fee_Amount_When_Pay__c,Fee__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c,Filing_Date__c,'+
                    'Invoice_Type_Name_Value__c,Invoice__c,Invoice__r.Name,Term_Name__c FROM Order_Item__c '+
                    'WHERE Id IN: assetIds';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Order_Item__c> scope)
    {
        strAuditTrail='BatchValidateWithPTO class invoked|';
        strAuditTrail+='New OrderIds - '+orderIds+'|';
        for(Order_Item__c oi : scope)
        {
            List<Order_Item__c> temp = mapOrderItem.get(oi.Jurisdiction__c);
            if(temp != null)
            {
                temp.add(oi);
            }
            else
            {
                mapOrderItem.put(oi.Jurisdiction__c, new List<Order_Item__c>{oi});
            }
        }
        strAuditTrail+='scopeSize - '+scope.size()+'|';
    }
    public void finish(Database.BatchableContext BC)
    {
        List<Order__c> orderToBeUpdated=new List<Order__c>();
        try
        {
            if(mapOrderItem.size()>0)
            {
                for(string cc : mapOrderItem.keyset())
                {
                    List<Order_Item__c> items = mapOrderItem.get(cc);
                    ptoValidationReqWrapper wrp = NEW ptoValidationReqWrapper();
                    wrp.countryCode = cc;
                    wrp.countryAssets = items;
                    mapData.add(wrp);
                }
                status='Success';
                for(Order__c order:orders)
                {
                    order.Validation_Request_Status__c='Success';
                    orderToBeUpdated.add(order);
                }
                batchPtoPaymentValidateAPI cls = NEW batchPtoPaymentValidateAPI(mapData);
                database.executeBatch(cls,1);
                if(orderToBeUpdated.size()>0)
                	update orderToBeUpdated;
            }
        }
        catch(exception e)
        {
            for(Order__c order:orders)
            {
                order.Validation_Request_Status__c='Failed';
                orderToBeUpdated.add(order);
            }
            if(orderToBeUpdated.size()>0)
            	update orderToBeUpdated;
            status = 'Fail';
            strAuditTrail += ' || Error :'+e.getMessage()+' | Line No:'+e.getLineNumber()+' | Cause: '+e.getCause();
            system.debug('Error :'+e.getMessage()+' | Line No:'+e.getLineNumber()+' | Cause: '+e.getCause());
        }
        finally
        {
            system.debug(strAuditTrail);
            AuditTrailHelper.UpdateAudit('BatchValidateWithPTO',strAuditTrail,status);
        }
    }
}