force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billing_Amount__c</fullName>
    <label>Billing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Amount_When_Instruct__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount_When_Instruct__c</fullName>
    <formula>if 
(
(TEXT( Fee_Currency__c)== TEXT( Billing_Currency__c ))
,(Fee__c +  Claim_Fee__c +  Surcharge__c)
, (((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate__c)/Billing_Currency_Unit_Rate__c)
+ ((((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate__c)/Billing_Currency_Unit_Rate__c) *  (CE_Markup_Percentage__c /100))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTO Fee  (Invoiced)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PTO_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>PTO_Payment_Amount__c</fullName>
    <formula>CEILING(Fee__c * Bank_Rate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTO Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Amount_When_Instruct__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Amount_When_Instruct__c</fullName>
    <formula>if 
(
(TEXT(Service_Fee_Currency__c)==TEXT(Billing_Currency__c))
, Service_Fee__c
, ((Service_Fee__c/Service_Fee_Unit_Rate__c)/Billing_Currency_Unit_Rate__c)
+ (((Service_Fee__c/Service_Fee_Unit_Rate__c)/Billing_Currency_Unit_Rate__c) * (CE_Markup_Percentage__c /100))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Fee Amount (When Instruct)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Variance__c.field-meta.xml
<CustomField>
    <fullName>Variance__c</fullName>
    <formula>((Fee_Amount_When_Pay__c -  Fee_Amount_When_Instruct__c) / Fee_Amount_When_Instruct__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Variance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Variance_Amount__c</fullName>
    <formula>Fee_Amount_When_Instruct__c-PTO_Payment_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceWithVarianceController.cls
public with sharing class CreateInvoiceWithVarianceController {
    private ApexPages.StandardSetController standardController;
    Public list<String> selectedOrderIds{Set;Get;}
    list<Order__c> selectedOrders = new list<Order__c>(); 
   	public  static List<Order_Item__c> assets = new List<Order_Item__c>();
    Public String listviewURL{Set;Get;}
    Public String client = '';
    Public static Boolean isInvalid {Set;Get;} 
    Public static String disableSubmit {Set;Get;} 
    Public static String errorMessage{Set;Get;} 
    Public string strAuditText = '';
    
 	Public CreateInvoiceWithVarianceController(ApexPages.StandardSetController controller) {
        this.standardController = controller;
        GetListViewURL(); //Get return URL 
        GetSelectedOrderIds(); //Get list of ids of the selected Orders
        isInvalid = False;
        disableSubmit = '';
    }
    
    /*
     * Gets the Listview URL from where the assets are selected.
	*/
     Public void GetListViewURL(){
        //Get the return url if it's in Lightning view
        listviewURL = ApexPages.currentPage().getParameters().get('vfRetURLInSFX');
        If(listviewURL == null || listviewURL == '')
        {
            //Get the return url if it's in classic view
            listviewURL = ApexPages.currentPage().getParameters().get('retURL');
        }
    }
    
        /*
     * Gets all the selected asset ids.
	*/
    Public void GetSelectedOrderIds(){
        //Get list of ids of the selected Orders
        selectedOrderIds = New List <String> ();
        selectedOrders = (Order__c[])this.standardController.getSelected();
        if(selectedOrders!=null && selectedOrders.size()>0)
        {     
            for(Order__c orderitem : selectedOrders){
            	selectedOrderIds.add(orderitem.Id);
            }
        }
    }
    
     public List<Order_Item__c> getAssets() {
         try
         {
             if(selectedOrderIds.size() == 0){
                 errorMessage = 'Select atleast one order';
                 isInvalid = True;
             }else{
                 //Get all asset details
                assets = [SELECT Name,Application_No__c,Patent_No__c,Order__r.Name,Order__r.Client__c,Fee_Amount_When_Instruct__c,PTO_Payment_Amount__c,Service_Fee_Amount_When_Instruct__c,Variance_Amount__c,Payment_Status__c,Billing_Amount__c,Variance__c FROM Order_Item__c WHERE Order__c IN: selectedOrderIds AND Variance__c > 0];                
                selectedOrderIds = new list<Id>();
                 for(Order_Item__c asset : assets){
                     selectedOrderIds.add(asset.Order__c);
                 }
                 selectedOrders = new List<Order__c>();
                 selectedOrders = [SELECT Id FROM Order__c WHERE Id IN: selectedOrderIds];
                if(assets.size() > 0)
                {            
                    client = assets[0].Order__r.Client__c;
                    for(Order_Item__c asset : assets)
                    {                    
                        //Check if all the orders have same client id
                        if(client != asset.Order__r.Client__c)
                        {          
                            errorMessage = 'Orders of different clients cannot be selected';                    
                            isInvalid = True;
                            break;
                        }
                    }  
                }
                else{
                    errorMessage = 'The selected orders have no asset with positive variance';
                    isInvalid = True;           
                }
             }
            
        }
        catch(Exception e)
        {
            AuditTrailHelper.UpdateAudit('CreateInvoiceWithVarianceController','Exception: ' + e.getMessage() + e.getLineNumber(),'None');
        }
        return assets;
    }
    
    Public PageReference Submit() {
        for(Order__c order : selectedOrders){
            order.Payment_Status__c = 'Invoiced Variance Amount';
        }  
        update selectedOrders;
        AuditTrailHelper.UpdateAudit('CreateInvoiceWithVarianceController','updated','None');
        if (selectedOrderIds != null && selectedOrderIds.size() > 0)
        {
            AuditTrailHelper.UpdateAudit('CreateInvoiceWithVarianceController',' Invoices to be modified for the order(s):' + selectedOrderIds,'None');
            BatchQueueHelper.CreateBatchQueueForInvoiceGeneration(selectedOrderIds);
        }
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Request to generate Invoice has been placed!'));
        return null;
    }
}