force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Is_PTO_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Is_PTO_Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PTO fee paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Is_Renewed_Externally__c.field-meta.xml
<CustomField>
    <fullName>Is_Renewed_Externally__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Renewed Externally?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Received_from_Client__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_from_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Received from Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PoNumber__c.field-meta.xml
<CustomField>
    <fullName>PoNumber__c</fullName>
    <label>PoNumber</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Send_for_approval_to_pay_PTO_fee__c.field-meta.xml
<CustomField>
    <fullName>Send_for_approval_to_pay_PTO_fee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Are you requesting approval from your manager to pay PTO even if the payment not yet received from the client?</inlineHelpText>
    <label>Send for approval to pay PTO fee?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/trgOrderItemTest.cls
@isTest
public class trgOrderItemTest {
    
    @testSetup static void setup() {
        
        //usr.Profile.Name = 'ADU';
        //usr.Is_ADU_Manager__c = true;
        //update usr;
        //System.assertEquals('ADU', usr.Profile.Name);
        //System.assertEquals(true, usr.Is_ADU_Manager__c);
        
        List<Clients__c> testC = new List<Clients__c>();
        Clients__c clients = new Clients__c();
        insert clients;
        testC.add(new Clients__c());
        
        List<Order__c> testCand = new List<Order__c>();
        
        Order__c cand = new Order__c();
        cand.Client__c = clients.Id;
        insert cand;
        testCand.add(new Order__c(Client__c = clients.Id));
        
        insert testCand;  
        
        List<Order_Item__c> candior = new List<Order_Item__c>();
        Order_Item__c candor = new Order_Item__c();
        candor.Order__c = cand.Id;
        candor.Amount__c = 100;
        candor.PoNumber__c = 'ABC1';
        candor.Payment_Status__c = 'Waiting to Invoice';
        //candor.Is_Renewed_Externally__c = false;
        //candor.Invoice__c = null;
        candor.Payment_Received_from_Client__c = false;
        candor.Send_for_approval_to_pay_PTO_fee__c = true;
        candor.Renewal_Instruction__c = 'Renew';
        candor.Is_PTO_Fee_Paid__c = false;
        
        insert candor;
        system.debug('OI 1: '+ candor);
        candior.add(new Order_Item__c(Order__c = cand.Id, Amount__c = 100, PoNumber__c = 'ABC1' ));
        insert candior;
        
       
        
        
        
        /*candor.Order__c = cand.Id;
candor.Amount__c = 101;
candior.add(new Order_Item__c(Order__c = cand.Id, Amount__c = 101));
upsert candior;*/
        
    }
    
    @isTest public static void TestMethod1()
    { 
        test.startTest();
        
        List<Order__c> cand = [SELECT Client__c FROM Order__c];
            
        /* Invoice__c inv = new Invoice__c();
         Inv.Invoice_Amount__c = 2000.0;
            Inv.Order__c = cand[0].id;
            Inv.Invoice_Currency__c ='USD';
        insert inv; */
        
            List<Order_Item__c> candor = [SELECT Order__c, Amount__c, PoNumber__c, Payment_Status__c, Payment_Received_from_Client__c,Send_for_approval_to_pay_PTO_fee__c,Renewal_Instruction__c, Is_PTO_Fee_Paid__c  FROM Order_Item__c WHERE Amount__c = 100];
            for(Order_Item__c obj : candor )
            {
                obj.Payment_Status__c = 'Payment Requested';
                obj.PoNumber__c = 'ABC2';
                obj.Amount__c = 101;
                obj.Is_PTO_Fee_Paid__c = true;
                //obj.Is_Renewed_Externally__c = true;
              //  obj.Invoice__c = inv.Id;
            }
            if(candor.size() > 0)
            {
                update candor;
            }
            system.debug('Update OI: '+candor);
            test.stopTest();
         System.assertEquals('Payment Requested', candor[0].Payment_Status__c);
         System.assertEquals('ABC2', candor[0].PoNumber__c);
         System.assertEquals(101, candor[0].Amount__c);
       // System.assertEquals(true, candor[0].Is_Renewed_Externally__c);
           // System.assertEquals(inv.Id, candor[0].Invoice__c);
           System.assertEquals(true, candor[0].Is_PTO_Fee_Paid__c);
           
        
    }
}