force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/EndPoint_URL__c.field-meta.xml
<CustomField>
    <fullName>EndPoint_URL__c</fullName>
    <label>EndPoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Approval__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approval__c</fullName>
    <label>Cancellation Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approved_Date__c</fullName>
    <label>Cancellation Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Rejected_Date__c</fullName>
    <label>Cancellation Rejected Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Filing_Receipt_File_Id__c.field-meta.xml
<CustomField>
    <fullName>Filing_Receipt_File_Id__c</fullName>
    <label>Filing Receipt File Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Filing_Receipt_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Filing_Receipt_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filing Receipt Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/batchInstructionStatusUpdate.cls
public class batchInstructionStatusUpdate implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful{
    //--------------------------
    public List<string> recordIDs {set;get;}
    public string query{set;get;}
    public string recordStatus{set;get;}
    //--------------------------
    
    public batchInstructionStatusUpdate(List<string> recid,String recStatus)
    {
        system.debug('>> Id\'s: '+recid+' Status:'+  recStatus);
        recordIDs = NEW List<string>();
        recordIDs = recid;
        recordStatus = '';
        recordStatus = recStatus;
        query = 'SELECT id,Name,Filing_Receipt_Uploaded__c,Filing_Receipt_File_Id__c,Order__r.Client__c,Order__r.Client__r.Endpoint_URL__c,Cancellation_Approval__c  FROM Order_Item__c where ID IN: recordIDs';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Order_Item__c> scope)
    {
        string strAuditTrail = '';
        string Status = 'Success';
        try
        {
            List<Order_Item__c> orderItems=new List<Order_Item__c>();
            for(Order_Item__c oi : scope)
            {
                req r = NEW req();     
                r.OrderName = oi.Name;
                r.Status = recordStatus;                
                string jsonbody = JSON.serialize(r);
                strAuditTrail += 'jsonbody: '+jsonbody;
                string AccessToken = SymphonyAuthenticaionHelper.SymphonyAuthenticaionHelper(oi.Order__r.Client__c);
                strAuditTrail+='>>>'+AccessToken;
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setMethod('POST');
                req.setEndpoint(oi.Order__r.Client__r.Endpoint_URL__c+'/statusupdate/instructionstatus/');
                //system.debug('>>>'+oi.Order__r.Client__r.Endpoint_URL__c+'/statusupdate/instructionstatus/');
                strAuditTrail += 'URL - '+oi.Order__r.Client__r.Endpoint_URL__c+'/statusupdate/instructionstatus/';
                req.setHeader('Authorization', 'Bearer ' + AccessToken);
                req.setHeader('Content-Type','application/json;charset=UTF-8');
                req.setHeader('Content-Length', string.valueOf(jsonbody.length()));            
                req.setBody(jsonbody);
                HttpResponse res = http.send(req);  
                //strAuditTrail+='Response status code :'+res.getStatusCode() +' |Status :'+res.getStatus() +' |Body '+res.getBody();          
                strAuditTrail += 'Req:'+jsonbody+' |Res Status: '+res.getStatus()+' |Status Code: '+res.getStatusCode()+' |Body: '+res.getBody();               
                if(recordStatus=='Rejected')
                {
                    oi.Cancellation_Rejected_Date__c = System.today();
                    orderItems.add(oi);
                }   
                else if(recordStatus=='Approved')
                {
                    oi.Cancellation_Approved_Date__c=System.today();
                    orderItems.add(oi);
                }
            }
            if(orderItems.size()>0)
            	update orderItems;
        }
        catch(exception e)
        {
            strAuditTrail += e.getmessage()+'||'+e.getLineNumber();
            Status = 'Fail';
        }
        finally
        {
            AuditTrailHelper.UpdateAudit('batchInstructionStatusUpdate', strAuditTrail, Status);
        }
    } 
    
    
    public void finish(Database.BatchableContext BC)
    {
        
    }
    public class req
    {
        public string OrderName{set;get;}
        public string Status{set;get;}
        
    }
}