force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_EUR__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_EUR__c</fullName>
    <label>Order Amount EUR</label>
    <summarizedField>Order_Item__c.Invoice_Amount_When_Instruct__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Item__c.Billing_Currency__c</field>
        <operation>equals</operation>
        <value>EUR</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Order_Item__c.Renewal_Instruction__c</field>
        <operation>equals</operation>
        <value>Renew</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_USD_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_USD_Total__c</fullName>
    <formula>Order_Amount_USD__c +  Late_Fee__c +  Rush_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Amount USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <displayFormat>OID-{000000000}</displayFormat>
    <label>Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Renewals__c.field-meta.xml
<CustomField>
    <fullName>Total_Renewals__c</fullName>
    <label>Total Renewals</label>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailController.cls
public with sharing class EmailController
{
    public static void SendToADU_WhenNewOrderReceived(List<Id> lstOrderId)
    {
        string strAuditText = '';
        try
        {
            List<String> Receivers = EmailHelper.GetEmailIds(true, true, false);
            List<Order__c> objOrderList = [SELECT  Id, Name, Payment_Status__c, Order_Number__c, Order_Date__c, Total_Renewals__c, Client__r.Client_Name__c, Order_Amount_USD_Total__c, Order_Amount_EUR__c FROM Order__c WHERE Id IN :lstOrderId];
            string strMessageBody = EmailHelper.Body_WhenNewOrderReceived(objOrderList);
            
            Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
            objMail.setSubject(objOrderList.size() +  ' new orders received from clients');
            objMail.setToAddresses(Receivers);
            objMail.setHtmlBody(strMessageBody); 
            if(!test.isRunningTest()){
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { objMail});
            }
        }
        catch(Exception exp)
        {
            strAuditText += '[Exceptionr raised. Message:' + exp.getMessage() + ', Other:' + exp.getStacktraceString() + ']';
        }
        finally
        {
            AuditTrailHelper.UpdateAudit('EmailController.SendToADU_WhenNewOrderReceived', strAuditText, 'None');
        }
    }
    public static void SendToClient_WhenNewOrderReceived(List<Id> lstOrderId)
    {
        Map<Id, List<Order__c>> mapClientOrders = new Map<Id, List<Order__c>>();
        Map<Id, string> mapClientEmail = new Map<Id, string>();
        List<Order__c> objOrderList = [SELECT  Id, Name, Payment_Status__c, Order_Number__c, Order_Date__c, Total_Renewals__c, Client__c, Client__r.Client_Name__c, Client__r.Contact_Email_Id__c, Order_Amount_USD_Total__c, Order_Amount_EUR__c FROM Order__c WHERE Id IN :lstOrderId];
        for(Order__c objOrder : objOrderList)
        {
            if (mapClientOrders.containsKey(objOrder.Client__c)==false)
            {
                List<Order__c> objClientOrderList =  new List<Order__c>();
                objClientOrderList.add(objOrder);
                mapClientOrders.put(objOrder.Client__c,objClientOrderList);
                mapClientEmail.put(objOrder.Client__c, objOrder.Client__r.Contact_Email_Id__c);
            }
            else
            {
                List<Order__c> objClientOrderList =  mapClientOrders.get(objOrder.Client__c);
                objClientOrderList.add(objOrder);
                mapClientOrders.put(objOrder.Client__c,objClientOrderList);
            }
        }
        
        List<Messaging.SingleEmailMessage> objMessageList = new List<Messaging.SingleEmailMessage>();
        Set<Id> objClientIds = mapClientOrders.keySet();
        for(Id ClientId : objClientIds)
        {
            if (mapClientOrders.containsKey(ClientId))
            {
                List<Order__c> objClientOrderList = mapClientOrders.get(ClientId); 
                List<String> Receivers = new List<String>();
                if (mapClientEmail.containsKey(ClientId))
                    Receivers.add(mapClientEmail.get(ClientId));
                
                string strMessageBody = EmailHelper.Body_Client_WhenNewOrderReceived(objClientOrderList);
                Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
                objMail.setSubject('Orders placed to MaxVal successfully');
                objMail.setToAddresses(Receivers);
                objMail.setHtmlBody(strMessageBody); 
                objMessageList.add(objMail);
            }
        }
        if(!test.isRunningTest()){
        	Messaging.sendEmail(objMessageList);
        }
    }
    public static void SendToADU_WhenPaymentRequested(List<Id> lstOrderId)
    {
        List<String> Receivers = EmailHelper.GetEmailIds(true, true, false);
        List<Invoice__c> objInvoiceList = [SELECT Id, Order__r.Order_Date__c, Order__r.Client__r.Client_Name__c, Invoice_No__c, Order__r.Order_Number__c, Invoice_Currency__c, Invoice_Amount__c FROM Invoice__c WHERE Order__c IN :lstOrderId];
        string strMessageBody = EmailHelper.Body_WhenPaymentRequested(objInvoiceList);
        
        Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
        objMail.setSubject('Invoice generated and payment requested from clients');
        objMail.setToAddresses(Receivers);
        objMail.setHtmlBody(strMessageBody); 
        if(!test.isRunningTest()){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { objMail});
        }
    }
    public static void SendToClient_WhenPaymentRequested(List<Id> lstOrderId)
    {
        Map<Id, List<Invoice__c>> mapClientInvoices = new Map<Id, List<Invoice__c>>();
        Map<Id, string> mapClientEmail = new Map<Id, string>();
        List<Invoice__c> objInvoiceList = [SELECT Id, Order__r.Order_Date__c, Order__r.Client__c, Order__r.Client__r.Client_Name__c, Order__r.Client__r.Contact_Email_Id__c, Invoice_No__c, Order__r.Order_Number__c, Invoice_Currency__c, Invoice_Amount__c FROM Invoice__c WHERE Order__c IN :lstOrderId];
        system.debug(objInvoiceList.size());        
        //List<Order__c> objOrderList = [SELECT  Id, Name, Payment_Status__c, Order_Number__c, Order_Date__c, Total_Renewals__c, Client__c, Client__r.Client_Name__c, Client__r.Contact_Email_Id__c, Order_Amount_USD_Total__c, Order_Amount_EUR__c FROM Order__c WHERE Id IN :lstOrderId];
        for(Invoice__c objInvoice : objInvoiceList)
        {
            if (mapClientInvoices.containsKey(objInvoice.Order__r.Client__c)==false)
            {
                List<Invoice__c> objClientInvoiceList =  new List<Invoice__c>();
                objClientInvoiceList.add(objInvoice);
                mapClientInvoices.put(objInvoice.Order__r.Client__c,objClientInvoiceList);
                mapClientEmail.put(objInvoice.Order__r.Client__c, objInvoice.Order__r.Client__r.Contact_Email_Id__c);
            }
            else
            {
                List<Invoice__c> objClientInvoiceList =  mapClientInvoices.get(objInvoice.Order__r.Client__c);
                objClientInvoiceList.add(objInvoice);
                mapClientInvoices.put(objInvoice.Order__r.Client__c,objClientInvoiceList);
            }
        }
        
        List<Messaging.SingleEmailMessage> objMessageList = new List<Messaging.SingleEmailMessage>();
        Set<Id> objClientIds = mapClientInvoices.keySet();
        system.debug(objClientIds);        
        for(Id ClientId : objClientIds)
        {
            if (mapClientInvoices.containsKey(ClientId))
            {
                List<Invoice__c> objClientInvoiceList = mapClientInvoices.get(ClientId); 
                List<String> Receivers = new List<String>();
                if (mapClientEmail.containsKey(ClientId))
                    Receivers.add(mapClientEmail.get(ClientId));
                
                string strMessageBody = EmailHelper.Body_Client_WhenPaymentRequested(objClientInvoiceList);
                Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
                objMail.setSubject('Invoices generated for your order');
                objMail.setToAddresses(Receivers);
                objMail.setHtmlBody(strMessageBody); 
                objMessageList.add(objMail);
            }
        }
        system.debug(objMessageList.size()); 
        if(!test.isRunningTest()){
            Messaging.sendEmail(objMessageList);
        }
    }
    
}