force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Symphony_Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Org_Id__c</fullName>
    <label>Symphony Org Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Symphony_Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Org_Id__c</fullName>
    <label>Symphony Org Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Client_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Order_Id__c</fullName>
    <label>Client Order Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Instruction_Type__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Type__c</fullName>
    <label>Instruction Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Asset__c.field-meta.xml
<CustomField>
    <fullName>Total_Asset__c</fullName>
    <label>Total Asset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Adjusted_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_Expiration_Date__c</fullName>
    <label>Adjusted Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Agent_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fee_Currency__c</fullName>
    <label>Agent Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Asset_Index__c.field-meta.xml
<CustomField>
    <fullName>Asset_Index__c</fullName>
    <label>Asset Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Approval__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approval__c</fullName>
    <label>Cancellation Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Claim_Fee__c.field-meta.xml
<CustomField>
    <fullName>Claim_Fee__c</fullName>
    <label>Claim Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Docket_No__c.field-meta.xml
<CustomField>
    <fullName>Docket_No__c</fullName>
    <label>Docket No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Entity_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_Name__c</fullName>
    <label>Entity Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Extension_Package_Version__c.field-meta.xml
<CustomField>
    <fullName>Extension_Package_Version__c</fullName>
    <label>Extension Package Version</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PTO Fee (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Fee_Currency__c</fullName>
    <label>Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Fee_Unit_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fee Unit Rate (When Instruct)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Instructed_By__c.field-meta.xml
<CustomField>
    <fullName>Instructed_By__c</fullName>
    <label>Instructed By</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Instructed_Date__c.field-meta.xml
<CustomField>
    <fullName>Instructed_Date__c</fullName>
    <label>Instructed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Publication_No__c.field-meta.xml
<CustomField>
    <fullName>Publication_No__c</fullName>
    <label>Publication No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Currency__c</fullName>
    <label>Service Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Unit_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Service Fee Unit Rate (When Instruct)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SymphonyIPM_Version__c.field-meta.xml
<CustomField>
    <fullName>SymphonyIPM_Version__c</fullName>
    <label>SymphonyIPM Version</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Term_Name__c.field-meta.xml
<CustomField>
    <fullName>Term_Name__c</fullName>
    <label>Term</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <formula>Order__r.Client__r.Symphony_Org_Id__c + &apos;_&apos; +  Application_No__c + &apos;_&apos; +  Term_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Currency_All.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AQD</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <masterLabel>Currency All</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RenewalAPIController.cls
@RestResource(urlMapping='/renewals/InstructRenewal/*')
global class RenewalAPIController
{
    
    @HttpGet
    global static string getMessge() 
    {
        return 'Success';
    }
    //@HttpPost
    //global static string doPost(string AppNo, string DocketNo) 
    //{
    //    return AppNo + '-' + DocketNo;
    //}
    
    //global static string InstructRenewal
    @HttpPost
    global static resp InstructRenewal()
    {
        string strAudit = '';
        //string ReturnValue = '';
        resp ReturnValue = new resp();
        String jsonString = RestContext.request.requestBody.toString();
        JSONParser parser = JSON.createParser(jsonString);
        requestbody res = (requestbody)parser.readValueAs(requestbody.class);
        strAudit+='response - '+res;
        system.debug(res);
        try
        {
            //Check Unique Name
            boolean CanProceedFurther = true;
            boolean CanProceedToUpdate = false;
            string orderItemId = '';
            string orderItemName = '';
            string strUniqueName = res.ClientOrgId + '_' + res.ApplicationNo + '_' + res.PatentNo + '_' + res.TermName;
            system.debug('inside try - unique-'+strUniqueName);
            Order_Item__c objExistingOrderItem = null;
            List<Order_Item__c> objOrderItemList = [SELECT Id, Name, Renewal_Instruction__c, Payment_Status__c, Cancellation_Approval__c,Unique_Name__c FROM Order_Item__c WHERE Unique_Name__c=:strUniqueName];
            if (objOrderItemList != null && objOrderItemList.size()>0)
            {
                ReturnValue.IsSuccess = true;
                objExistingOrderItem = objOrderItemList[0];
                orderItemId = objOrderItemList[0].id;
                orderItemName = objOrderItemList[0].Name;
                if (objExistingOrderItem.Renewal_Instruction__c == 'Renew' && res.RenewalInstruction == 'Cancel')
                {
                    if (objExistingOrderItem.Payment_Status__c == 'Waiting to Invoice' || objExistingOrderItem.Payment_Status__c == 'Payment Requested' || objExistingOrderItem.Payment_Status__c == 'Payment Received')
                    {
                        objExistingOrderItem.Cancellation_Approval__c = 'Requested';
                        UPDATE objExistingOrderItem;
                        ReturnValue.Message = 'Message: Your request will be processed soon';
                        CanProceedFurther = false;
                    }
                    else
                    {
                        ReturnValue.Message = 'Message: PTO fee payment process is in progress. Unable to cancel';
                        CanProceedFurther = false;
                    }
                }
                else if (res.MaRSRenewalID!='-' && res.MaRSRenewalID!=null && res.MaRSRenewalID!='' && objExistingOrderItem.Renewal_Instruction__c == 'Renew' && res.RenewalInstruction == 'Renew' && objExistingOrderItem.Name == res.MaRSRenewalID)
                {
                    //ReturnValue.Message = 'Message: Aleady instructed this renewal';
                    CanProceedFurther = false;
                    CanProceedToUpdate = true;
                } 
                else if (objExistingOrderItem.Renewal_Instruction__c == 'Renew' && res.RenewalInstruction == 'Renew')
                {
                    ReturnValue.Message = 'Message: Already instructed this renewal';
                    ReturnValue.Status = 'Instruct Failed';
                    CanProceedFurther = false;
                } 
            }
            
            //Get the client Details
            Clients__c objClient = null;
            List<Clients__c> objClients = [SELECT Id,Name FROM Clients__c WHERE Symphony_Org_Id__c= :res.ClientOrgId];
            system.debug('clients-'+objClients);
            if (objClients!= null && objClients.size()>0)
                 objClient = objClients[0];
            if (CanProceedFurther)
            {
                system.debug('CanProceedFurther');
                //Create order for the instructions
                Order__c objOrder = null;
                List<Order__c> objOrders = [SELECT Id,Total_Asset__c FROM Order__c WHERE Client_Order_Id__c = :res.ClientOrderId AND Client__c = :objClient.Id];
                system.debug('order-'+objOrders);
                if (objOrders != null && objOrders.size()>0)
                     objOrder = objOrders[0];
                if (objOrder == null)
                {
                    objOrder = new Order__c();
                    objOrder.Client_Order_Id__c = res.ClientOrderId;
                    objOrder.Order_Date__c =  system.now();//Date.Today();
                    objOrder.Client__c = objClient.Id; 
                    objOrder.Order_Status__c = 'Order Placed';
                    objOrder.Payment_Status__c = 'To be Invoiced';
                    objOrder.Instruction_Type__c=res.InstructionType;
                    objOrder.Total_Asset__c  = res.TotalAssets;
                    INSERT objOrder;            
                }
                AuditTrailHelper.UpdateAudit('InstructRenewal-API', 'objOrder:' + objOrder, 'None');
                
                //Create instructions against the order for the instructions
                Order_Item__c objOrderItem = new Order_Item__c();
               
                objOrderItem.Jurisdiction__c = res.Jurisdiction;
                objOrderItem.Application_No__c = res.ApplicationNo;
                /*MARS-728 - Publication number should be added in Asset Detail view in MaRS*/
                /*Modified by Saranyaa*/
                objOrderItem.Publication_No__c = res.PublicationNo;
                objOrderItem.Docket_No__c = res.DocketNo;
                //strAudit += ' ApplicationDate :'+res.ApplicationDate;
                //Modified by Sneha - MARS-816- Filing Date should be passed to MaRS and display in Asset Detail view
                //if(res.ApplicationDate !=null && res.ApplicationDate!='')
                    //objOrderItem.Application_Date__c = Date.valueOf(res.ApplicationDate);
                if(res.FilingDate !=null && res.FilingDate!='')
                    objOrderItem.Filing_Date__c = Date.valueOf(res.FilingDate);
                strAudit += ' IssueDate :'+res.IssueDate;
                if(res.IssueDate !=null && res.IssueDate!='')
                    objOrderItem.Issue_Date__c = Date.valueOf(res.IssueDate);                
                //Added by Sneha - MARS-778-Add Asset Expiration Field in MaRS system 
                strAudit += 'ExpirationDate :'+res.ExpirationDate;
                objOrderItem.Expiration_Date__c = Date.valueOf(res.ExpirationDate);
                //Added by Sanjay MARS-857 -- Add Adjusted Expiration Date field in Renewals tab
                objOrderItem.Adjusted_Expiration_Date__c = Date.valueOf(res.AdjustedExpirationDate);
                objOrderItem.Patent_No__c = res.PatentNo;
                objOrderItem.Title__c = res.Title;
                objOrderItem.Path__c = res.Path;
                objOrderItem.Term_Name__c = res.TermName;
                //Added by Sneha(MARS-974)
                objOrderItem.Asset_Index__c =res.AssetIndex;
                objOrderItem.Renewal_Instruction__c = res.RenewalInstruction;
                objOrderItem.Entity_Type_Name__c = res.EntityTypeName;
                objOrderItem.Instructed_By__c = res.InstructedBy;
                objOrderItem.Instructed_Date__c = Date.Today();
                //Added by Sneha - MARS-812-Passing Symphony IPM and MaRS extension Package version from Symphony to MaRS
                objOrderItem.Extension_Package_Version__c = res.ExtensionPackage;
                objOrderItem.SymphonyIPM_Version__c = res.SymphonyIPM;
                
                objOrderItem.Fee_Currency__c = res.FeeCurrency;
                objOrderItem.Fee__c = res.Fee;
                objOrderItem.Surcharge__c = res.Surcharge;
                objOrderItem.Claim_Fee__c = res.ClaimFee;
                objOrderItem.Fee_Unit_Rate__c = res.FeeUnitRate;
                
                objOrderItem.Service_Fee_Currency__c = res.ServiceFeeCurrency;
                objOrderItem.Service_Fee__c = res.ServiceFee;
                objOrderItem.Service_Fee_Unit_Rate__c = res.ServiceFeeUnitRate;
                
                objOrderItem.Agent_Fee_Currency__c = res.AgentFeeCurrency;
                objOrderItem.Agent_Fee__c = res.AgentFee;
                objOrderItem.Agent_Fee_Unit_Rate__c = res.AgentFeeUnitRate;
                
                objOrderItem.CE_Markup_Percentage__c = res.MarkupPercentage;
                
                objOrderItem.Billing_Currency__c = res.BillingCurrency;
                objOrderItem.Billing_Amount__c = res.BillingAmount;
                objOrderItem.Billing_Currency_Unit_Rate__c = res.BillingCurrencyUnitRate;
                objOrderItem.Invoice_Type_Name__c= res.InvoiceTypeName;
                
                objOrderItem.Due_Date__c = res.DueDate;
                objOrderItem.Drop_Dead_Date__c = res.DropDeadDate;
                
                objOrderItem.Client_Renewal_Id__c = res.ClientRenewalId;
                
                objOrderItem.Order__c = objOrder.Id;
                objOrderItem.Payment_Status__c = 'Waiting to Invoice';
                INSERT objOrderItem;
                strAudit +=' objOrderItem: '+objOrderItem.id;                             
                //Returning
                Order_Item__c objOrderItemCreated = [SELECT Id, Name FROM Order_Item__c WHERE Id =: objOrderItem.Id];
                ReturnValue.MaRSRenewalID = objOrderItemCreated.Name;
                strAudit +=' MaRSRenewalID : '+ReturnValue.MaRSRenewalID;
                ReturnValue.IsSuccess = true;
                
            	if(objOrder.Total_Asset__c==objOrderItem.Asset_Index__c)
                {
                    List<Order_Item__c> newItemList=[SELECT Id FROM Order_Item__c WHERE Order__c=:objOrder.Id];
                    List<id> orderItemIds=new List<id>();
                    for(Order_Item__c item:newItemList)
                    {
                        orderItemIds.add(item.Id);
                    }
                    OrderItemBatch itemBatch=new OrderItemBatch(orderItemIds);
                    database.executeBatch(itemBatch,1);
                    strAudit+='OrderItemBatch Called||';
                }
            }
            if(CanProceedToUpdate == true && orderItemId!='')
            {
                //Update instruction
                Order_Item__c objOrderItem = new Order_Item__c();
                objOrderItem.id = orderItemId;
               
                objOrderItem.Jurisdiction__c = res.Jurisdiction;
                objOrderItem.Application_No__c = res.ApplicationNo;
                /*MARS-728 - Publication number should be added in Asset Detail view in MaRS*/
                /*Modified by Saranyaa*/
                objOrderItem.Publication_No__c = res.PublicationNo;
                objOrderItem.Docket_No__c = res.DocketNo;
                //Added by Sneha(MARS-974)
                objOrderItem.Asset_Index__c =res.AssetIndex;
                
                //Modified by Sneha - MARS-816- Filing Date should be passed to MaRS and display in Asset Detail view
                //if(res.ApplicationDate !=null && res.ApplicationDate!='')
                    //objOrderItem.Application_Date__c = Date.valueOf(res.ApplicationDate);
                if(res.FilingDate !=null && res.FilingDate!='')
                    objOrderItem.Filing_Date__c = Date.valueOf(res.FilingDate);
                if(res.IssueDate !=null && res.IssueDate!='')
                    objOrderItem.Issue_Date__c = Date.valueOf(res.IssueDate);
                //Added by Sneha - MARS-778-Add Asset Expiration Field in MaRS system
                objOrderItem.Expiration_Date__c = Date.valueOf(res.ExpirationDate);
                //Added by Sanjay MARS-857 -- Add Adjusted Expiration Date field in Renewals tab
                objOrderItem.Adjusted_Expiration_Date__c = Date.valueOf(res.AdjustedExpirationDate);
                objOrderItem.Patent_No__c = res.PatentNo;
                objOrderItem.Title__c = res.Title;
                objOrderItem.Path__c = res.Path;
                objOrderItem.Term_Name__c = res.TermName;
                //Added by Sneha - MARS-812-Passing Symphony IPM and MaRS extension Package version from Symphony to MaRS
                objOrderItem.Extension_Package_Version__c = res.ExtensionPackage;
                objOrderItem.SymphonyIPM_Version__c = res.SymphonyIPM;
                
                objOrderItem.Renewal_Instruction__c = res.RenewalInstruction;
                objOrderItem.Entity_Type_Name__c = res.EntityTypeName;
                objOrderItem.Instructed_By__c = res.InstructedBy;
                objOrderItem.Instructed_Date__c = Date.Today();
                
                objOrderItem.Fee_Currency__c = res.FeeCurrency;
                objOrderItem.Fee__c = res.Fee;
                objOrderItem.Surcharge__c = res.Surcharge;
                objOrderItem.Claim_Fee__c = res.ClaimFee;
                objOrderItem.Fee_Unit_Rate__c = res.FeeUnitRate;
                
                objOrderItem.Service_Fee_Currency__c = res.ServiceFeeCurrency;
                objOrderItem.Service_Fee__c = res.ServiceFee;
                objOrderItem.Service_Fee_Unit_Rate__c = res.ServiceFeeUnitRate;
                
                objOrderItem.Agent_Fee_Currency__c = res.AgentFeeCurrency;
                objOrderItem.Agent_Fee__c = res.AgentFee;
                objOrderItem.Agent_Fee_Unit_Rate__c = res.AgentFeeUnitRate;
                
                objOrderItem.CE_Markup_Percentage__c = res.MarkupPercentage;
                
                objOrderItem.Billing_Currency__c = res.BillingCurrency;
                objOrderItem.Billing_Amount__c = res.BillingAmount;
                objOrderItem.Billing_Currency_Unit_Rate__c = res.BillingCurrencyUnitRate;
                
                objOrderItem.Due_Date__c = res.DueDate;
                objOrderItem.Drop_Dead_Date__c = res.DropDeadDate;
                
                objOrderItem.Client_Renewal_Id__c = res.ClientRenewalId;
                
                //objOrderItem.Order__c = objOrder.Id;
                objOrderItem.Payment_Status__c = 'Waiting to Invoice';
                update objOrderItem;
                ReturnValue.IsSuccess = true;  
                ReturnValue.MaRSRenewalID = orderItemName;            
            }
                
        }
        catch(Exception exp)
        {
            ReturnValue.IsSuccess = false;
            strAudit += exp.getMessage() + '| ' + exp.getStacktraceString();
            ReturnValue.ErrorDescription = 'Error' + ' : ' +exp.getMessage();
        }
        finally
        {
            AuditTrailHelper.UpdateAudit('InstructRenewal', strAudit, '');
        }
        return ReturnValue;
    }
    global class resp
    {
        public boolean IsSuccess{set;get;}
        public string MaRSRenewalID{set;get;}
        public string Status{set;get;}
        public string Message{set;get;}
        public string ErrorCode{set;get;}
        public string ErrorDescription{set;get;}
    }
    public class requestbody
    {
        public string Jurisdiction{set;get;}
        public string ApplicationNo{set;get;} 
        public string PublicationNo{set;get;} 
        public string DocketNo{set;get;} 
        public string PatentNo{set;get;} 
        public string Title{set;get;} 
        public string Path{set;get;} 
        public string TermName{set;get;} 
        public string RenewalInstruction{set;get;} 
        public string EntityTypeName{set;get;} 
        public string InstructedBy{set;get;} 
        public string FeeCurrency{set;get;} 
        public decimal Fee{set;get;} 
        public decimal Surcharge{set;get;} 
        public decimal ClaimFee{set;get;} 
        public decimal FeeUnitRate{set;get;} 
        public string ServiceFeeCurrency{set;get;} 
        public decimal ServiceFee{set;get;} 
        public decimal ServiceFeeUnitRate{set;get;} 
        public string AgentFeeCurrency{set;get;} 
        public decimal AgentFee{set;get;} 
        public decimal AgentFeeUnitRate{set;get;} 
        public decimal MarkupPercentage{set;get;} 
        public string BillingCurrency{set;get;} 
        public decimal BillingAmount{set;get;} 
        public decimal BillingCurrencyUnitRate{set;get;} 
        public string InvoiceTypeName{set;get;} 
        public Date DueDate{set;get;} 
        public Date DropDeadDate{set;get;} 
        public Date ExpirationDate{set;get;}
        public Date AdjustedExpirationDate{set;get;}
        public string ClientOrgId{set;get;} 
        public string ClientOrderId{set;get;} 
        public string ClientRenewalId {set;get;} 
        public string MaRSRenewalID{set;get;} 
        //public string ApplicationDate{set;get;}
        public string FilingDate{set;get;}
        public string IssueDate{set;get;}
        public string ExtensionPackage{set;get;}
        public string SymphonyIPM{set;get;}
        public integer AssetIndex{set;get;}
        public integer TotalAssets{set;get;}
        public string InstructionType{set;get;}
    }
}