force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send Create Request</fullName>
            </value>
            <value>
                <fullName>Send Update Request</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Downloaded Info</fullName>
            </value>
            <value>
                <fullName>Downloaded Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request to be Sent</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Sent to Client</fullName>
            </value>
            <value>
                <fullName>Invoice Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LEDES_Message__c.field-meta.xml
<CustomField>
    <fullName>LEDES_Message__c</fullName>
    <label>LEDES Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LEDES_Status__c.field-meta.xml
<CustomField>
    <fullName>LEDES_Status__c</fullName>
    <label>LEDES Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>NotRequested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoiceStatusRequest.cls
@RestResource(urlMapping = '/renewal/invoice/request/status/*')
global class InvoiceStatusRequest
{
    @HttpPost
    global static resp InvoiceStatus() 
    {
        string status = 'Success';
        string strAuditTrail = '';
        system.debug('renewal/invoice/request');   
        String jsonString = RestContext.request.requestBody.toString();
        system.debug('Req Body: '+jsonString);
        strAuditTrail+='Req Body: '+jsonString+'||' ;
        JSONParser parser = JSON.createParser(jsonString);
        requestbody res = (requestbody)parser.readValueAs(requestbody.class);
        MAP<string,data> mapitems= NEW MAP<string,data>();
        set<string> InvRef=new set<string>();
        resp reslst = NEW resp();
        List<resError> errors = NEW List<resError>();
        list<Invoice__c> finalInvupdate=new list<Invoice__c>();
        string strclintbody='';
        strclintbody=res.ClientRequestHandle;
        system.debug(strclintbody);
        if(strclintbody != '' && strclintbody != null && strclintbody != 'null')
        {
            string ReqID='';
            ReqID=res.RequestID;
            if(ReqID != '' && ReqID != null && ReqID != 'null')
            {
                if(res.Data!=null)
                {
                    for(data itm : res.Data)
                    {
                        InvRef.add(itm.InvoiceRef);
                        if(mapitems.containskey(itm.InvoiceRef))
                        {
                            resError er = NEW resError();
                            reslst.Status = false;
                            er.Code = 'Duplicate_Invoice';
                            er.Description= 'Duplicate Invoice No cant be processed.';
                            errors.add(er);
                            reslst.Error=errors;
                            return reslst;
                        }                            
                        else
                            mapitems.put(itm.InvoiceRef, itm); 
                    }
                }
                system.debug('mapitems'+mapitems);
                list<Invoice__c> ObjInvoice= [SELECT id,Name,Order__r.name,LEDES_Message__c,LEDES_Status__c from Invoice__c WHERE name IN:InvRef];// and Order__r.Client__c=:strclintbody
                
                if(ObjInvoice.size()>0)
                {
                    List<string> assetId=new List<string>();
                    for(Invoice__c inv : ObjInvoice){
                        if(mapitems.containsKey(inv.Name))
                        {
                            data rItem = mapitems.get(inv.Name);
                            system.debug('rItem '+rItem );
                            if(rItem.Status =='1')
                                inv.Invoice_Status__c='To Do';
                            if(rItem.Status =='2')
                                inv .Invoice_Status__c=' In Progress';
                            if(rItem.Status =='3')
                            {
                                inv .Invoice_Status__c='Completed';
                                inv .API_Status__c='Completed';
                                List<Order_Item__c> orderItemId=[Select id,Order__r.name from Order_Item__c where Order__r.name=:inv.Order__r.name];
                                if(orderItemId.size()>0)
                                {
                                    for(Order_Item__c item:orderItemId)
                                    {
                                        assetId.add(item.Id);
                                    }
                                }
                            }
                            if(rItem.Status =='4')
                                inv .Invoice_Status__c='Completed and Posted';
                            if(rItem.Status =='5')
                                inv .Invoice_Status__c='Posting Failed';
                            if(rItem.Status =='6')
                                inv .Invoice_Status__c='Failed';
                            LEDESResponse ledes=rItem.LEDESResponse;
                            if(ledes!=null)
                            {
                                inv.LEDES_Status__c=ledes.LEDESStatus;
                                string warningMessage='';
                                if(ledes.warning.size()>0)
                                {
                                    for(resError ledesWarning :ledes.warning)
                                    {
                                        if(warningMessage == '')
                                            warningMessage = ledesWarning.Code+'-'+ledesWarning.Description;
                                        else
                                            warningMessage += ', '+ledesWarning.Code+'-'+ledesWarning.Description;
                                    }
                                    inv.LEDES_Message__c=warningMessage;
                                }  
                            }
                            inv .Invoice_No__c=rItem.InvoiceNo;
                            finalInvupdate.add(inv);
                            if(inv.Invoice_Status__c== 'Completed')
                            {
                                strAuditTrail +='Invoice Generated for InvoiceRef - '+inv.Name+'||';
                                batchInstructionStatusUpdate CA = NEW batchInstructionStatusUpdate(assetId, 'Invoice Generated');
                				database.executebatch(CA, 1);
                                strAuditTrail+='Invoice Status updated to Symphony';
                            }
                        }
                    }
                }
                try
                {
                    if(finalInvupdate!=null && finalInvupdate.size()>0){                
                        update finalInvupdate;
                        reslst.Status = true;
                    }
                    else{
                        resError er = NEW resError();
                        reslst.Status = false;
                        er.Code = 'NO_DATA_FOUND';
                        er.Description= 'No data found';
                        errors.add(er);
                    }
                }
                catch(exception e)
                {
                    strAuditTrail += ' || Error :'+e.getMessage();
                    status = 'Fail';
                    resError er = NEW resError();
                    er.Code = '-';
                    er.Description = e.getMessage();
                    errors.add(er);            
                }
            }
            else{
                resError er = NEW resError();
                status = 'Fail';
                er.Code = 'REQ_ID_EMPTY';
                er.Description= 'RequestId is null or empty.';
                errors.add(er);
            }
        }
        else{
            resError er = NEW resError();
            status = 'Fail';
            er.Code = 'REQ_HNDL_EMPTY';
            er.Description= 'ClientRequestHandle content is null or empty.';
            errors.add(er);
        }
        reslst.Error=errors;
        AuditTrailHelper.UpdateAudit('InvoiceStatusRequest',strAuditTrail,status);
        return  reslst;  
    }
    /* {
"ClientRequestHandle": "a002E00000k8s3p_a022E00000bMtUd_USD",
"RequestID": "28c30658-28c30658-28c30658-28c30658",
"Status": 2,
"Error": [],
"Data":[
{
"InvoiceRef": "INV-36",
"Status": 3,
"InvoiceNo": "A202008001",
"Error": [],
"Warning":[]
},
{
"InvoiceRef": "INV-37",
"Status": 3,
"InvoiceNo": "A202008002",
"Error": [],
"Warning":[]
}
]
}*/
    global class requestbody
    {
        global string ClientRequestHandle{set;get;}
        global string RequestID{set;get;}
        global integer Status{set;get;}
        global List<data> Data{set;get;}
    }
    global class data
    {
        global string InvoiceRef{set;get;}
        global string InvoiceNo{set;get;}
        global string Status{set;get;}
        global List<error> Error{set;get;}
        global List<warning> warning{set;get;}
        global LEDESResponse LEDESResponse{set;get;}
    }
    global class LEDESResponse
    {
        global string LEDESStatus{set;get;}
        global List<resError> warning{set;get;}
    }
    global class errorbody
    {
        global string Description{set;get;}
    }
    global class error
    {
        global string Description{set;get;}
        global string Staus{set;get;}
    }
    global class warning
    {
        global string Description{set;get;}
    }
    global class resp
    {
        public boolean Status{set;get;}
        Public List<resError> Error{set;get;}
    }
    global class resError
    {
        public string Code{set;get;}
        public string Description{set;get;}
    }
}