force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PTO_fee_paid_status_updated_on__c.field-meta.xml
<CustomField>
    <fullName>PTO_fee_paid_status_updated_on__c</fullName>
    <label>PTO fee paid status updated on</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Close_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Close_Date_To_Pay__c</fullName>
    <label>Suggested Close Date to Pay</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Open_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Open_Date_To_Pay__c</fullName>
    <label>Suggested Payment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchEmailToADURenewalToBePaid.cls
public class batchEmailToADURenewalToBePaid implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful{
    //public OrgWideEmailAddress[] owea{set;get;}
    public datetime yestDayTime {set;get;}
    public List<Profile> pr {set;get;}
    public boolean sendMailtoClient {set;get;}
    public string query {set;get;}
    public List<User> aduusers{set;get;}
    Public map<string,string> ClientHisItems {set;get;}
    Public map<string,string> ClientidName {set;get;}
    Public map<string,string> ClientidEmail {set;get;}
    //--------------------------
    
    public batchEmailToADURenewalToBePaid()
    {   
        system.debug('batchEmailToADURenewalToBePaid');
        sendMailtoClient = false;
        aduusers = NEW List<User>();
        //owea = [select Id from OrgWideEmailAddress ];
        ClientHisItems = NEW map<string,string>();
        ClientidName = NEW map<string,string>();
        ClientidEmail = NEW map<string,string>();
        yestDayTime = datetime.now().addDays(-1);
        pr = [SELECT id,Name from Profile where Name='ADU' Limit 1];
        aduusers = [SELECT id,Name,email from User Where ProfileID=: pr[0].id AND isActive=true];
        query = 'SELECT id,Name,Client__c,Order__r.Client__c,Order__c,Order__r.Client__r.Contact_Email_Id__c,Application_No__c,Patent_No__c,PTO_fee_paid_status_updated_on__c FROM Order_Item__c where Suggested_Open_Date_To_Pay__c <= TODAY AND Suggested_Close_Date_To_Pay__c >=TODAY AND Payment_Status__c = \'Payment Received\' AND (Paid_Status__c=null OR Paid_Status__c=\'\') AND Renewal_Instruction__c=\'Renew\'';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('batchEmailToADURenewalToBePaid start');
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Order_Item__c> scope)
    {
        if(aduusers.size()>0)
        {
            system.debug('batchEmailToADURenewalToBePaid execute');
            List<Order_Item__c> lst = scope;
            string orgURL = string.valueOf(URL.getSalesforceBaseUrl().toExternalForm());
            for(Order_Item__c oi : scope)
            {
                string CientId = oi.Order__r.Client__c;
                String listOIs = ClientHisItems.get(CientId); 
                if(listOIs == null)
                {
                    listOIs = '<a href='+orgURL+'/'+oi.id+'>'+oi.Application_No__c+'</a>';
                    ClientHisItems.put(CientId,listOIs);
                }
                else
                {
                    listOIs += ', <a href='+orgURL+'/'+oi.id+'>'+oi.Application_No__c+'</a>';
                    ClientHisItems.put(CientId,listOIs);
                }
                ClientidName.put(CientId,oi.Client__c);
                ClientidEmail.put(CientId,oi.Order__r.Client__r.Contact_Email_Id__c);
            }
            if(ClientHisItems.size() > 0)
                sendMailtoClient = true;
        }
    } 
    
    public void finish(Database.BatchableContext BC)
    {
        system.debug('batchEmailToADURenewalToBePaid Finish');
        List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();
        String todayDate = Datetime.now().format('yyyy-MM-dd');
        if(sendMailtoClient && ClientHisItems.size()>0)
        {
            
            List<EmailTemplate> emailTemplate = [select Id,Name, Subject, HtmlValue, Body from EmailTemplate where  Name = 'Notify the ADU the renewals to be paid to PTO Reminder' Limit 1];
            if(emailTemplate.size()>0)
            {
                for(User usr : aduusers)
                {
                    string mailTableStart = '<table border="1"><tr><th>Client(s)</th><th>Records</th></tr>';
                    string mailTableRows='';
                    string mailTableEnd='</table>';                    
                    for(string clientid : ClientHisItems.keyset())
                    {
                        mailTableRows+='<tr><td>'+ClientidName.get(clientid)+'</td><td>'+ClientHisItems.get(clientid)+'</td></tr>';
                    }
                    List<String> toAddresses = new List<String>();
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    toAddresses.add(usr.email);
                    //toAddresses.add('harsha@maxval.com');
                    mail.setToAddresses(toAddresses);
                    String subject= emailTemplate[0].Subject;
                    subject= subject.replace('{day}', ' -'+todayDate);
                    String htmlBody = emailTemplate[0].HtmlValue;
                    htmlBody = htmlBody.replace('{ADU}', usr.Name);
                    htmlBody = htmlBody.replace('mailTableStart', mailTableStart);
                    htmlBody = htmlBody.replace('mailTableRows', mailTableRows);
                    htmlBody = htmlBody.replace('mailTableEnd', mailTableEnd);
                    htmlBody =htmlBody.replace('<![CDATA[','');
                    htmlBody = htmlBody.replace(']]>','</div>'); 
                    mail.setSubject(subject);
                    mail.setHtmlBody(htmlBody);
                    /*if ( owea.size() > 0 ) {
                        mail.setOrgWideEmailAddressId(owea.get(0).Id);
                    }*/
                    allMails.add(mail);
                }
                system.debug(allMails.size());
                if(!test.isRunningTest() && allMails.size()>0)
                    Messaging.sendEmail(allMails);
            } 
        }
    }
}