force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jurisdiction__c/Jurisdiction__c.object-meta.xml
<CustomObject>
    <label>Jurisdiction</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jurisdictions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Late Fee (Added in USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Rush_Fee__c.field-meta.xml
<CustomField>
    <fullName>Rush_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rush Fee (Added in USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Agent_Fee__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fee__c</fullName>
    <label>Agent Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Agent_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fee_Currency__c</fullName>
    <label>Agent Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Agent_Fee_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fee_Unit_Rate_When_Pay__c</fullName>
    <label>Agent Fee Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/CE_Markup_Percentage__c.field-meta.xml
<CustomField>
    <fullName>CE_Markup_Percentage__c</fullName>
    <label>CE Markup Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Claim_Fee__c.field-meta.xml
<CustomField>
    <fullName>Claim_Fee__c</fullName>
    <label>Claim Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Docket_No__c.field-meta.xml
<CustomField>
    <fullName>Docket_No__c</fullName>
    <label>Docket No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Drop_Dead_Date__c.field-meta.xml
<CustomField>
    <fullName>Drop_Dead_Date__c</fullName>
    <label>Drop Dead Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PTO Fee (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Fee_Currency__c</fullName>
    <label>Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Fee_Unit_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fee Unit Rate (When Instruct)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Fee_Unit_Rate_When_Pay__c</fullName>
    <label>Fee Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Instructed_By__c.field-meta.xml
<CustomField>
    <fullName>Instructed_By__c</fullName>
    <label>Instructed By</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Record_Id__c</fullName>
    <label>Renewal Record Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Rush_Fee__c.field-meta.xml
<CustomField>
    <fullName>Rush_Fee__c</fullName>
    <label>Rush Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Currency__c</fullName>
    <label>Service Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Unit_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Service Fee Unit Rate (When Instruct)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Unit_Rate_When_Pay__c</fullName>
    <label>Service Fee Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Close_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Close_Date_To_Pay__c</fullName>
    <label>Suggested Close Date to Pay</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Open_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Open_Date_To_Pay__c</fullName>
    <label>Suggested Payment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Term_Name__c.field-meta.xml
<CustomField>
    <fullName>Term_Name__c</fullName>
    <label>Term</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Ref. No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency_All.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AQD</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <masterLabel>Currency All</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DataLoaderForOrder.cls
public class DataLoaderForOrder
{
    public DataLoaderForOrder()
    {
    }
    public static boolean CleanupOrders()
    {
        List<Payment__c> objPayments =  [SELECT Id FROM Payment__c];
        DELETE objPayments;
        
        List<Order_Item__c> objOrderItems = [SELECT Id FROM Order_Item__c];
        DELETE objOrderItems;
        
        List<Order__c> objOrders = [SELECT Id FROM Order__c];
        DELETE objOrders;
        
        return true;
    }
    public static Order__c CreateOrder(string BillingCurrency, Id ClientId, decimal LateFee, string OrderName, decimal OrderAmountClient, string PaymentStatus, decimal RushFee)
    {
        Order__c objOrder = new Order__c();
        //objOrder.Billing_Currency__c = BillingCurrency;
        objOrder.Client__c = ClientId;
        objOrder.Late_Fee__c = LateFee;
        //objOrder.Name = OrderName;
        //objOrder.Order_Amount_Client__c = OrderAmountClient;
        objOrder.Order_Date__c = DateTime.Now();
        objOrder.Payment_Status__c = PaymentStatus;
        objOrder.Rush_Fee__c = RushFee;
        INSERT objOrder;
        return objOrder;
    }
    


    public static Order_Item__c CreateOrderItem (Id OrderId, string Jurisdiction, string ApplicationNo, string DocketNo, string PatentNo, string DueDate, string DropDeadDate, string PaymentStatus, string RenewalInstruction, string RenewalRecordId, string SuggestedOpenDateToPay,string SuggestedCloseDateToPay, string TermName, string Title, string InstructedBy,string FeeCurrency, decimal Fee, decimal ClaimFee, decimal Surcharge, decimal FeeUnitRateWhenInstruct, decimal FeeUnitRateWhenPay, string ServiceFeeCurrency, decimal ServiceFee, decimal ServiceFeeUnitRateWhenInstruct , decimal ServiceFeeUnitRateWhenPay, string AgentFeeCurrency, decimal AgentFee, decimal AgentFeeUnitRateWhenInstruct, decimal AgentFeeUnitRateWhenPay, decimal CEMarkupPercentage)
    {
        Order_Item__c objOrderItem = new Order_Item__c();
        objOrderItem.Order__c =OrderId;
        
        objOrderItem.Agent_Fee_Currency__c = AgentFeeCurrency;
        //objOrderItem.Agent_Fee_Unit_Rate_When_Instruct__c = AgentFeeUnitRateWhenInstruct;
        objOrderItem.Agent_Fee_Unit_Rate_When_Pay__c = AgentFeeUnitRateWhenPay;
        objOrderItem.Agent_Fee__c = AgentFee;
        
        objOrderItem.Application_No__c = ApplicationNo;
        objOrderItem.CE_Markup_Percentage__c = CEMarkupPercentage;
        objOrderItem.Claim_Fee__c = ClaimFee;
        objOrderItem.Docket_No__c = DocketNo;
        objOrderItem.Drop_Dead_Date__c = Date.valueOf(DropDeadDate);
        objOrderItem.Due_Date__c = Date.valueOf(DueDate);
        
        objOrderItem.Fee_Currency__c = FeeCurrency;
        objOrderItem.Fee_Unit_Rate__c = FeeUnitRateWhenInstruct;
        objOrderItem.Fee_Unit_Rate_When_Pay__c = FeeUnitRateWhenPay;
        
        objOrderItem.Fee__c = Fee;
        objOrderItem.Instructed_By__c = InstructedBy;
        objOrderItem.Jurisdiction__c = Jurisdiction;
        objOrderItem.Patent_No__c = PatentNo;
        objOrderItem.Payment_Status__c = PaymentStatus;
        objOrderItem.Renewal_Instruction__c = RenewalInstruction;
        objOrderItem.Renewal_Record_Id__c = RenewalRecordId;
        
        objOrderItem.Service_Fee_Currency__c = ServiceFeeCurrency;
        objOrderItem.Service_Fee_Unit_Rate__c = ServiceFeeUnitRateWhenInstruct;
        objOrderItem.Service_Fee_Unit_Rate_When_Pay__c = ServiceFeeUnitRateWhenPay;
        objOrderItem.Service_Fee__c = ServiceFee;
        
        objOrderItem.Suggested_Close_Date_To_Pay__c = Date.valueOf(SuggestedCloseDateToPay);
        objOrderItem.Suggested_Open_Date_To_Pay__c = Date.valueOf(SuggestedOpenDateToPay);
        objOrderItem.Surcharge__c = Surcharge;
        objOrderItem.Term_Name__c = TermName;
        objOrderItem.Title__c = Title;
        INSERT objOrderItem;
        return objOrderItem;
    }
    
    public static void SetupData()
    {
        CleanupOrders();
        Clients__c objClient = [SELECT Id FROM Clients__c WHERE Name='APL' LIMIT 1];
        Order__c objOrder = DataLoaderForOrder.CreateOrder('USD', objClient.Id, 0, 'ORD-1', 1310, 'To be Invoiced', 0);
        DataLoaderForOrder.CreateOrderItem(objOrder.Id, 'US','APP-US-001', 'DKT-US-001', 'PAT-US-001', '2020-06-30', '2020-12-30', 'Waiting to Invoice', 'Renew', '1', '2020-6-20', '2020-6-29', 'Year 3.5', 'Title-US-001', 'Sanjay Ram', 'USD', 1300, 0, 0, 1, 1, 'USD', 10, 1, 1,'USD', 0, 1, 1, 4);
    }
}
//Clients__c objClient = [SELECT Id FROM Clients__c WHERE Name='APL' LIMIT 1];
//Order__c objOrder = DataLoaderForOrder.CreateOrder('USD', objClient.Id, 0, 'ORD-4', 2650, 'To be Invoiced', 0);
//DataLoaderForOrder.CreateOrderItem(objOrder.Id, 'USD', 1, 1, 0, 'US13/123,456', 4, 0, 'DKT-US-004', '2020-12-30', '2020-06-30', 'USD', 1, 1, 1300, 'Sanjay Ram', 'US', 'US-SAM-001', 'Waiting to Invoice', 'Renew', '123', 'USD', 1, 1, 10, '2020-6-29', '2020-6-20', 0, 'Year 3.5', 'US-001-Title');