force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency_Unit_Rate__c</fullName>
    <label>Billing Currency Unit Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/CE_Markup_Percentage__c.field-meta.xml
<CustomField>
    <fullName>CE_Markup_Percentage__c</fullName>
    <label>CE Markup Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Claim_Fee__c.field-meta.xml
<CustomField>
    <fullName>Claim_Fee__c</fullName>
    <label>Claim Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PTO Fee (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Amount_When_Instruct__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount_When_Instruct__c</fullName>
    <formula>if 
(
(TEXT( Fee_Currency__c)== TEXT( Billing_Currency__c ))
,(Fee__c +  Claim_Fee__c +  Surcharge__c)
, (((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate__c)/Billing_Currency_Unit_Rate__c)
+ ((((Fee__c +  Claim_Fee__c +  Surcharge__c)/Fee_Unit_Rate__c)/Billing_Currency_Unit_Rate__c) *  (CE_Markup_Percentage__c /100))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTO Fee  (Invoiced)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Fee_Currency__c</fullName>
    <label>Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Fee_Unit_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fee Unit Rate (When Instruct)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency_All.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AQD</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <masterLabel>Currency All</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateInvoiceWithVarianceControllerTest.cls
@isTest
public class CreateInvoiceWithVarianceControllerTest {
    
    public static testmethod void Method1()
    {
        Clients__c client = new Clients__c();
        client.Name = 'Maxval@123';
        insert client;
        
        List<Order__c> ordList = new List<Order__c>();
        Order__c ord = new Order__c();
        ord.Client__c = client.Id;
        ordList.add(ord);
        insert ordList;
        
        List<Order_Item__c> oiList = new List<Order_Item__c>();
        Order_Item__c oi = new Order_Item__c();
        oi.Order__c = ord.Id;
        oi.Application_No__c = 'US1233234';
        oi.Patent_No__c = 'US232434';
        oi.Fee_Currency__c = 'USD';
        oi.Billing_Currency__c = 'USD';
        oi.Fee__c = 100;
        oi.Claim_Fee__c = 10;
        oi.Surcharge__c = 10;
        oi.Fee_Unit_Rate__c = 2;
        oi.Billing_Currency_Unit_Rate__c = 2;
        oi.CE_Markup_Percentage__c = 20;
        oiList.add(oi);
        insert oiList;
        system.debug('Fee'+ oiList[0].Fee_Amount_When_Instruct__c);
        
        Test.startTest();
        
        PageReference pageRef = Page.vfCreateInvoiceWithVariance;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(ordList[0].Id));
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(ordList);
        stdSetController.setSelected(ordList);
        CreateInvoiceWithVarianceController ext = new CreateInvoiceWithVarianceController(stdSetController);
        system.debug(ordList[0].id);
        ext.GetListViewURL();
        ext.GetSelectedOrderIds();
        ext.getAssets();
        
        Test.stopTest();
    }
}