force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/EndPoint_URL__c.field-meta.xml
<CustomField>
    <fullName>EndPoint_URL__c</fullName>
    <label>EndPoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/Renewal_Chat__c.object-meta.xml
<CustomObject>
    <label>Renewal Chat</label>
    <nameField>
        <displayFormat>RC-{0000000}</displayFormat>
        <label>Renewal Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Renewal_Chat__c/fields/Chat_Text__c.field-meta.xml
<CustomField>
    <fullName>Chat_Text__c</fullName>
    <label>Chat Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/fields/From_Symphony__c.field-meta.xml
<CustomField>
    <fullName>From_Symphony__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Symphony</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/fields/From_UserId__c.field-meta.xml
<CustomField>
    <fullName>From_UserId__c</fullName>
    <label>From UserId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/fields/MaRS_Reference_ID__c.field-meta.xml
<CustomField>
    <fullName>MaRS_Reference_ID__c</fullName>
    <label>MaRS Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RenewalChatController.cls
public with sharing class RenewalChatController
{
    @auraEnabled
    public static dataBody getAllMessages(String recID)
    {
        system.debug(recID);
        dataBody db = NEW dataBody();
        string cbURL = '';
        string MaRSRefID = '';
        List<Order_Item__c> oi = [select id,name,Order__r.Client__c,Order__r.Client__r.Endpoint_URL__c from Order_Item__c where id=: recID];
        List<Renewal_Chat__c> chats = NEW List<Renewal_Chat__c>();
        if(oi.size()> 0)
            chats = [SELECT ID,From__c,Chat_Text__c,CreatedDate,From_Symphony__c FROM Renewal_Chat__c WHERE MaRS_Reference_ID__c=: oi[0].Name ORDER BY CreatedDate DESC];
        if(chats.size()>0)
        {
            db.renewalChats = chats;            
            system.debug('Final:'+db.cURL+' MRefID:'+db.MRefID+' renewalChats:'+db.renewalChats.size());
        }
        db.MRefID = oi[0].Name;
        db.cURL = oi[0].Order__r.Client__r.Endpoint_URL__c;
        db.cID = oi[0].Order__r.Client__c;
        return db;
    }
    @auraEnabled
    public static string SendMessages(String MaRSReferenceID, String ChatMessage, String ClientID, string ClientURL)
    {
        string strAuditTrail = '';
        string Status = 'Success';
        try
        {
            strAuditTrail += 'RenewalChatController - SendMessages: For- '+MaRSReferenceID+' Msg-'+ChatMessage; 
            Renewal_Chat__c rc = New Renewal_Chat__c();
            rc.From__c = UserInfo.getName();
            rc.From_UserId__c = UserInfo.getUserId();
            rc.MaRS_Reference_ID__c = MaRSReferenceID;
            rc.Chat_Text__c = ChatMessage; 
            insert rc;
            
            callAPISendMessages(MaRSReferenceID, ChatMessage, ClientURL, ClientID, rc.From_UserId__c, rc.From__c);
        }
        catch(exception e)
        {
            strAuditTrail += e.getmessage();
            Status = 'Fail';
        }
        AuditTrailHelper.UpdateAudit('RenewalChatController', strAuditTrail, Status);
        return Status;
    } 
    @future(callout=true)
    public static void callAPISendMessages(String MaRSReferenceID, String ChatMessage, string ClientURL,String ClientID, string FromUserId, string FromName)
    {
        string strAuditTrail = '';
        string Status = 'Success';
        try
        {
            requestBody r = NEW requestBody();
            r.MaRSReferenceID = MaRSReferenceID;
            r.FromUserID = FromUserId;
            r.FromName = FromName;
            r.ChatMessage = ChatMessage;
            string jsonbody = JSON.serialize(r);
            string AccessToken = SymphonyAuthenticaionHelper.SymphonyAuthenticaionHelper(ClientID);
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setMethod('POST');
            req.setEndpoint(ClientURL+'/services/apexrest/renewals/chat/');
            req.setHeader('Authorization', 'Bearer ' + AccessToken);
            req.setHeader('Content-Type','application/json;charset=UTF-8');
            req.setHeader('Content-Length', string.valueOf(jsonbody.length()));            
            req.setBody(jsonbody);
            HttpResponse res = http.send(req);  
            system.debug('Response status code :'+res.getStatusCode() +' |Status :'+res.getStatus() +' |Body '+res.getBody());          
            strAuditTrail += ' |Res Status: '+res.getStatus()+' |Status Code: '+res.getStatusCode()+' |Body: '+res.getBody();
            String jsonString = res.getBody();
            system.debug('Req Body: '+jsonString );
            JSONParser parser = JSON.createParser(jsonString);
            responsebody resb = (responsebody)parser.readValueAs(responsebody.class);
            if(resb.Status)
            {
                Status = 'Success';
            }
            else
            {
                error e = resb.error;
                Status = 'Fail - '+e.Description;
            }
        }
        catch(exception e)
        {
            strAuditTrail += e.getmessage();
            Status = 'Fail';
            system.debug(e.getmessage());
            AuditTrailHelper.UpdateAudit('RenewalChatController', strAuditTrail, Status);
        }
        AuditTrailHelper.UpdateAudit('RenewalChatController', strAuditTrail, Status);
    }
    public class dataBody
    {
        @auraEnabled
        public List<Renewal_Chat__c> renewalChats{set;get;}
        @auraEnabled
        public string cURL{set;get;}
        @auraEnabled
        public string MRefID{set;get;}
        @auraEnabled
        public string cID{set;get;}
    }
    public class requestBody
    {
        public string MaRSReferenceID{set;get;}
        public string FromUserID{set;get;}
        public string FromName{set;get;}
        public string ChatMessage{set;get;}
    }
    public class responsebody
    {
        public boolean Status{set;get;}
        public error Error{set;get;}
    }
    public class error
    {
        public string Description{set;get;}
        public string Code{set;get;}
    }
}