force-app/main/default/objects/API_Auth_Detail__c/API_Auth_Detail__c.object-meta.xml
<CustomObject>
    <label>API Auth Detail</label>
    <nameField>
        <displayFormat>API-{000}</displayFormat>
        <label>API Auth Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Auth Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Auth_Detail__c/fields/Type_Of_Credential__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Credential__c</fullName>
    <label>Type Of Credential</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QB Credential</fullName>
                <default>true</default>
                <label>QB Credential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/API_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>API_Request_ID__c</fullName>
    <label>API Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send Create Request</fullName>
            </value>
            <value>
                <fullName>Send Update Request</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Downloaded Info</fullName>
            </value>
            <value>
                <fullName>Downloaded Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/batchRenewalInvoiceUpdate.cls
//renewal/invoice/update
public class batchRenewalInvoiceUpdate implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful
{
    public string query{set;get;}
    public string AccessToken{set;get;}
    public API_Credentials__c credentials{set;get;}
    public List<string> lstCIds{set;get;}
    public string ApiHandleRefId{set;get;}
    public batchRenewalInvoiceUpdate(List<id> clientids)
    {
        SET<id> ids =NEW SET<id>(clientids);
        AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        lstCIds = NEW List<id>(ids);
        system.debug(lstCIds);
        credentials = [SELECT Id,Name,URL__c,Username__c,Password__c FROM API_Credentials__c WHERE Name=: 'Renewal Invoice Update'];
        ApiHandleRefId =[SELECT Name FROM API_Auth_Detail__c  WHERE Type_Of_Credential__c ='QB Credential' LIMIT 1].Name;
        query = 'select id from clients__c where id in: lstCIds';
    }
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Clients__c> scope)
    {
        boolean saveAudit = false;
        string strAuditTrail = '';
        try
        {
            strAuditTrail += 'Renewal Invoice Update : ';
            List<Clients__c> clients = scope;
            List<Invoice__c> clientInvoices = [Select id,Name,Order__r.Client__c,API_Request_ID__c,API_Status__c from Invoice__c where API_Status__c='Send Update Request' AND Order__r.Client__c=:clients[0].id];
            //List<Order_Item__c> ois = NEW List<Order_Item__c>();
            //String AccessToken = MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
            Map<String,List<Invoice__c>> ClientInvoiceMap = new Map<String,List<Invoice__c>>();
            for(Invoice__c ci : clientInvoices)
            {
                List<Invoice__c> temp = ClientInvoiceMap.get(ci.Order__r.Client__c);
                if(temp != null)
                {
                    temp.add(ci);
                }
                else
                {
                    ClientInvoiceMap.put(ci.Order__r.Client__c, new List<Invoice__c>{ci});
                }
            }
            for(string keyOI : ClientInvoiceMap.keyset())
            {
                ReqData woi = NEW ReqData();               
                List<objectitem> Items = NEW List<objectitem>();                
                for(Invoice__c ci : ClientInvoiceMap.get(keyOI))
                {
                    objectitem oitem = NEW objectitem();
                    oitem.InvoiceRef = ci.Name;
                    Items.add(oitem);
                }
                woi.ClientRequestHandle = keyOI;
                woi.ApiHandleRef = ApiHandleRefId;
                woi.Items = Items;
                string jsonbody = JSON.serialize(woi);
                //jsonbody ='{"ClientRequestHandle":"8bd2ee6c-ab07-4793-8078-56e338614025","Items":[{"InvoiceRef":"63463"},{"InvoiceRef":"34666"}]}';
                
                system.debug('Request Body :'+jsonbody);
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setMethod('POST');
                req.setEndpoint(credentials.URL__c);
                req.setHeader('Authorization', 'Bearer ' + AccessToken);
                req.setHeader('Content-Type','application/json;charset=UTF-8');
                req.setHeader('Content-Length', string.valueOf(jsonbody.length()));            
                req.setBody(jsonbody);
                HttpResponse res = http.send(req);  
                system.debug('Response status code :'+res.getStatusCode() +' |Status :'+res.getStatus() +' |Body '+res.getBody());          
                strAuditTrail += res.getBody();
                List<Invoice__c> invoices= NEW List<Invoice__c>();
                if(res.getStatusCode() == 200 || res.getStatusCode() == 201)
                {
                    string strres = res.getBody();
                    responsebody resb = (responsebody)JSON.deserialize(strres, responsebody.Class);
                    for(Invoice__c ci : ClientInvoiceMap.get(keyOI))
                    {
                        responseBodyData rd = resb.Data;
                        ci.API_Request_ID__c = rd.RequestID;
                        if(ci.API_Request_ID__c != null && ci.API_Request_ID__c!='')
                        {
                            ci.API_Status__c = 'Requested';
                        }
                        invoices.add(ci);
                    }
                }            
                update invoices;
            }
        }
        catch(Exception e)
        {
            strAuditTrail += ' || Error :'+e.getMessage();
        }
        finally
        {
            system.debug(strAuditTrail);
            AuditTrailHelper.UpdateAudit('batchRenewalInvoiceUpdate',strAuditTrail,'Success');
        }
    }
    public void finish(Database.BatchableContext BC)
    {
        
    }
    public class ReqData
    {
        public string ClientRequestHandle{get;set;}
        public string ApiHandleRef{get;set;}
        public List<objectitem> Items{get;set;}
    }
    public class objectitem
    {
        public string InvoiceRef{get;set;}
    }
    public class responseBody
    {
        public integer Status{ get; set; }
        public responseBodyData Data{ get; set; }
        public List<responseBodyError> Error{ get; set; }
        public string Warning{ get; set; }

    }
    public class responseBodyData
    {
        public string RequestID{ get; set; }
        public string DuplicateInvoiceReference{ get; set; }
    }
    public class responseBodyError
    {
        public string Code{ get; set; }
        public string Description{ get; set; }
    }    
}