force-app/main/default/objects/API_Auth_Detail__c/API_Auth_Detail__c.object-meta.xml
<CustomObject>
    <label>API Auth Detail</label>
    <nameField>
        <displayFormat>API-{000}</displayFormat>
        <label>API Auth Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Auth Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Auth_Detail__c/fields/Type_Of_Credential__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Credential__c</fullName>
    <label>Type Of Credential</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QB Credential</fullName>
                <default>true</default>
                <label>QB Credential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/QB_Customer__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Customer</label>
    <referenceTo>QB_Customer__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>ToBeRequested</fullName>
            </value>
            <value>
                <fullName>NotRequested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Application_No__c.field-meta.xml
<CustomField>
    <fullName>Application_No__c</fullName>
    <label>Application No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Memo</label>
    <referenceTo>Credit_Memo__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/CreditMemo_Amount__c.field-meta.xml
<CustomField>
    <fullName>CreditMemo_Amount__c</fullName>
    <label>CreditMemo Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/CreditMemo_Comments__c.field-meta.xml
<CustomField>
    <fullName>CreditMemo_Comments__c</fullName>
    <label>CreditMemo Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Patent_No__c.field-meta.xml
<CustomField>
    <fullName>Patent_No__c</fullName>
    <label>Patent No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QB_Account__c/QB_Account__c.object-meta.xml
<CustomObject>
    <label>QB Account</label>
    <nameField>
        <label>QB Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>QB Accounts</relationshipLabel>
    <relationshipName>QB_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Account__c/fields/QB_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Account_Id__c</fullName>
    <label>QB Account Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Customer__c/QB_Customer__c.object-meta.xml
<CustomObject>
    <label>QB Customer</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Customer__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>QB Customers</relationshipLabel>
    <relationshipName>QB_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/QB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetCreditMemoDetailsTest.cls
@isTest
public class GetCreditMemoDetailsTest {
    @isTest 
    public static void TestMethod1()
    {       
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        API_Auth_Detail__c apiAuth = new API_Auth_Detail__c();
        apiAuth.Type_Of_Credential__c ='QB Credential';
        insert apiAuth;
        
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
        
        QB_Account__c acc = new QB_Account__c();
        acc.QB_Account_Id__c = '1';
        acc.Client__c = Cl.Id;
        insert acc;
        
        QB_Customer__c cus = new QB_Customer__c();
        cus.QB_Customer_Id__c = '1';
        cus.Client__c = Cl.Id;
        insert cus;
        
        Credit_Memo__c  cmRec  = new Credit_Memo__c();
        cmRec.API_Status__c = 'Requested';
        insert cmRec;
        
        Test.startTest();
        Credit_Memo__c cm =[Select name from Credit_Memo__c limit 1];
        String jsonMsg = JSON.serialize(cm);
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
        req.requestURI = '/renewal/creditmemo/'+ cm.Name +'/details';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(jsonMsg); // Add JSON Message as a POST
        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
        Test.setMock(HttpCalloutMock.class, new GetCreditMemoDetailsMockErrorResponse());
        GetCreditMemoDetails.doget();
        Test.stopTest();
    }
    @isTest 
    public static void TestMethod2()
    {       
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        API_Auth_Detail__c apiAuth = new API_Auth_Detail__c();
        apiAuth.Type_Of_Credential__c ='QB Credential';
        insert apiAuth;
        
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
        
        QB_Account__c acc = new QB_Account__c();
        acc.QB_Account_Id__c = '1';
        acc.Client__c = Cl.Id;
        insert acc;
        
        QB_Customer__c cus = new QB_Customer__c();
        cus.QB_Customer_Id__c = '1';
        cus.Client__c = Cl.Id;
        insert cus;
        
        Test.startTest();
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
        req.requestURI = '/renewal/creditmemo/'+ 'CM-00001' +'/details';
        req.httpMethod = 'GET';
        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
        Test.setMock(HttpCalloutMock.class, new GetCreditMemoDetailsMockErrorResponse());
        GetCreditMemoDetails.doget();
        Test.stopTest();
    }
     @isTest 
    public static void TestMethod3()
    {       
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        API_Auth_Detail__c apiAuth = new API_Auth_Detail__c();
        apiAuth.Type_Of_Credential__c ='QB Credential';
        insert apiAuth;
        
        Test.startTest();
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
        req.requestURI = '/renewal/creditmemo/'+ 'CM-00001';
        req.httpMethod = 'GET';
        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
        Test.setMock(HttpCalloutMock.class, new GetCreditMemoDetailsMockErrorResponse());
        GetCreditMemoDetails.doget();
        Test.stopTest();
    }
    @isTest 
    public static void TestMethod4()
    {       
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        API_Auth_Detail__c apiAuth = new API_Auth_Detail__c();
        apiAuth.Type_Of_Credential__c ='QB Credential';
        insert apiAuth;
        
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
        
        QB_Account__c acc = new QB_Account__c();
        acc.QB_Account_Id__c = '1';
        acc.Client__c = Cl.Id;
        insert acc;
        
        QB_Customer__c cus = new QB_Customer__c();
        cus.QB_Customer_Id__c = '1';
        cus.Client__c = Cl.Id;
        insert cus;
        
        Order__c order = new Order__c();
        order.Client__c = Cl.Id;
        insert order;
        
        Order_Item__c oi1 = new Order_Item__c();
        oi1.Order__c = order.Id;
        oi1.Patent_No__c = 'US12345';
        oi1.Application_No__c = 'US1234567';
        oi1.Payment_Status__c = 'Asset Renewed';
        oi1.CreditMemo_Amount__c = 1800.00;
        oi1.CreditMemo_Comments__c = 'fluctuation';
        insert oi1;
        
        Credit_Memo__c  cmRec  = new Credit_Memo__c();
        cmRec.API_Status__c = 'Requested';
        insert cmRec;
        
        oi1.Credit_Memo__c = cmRec.Id;
        update oi1;
        
        Test.startTest();
        Credit_Memo__c cm =[Select name from Credit_Memo__c limit 1];
        String jsonMsg = JSON.serialize(cm);
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
        req.requestURI = '/renewal/creditmemo/'+ cm.Name +'/details';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(jsonMsg); // Add JSON Message as a POST
        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
        Test.setMock(HttpCalloutMock.class, new GetCreditMemoDetailsMockResponse());
        GetCreditMemoDetails.doget();
        Test.stopTest();
    }
    
}