force-app/main/default/objects/API_Auth_Detail__c/API_Auth_Detail__c.object-meta.xml
<CustomObject>
    <label>API Auth Detail</label>
    <nameField>
        <displayFormat>API-{000}</displayFormat>
        <label>API Auth Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Auth Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Auth_Detail__c/fields/Type_Of_Credential__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Credential__c</fullName>
    <label>Type Of Credential</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QB Credential</fullName>
                <default>true</default>
                <label>QB Credential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send Create Request</fullName>
            </value>
            <value>
                <fullName>Send Update Request</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Downloaded Info</fullName>
            </value>
            <value>
                <fullName>Downloaded Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Type_Configuration__c/Invoice_Type_Configuration__c.object-meta.xml
<CustomObject>
    <label>Invoice Type Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Type Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Type_Configuration__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>Invoice Type Configurations</relationshipLabel>
    <relationshipName>Invoice_Type_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Type_Configuration__c/fields/Contact_Persons__c.field-meta.xml
<CustomField>
    <fullName>Contact_Persons__c</fullName>
    <label>Contact Persons</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Type_Configuration__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Validation_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Request_Status__c</fullName>
    <label>Validation Request Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Ref. No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTO_Credentials__c/PTO_Credentials__c.object-meta.xml
<CustomObject>
    <label>PTO Credentials</label>
    <nameField>
        <displayFormat>CRE-{00000}</displayFormat>
        <label>PTO Credentials No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchValidateWithPTOTest.cls
@isTest public class batchValidateWithPTOTest {
    @isTest public static void TestMethod1()
    {
            PTO_Credentials__c PTO =new PTO_Credentials__c();
            PTO.Country_Code__c ='US';
            //PTO.Name = 'US';
            Insert PTO;
            
            API_Auth_Detail__c API =new API_Auth_Detail__c();
            API.Type_Of_Credential__c ='QB Credential';
            Insert API;
              
            API_Credentials__c ObjAPI1 = new API_Credentials__c();
            ObjAPI1.Password__c ='Test@1234';
            ObjAPI1.Username__c ='MaxvalAPI';
            ObjAPI1.Name = 'Renewal Invoice Update';
            ObjAPI1.URL__c ='https://login.salesforce.com/services/oauth2/token';
            insert ObjAPI1;
            
            API_Credentials__c ObjAPI11 = new API_Credentials__c();
            ObjAPI11.Password__c ='Test@1234';
            ObjAPI11.Username__c ='MaxvalAPI';
            ObjAPI11.Name = 'MaxvalAPI';
            ObjAPI11.URL__c ='https://login.salesforce.com/services/oauth2/token';
            insert ObjAPI11;
            
            API_Credentials__c ObjAPI2 = new API_Credentials__c();
            ObjAPI2.Password__c ='Test@1234';
            ObjAPI2.Username__c ='MaxvalAPI';
            ObjAPI2.Name = 'PTO Payment Validate';
            ObjAPI2.URL__c ='https://login.salesforce.com/services/oauth2/token';
            insert ObjAPI2;
            
            List<Id > ClList =new List<Id>();
            Clients__c  Cl =new Clients__c ();
            Cl.Client_Name__c = 'Test Status';
            Insert Cl;
            ClList.add(Cl.id);
            Invoice_Type_Configuration__c ITC =new Invoice_Type_Configuration__c();
            ITC.Contact_Persons__c = 'juveria.b@maxval.com';
            ITC.Client__c =Cl.id;
            insert ITC;
            List<Id> ListOrd =new List<Id>();
            Set<Id > OrdSet =new Set<Id>();
            
            Order__c  Ord =new Order__c ();
            Ord.Client__c =Cl.id;
            Insert Ord;
            OrdSet.add(Ord.id);
            ListOrd.add(Ord.id);
            
            Payment__c PY =new Payment__c ();
            PY.Payment_Amount__c =5800.0;
            Insert PY;
            List<Order_Item__c> listOI = NEW List<Order_Item__c>();
            Order_Item__c OI =new Order_Item__c();
            OI.Order__c =Ord.Id;
            OI.Payment__c =PY.id;
            OI.Payment_Status__c ='Payment Received';
            Insert OI;
            List<String> OIList =new List<String>();
            OIList.add(OI.id);
            
            Invoice__c  Inv =new Invoice__c ();
            Inv.Invoice_Amount__c = 2000.0;
            Inv.API_Status__c =	'Send Update Request';
            Inv.Order__c = Ord.id;
            Inv.Invoice_Currency__c ='USD';
            insert Inv;
            
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            //SymphonyAuthenticaionHelper sA =new SymphonyAuthenticaionHelper();
            MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
            batchValidateWithPTO   ObjBatch =new batchValidateWithPTO(OIList);
            Database.executeBatch(ObjBatch, 1);
           
            Test.stopTest();
    }
        @isTest public static void TestMethod2()
        {
                PTO_Credentials__c PTO =new PTO_Credentials__c();
                PTO.Country_Code__c ='US';
                Insert PTO;
                API_Credentials__c ObjApi = new API_Credentials__c();
                ObjApi.Password__c ='Test@1234';
                ObjApi.Username__c ='MaxvalAPI';
                ObjApi.Name = 'MaxvalAPI';
                ObjApi.URL__c ='https://login.salesforce.com/services/oauth2/token';
                insert ObjApi;
                API_Credentials__c ObjAPI2 = new API_Credentials__c();
                ObjAPI2.Password__c ='Test@1234';
                ObjAPI2.Username__c ='MaxvalAPI';
                ObjAPI2.Name = 'PTO Payment Validate';
                ObjAPI2.URL__c ='https://login.salesforce.com/services/oauth2/token';
                insert ObjAPI2;
                
                List<Id > ClList =new List<Id>();
                Clients__c  Cl =new Clients__c ();
                Cl.Client_Name__c = 'Sample';
                Insert Cl;
                ClList.add(Cl.id);
                Invoice_Type_Configuration__c ITC =new Invoice_Type_Configuration__c();
                ITC.Contact_Persons__c = 'sneha.b@maxval.com';
                ITC.Client__c =Cl.id;
                insert ITC;
                List<Id> ListOrd =new List<Id>();
                Set<Id > OrdSet =new Set<Id>();
                
                Order__c  Ord =new Order__c ();
                Ord.Client__c =Cl.id;
                Ord.Validation_Request_Status__c='';
                Ord.Order_Status__c='Order Placed';
                Insert Ord;
                OrdSet.add(Ord.id);
                ListOrd.add(Ord.id);
                
                Payment__c PY =new Payment__c ();
                PY.Payment_Amount__c =5800.0;
                Insert PY;
                List<Order_Item__c> listOI = NEW List<Order_Item__c>();
                Order_Item__c OI =new Order_Item__c();
                OI.Order__c =Ord.Id;
                OI.Payment__c =PY.id;
                OI.Payment_Status__c ='Payment Received';
                Insert OI;
                List<String> OIList =new List<String>();
                OIList.add(OI.id);
                
                Test.startTest();
                Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
                MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
                batchValidateWithPTO ObjBatch =new batchValidateWithPTO();
                Database.executeBatch(ObjBatch, 1);
               
                Test.stopTest();
        }
         @isTest public static void TestMethod3()
        {
                PTO_Credentials__c PTO =new PTO_Credentials__c();
                PTO.Country_Code__c ='US';
                Insert PTO;
                List<Id > ClList =new List<Id>();
                Clients__c  Cl =new Clients__c ();
                Cl.Client_Name__c = 'Sample1';
                Insert Cl;
                ClList.add(Cl.id);
                Invoice_Type_Configuration__c ITC =new Invoice_Type_Configuration__c();
                ITC.Contact_Persons__c = 'sneha.b@maxval.com';
                ITC.Client__c =Cl.id;
                insert ITC;
                List<Id> ListOrd =new List<Id>();
                Set<Id > OrdSet =new Set<Id>();
                
                Order__c  Ord =new Order__c ();
                Ord.Client__c =Cl.id;
                Ord.Validation_Request_Status__c='';
                Ord.Order_Status__c='Order Placed';
                Insert Ord;
                OrdSet.add(Ord.id);
                ListOrd.add(Ord.id);
                
                Payment__c PY =new Payment__c ();
                PY.Payment_Amount__c =5800.0;
                Insert PY;
                List<Order_Item__c> listOI = NEW List<Order_Item__c>();
                Order_Item__c OI =new Order_Item__c();
                OI.Order__c =Ord.Id;
                OI.Payment__c =PY.id;
                OI.Payment_Status__c ='Payment Received';
                Insert OI;
                List<String> OIList =new List<String>();
                OIList.add(OI.id);
                
                Test.startTest();
                Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
                MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
                batchValidateWithPTO ObjBatch =new batchValidateWithPTO();
                Database.executeBatch(ObjBatch, 1);
                Test.stopTest();
        }
    }