force-app/main/default/objects/API_Auth_Detail__c/API_Auth_Detail__c.object-meta.xml
<CustomObject>
    <label>API Auth Detail</label>
    <nameField>
        <displayFormat>API-{000}</displayFormat>
        <label>API Auth Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Auth Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Auth_Detail__c/fields/Type_Of_Credential__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Credential__c</fullName>
    <label>Type Of Credential</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QB Credential</fullName>
                <default>true</default>
                <label>QB Credential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Credentials__c/API_Credentials__c.object-meta.xml
<CustomObject>
    <label>API Credentials</label>
    <nameField>
        <label>API Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/API_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>API_Request_ID__c</fullName>
    <label>API Request ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>ToBeRequested</fullName>
            </value>
            <value>
                <fullName>NotRequested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRenewalCreditMemoCreateTest.cls
@isTest
public class BatchRenewalCreditMemoCreateTest {
    static testMethod void testMethod1() 
    {
        API_Auth_Detail__c API =new API_Auth_Detail__c();
        API.Type_Of_Credential__c ='QB Credential';
        Insert API;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        List<Id> ClList =new List<Id>();
        Credit_Memo__c  cm =new Credit_Memo__c ();
        cm.API_Status__c = 'Requested';
        cm.API_Request_ID__c = 'test';
        insert cm;
        ClList.add(cm.Id);
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new RenewalCreditMemoCreateMockResponse());
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        BatchRenewalCreditMemoCreate   ObjBatch =new BatchRenewalCreditMemoCreate(ClList);
        Database.executeBatch(ObjBatch, 1);
        Test.stopTest();
    }
    
    static testMethod void testMethod2() 
    {
        API_Auth_Detail__c API =new API_Auth_Detail__c();
        API.Type_Of_Credential__c ='QB Credential';
        Insert API;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        List<Id> ClList =new List<Id>();
        Credit_Memo__c  cm =new Credit_Memo__c ();
        cm.API_Status__c = 'Requested';
        cm.API_Request_ID__c = 'test';
        insert cm;
        ClList.add(cm.Id);
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new RenewalCreditMemoCreateMockErrorResponse());
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        BatchRenewalCreditMemoCreate   ObjBatch =new BatchRenewalCreditMemoCreate(ClList);
        Database.executeBatch(ObjBatch, 1);
        Test.stopTest();
    }
    
    static testMethod void testMethod3() 
    {
        API_Auth_Detail__c API =new API_Auth_Detail__c();
        API.Type_Of_Credential__c ='QB Credential';
        Insert API;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name = 'Renewal CreditMemo Create';
        ObjAPI1.URL__c ='https://api-qa.maxval.com/v1/renewal/creditmemo/create';
        insert ObjAPI1;
        
        API_Credentials__c ObjAPI11 = new API_Credentials__c();
        ObjAPI11.Password__c ='Test1234';
        ObjAPI11.Username__c ='iyvchffclv0ixuuu';
        ObjAPI11.Name = 'MaxvalAPI';
        ObjAPI11.URL__c ='https://api-conqa.maxval.com/services/oauth2/token';
        insert ObjAPI11;
        
        List<Id> ClList =new List<Id>();
        Credit_Memo__c  cm =new Credit_Memo__c ();
        cm.API_Status__c = 'Requested';
        cm.API_Request_ID__c = 'test';
        insert cm;
        ClList.add(cm.Id);
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new RenewalCreditMemoCreateMockErrorResponse());
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        BatchRenewalCreditMemoCreate   ObjBatch =new BatchRenewalCreditMemoCreate(ClList);
        Database.executeBatch(ObjBatch, 1);
        Test.stopTest();
    }
}