force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/scheduledbatchRequestingToPayPTOTest.cls
@isTest
public class scheduledbatchRequestingToPayPTOTest {
	static testMethod void testMethod1() 
    {
        Test.startTest();
        scheduledbatchRequestingToPayPTO sbrtppt = new scheduledbatchRequestingToPayPTO();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
        String sch = '0 0 23 * * ?';
        system.schedule('Test', sch , sbrtppt );
        
        Test.stopTest();
    }
}