force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/AP_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>AP_Client_Id__c</fullName>
    <label>AP Client Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/API_Secret__c.field-meta.xml
<CustomField>
    <fullName>API_Secret__c</fullName>
    <label>API Secret</label>
    <length>100</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/API_User_Password__c.field-meta.xml
<CustomField>
    <fullName>API_User_Password__c</fullName>
    <inlineHelpText>Please concatenate Security Token with Password (password+securitytoken)</inlineHelpText>
    <label>API User Password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/API_Username__c.field-meta.xml
<CustomField>
    <fullName>API_Username__c</fullName>
    <label>API Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SymphonyAuthenticaionHelper.cls
public class SymphonyAuthenticaionHelper
{
    public static string SymphonyAuthenticaionHelper(string clienid)
    {
            string token = '';
            string strAuditText = '';
        try{
            List<Clients__c> credentials = [SELECT Id,Name,AP_Client_Id__c,API_Key__c,API_Secret__c,Endpoint_URL__c,API_Username__c,API_User_Password__c FROM Clients__c WHERE id=: clienid Limit 1];
            strAuditText += credentials.size();
            if(credentials.size() > 0)
            {        
                strAuditText += 'inside if | ';
                String UserCredentials ='grant_type=password&client_id='+credentials[0].API_Key__c+'&client_secret='+credentials[0].API_Secret__c+'&username='+credentials[0].API_Username__c+'&password='+credentials[0].API_User_Password__c;
                strAuditText += 'request body: '+ UserCredentials;
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://test.salesforce.com/services/oauth2/token');
                req.setMethod('POST');
                req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
                req.setBody(UserCredentials);
                HttpResponse res = http.send(req);
                strAuditText +='Body:'+res.getBody()+' Res Code:'+res.getstatuscode()+' Res status:'+res.getstatus(); 
                if (res.getStatusCode() == 200) {
                    responseWrapper wResp = (responseWrapper) JSON.deserialize(res.getBody(), responseWrapper.class);
                    strAuditText += wResp.access_token;
            		//AuditTrailHelper.UpdateAudit('SymphonyAuthenticaionHelper', strAuditText, 'None');
                    return wResp.access_token;
                }
                else
                    strAuditText += token;
            		//AuditTrailHelper.UpdateAudit('SymphonyAuthenticaionHelper', strAuditText, 'None');
                    return token;
            }
            
        }catch(Exception e)
        {
            strAuditText += '|| Exception: ' + e.getMessage() + ' at Line no: ' + e.getLineNumber();
            //AuditTrailHelper.UpdateAudit('SymphonyAuthenticaionHelper', strAuditText, 'None');
        }
            return token;
    }
    public class responseWrapper 
    {
        public string id;
        public string access_token;
        public string instance_url;
    }
}