force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Symphony_Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Org_Id__c</fullName>
    <label>Symphony Org Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Approval__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approval__c</fullName>
    <label>Cancellation Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Requested_On__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Requested_On__c</fullName>
    <label>Cancellation Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RenewalReinstructController.cls
@RestResource(urlMapping='/renewalreinstruct/*')
global class RenewalReinstructController
{
    @HttpPost
    global static string ReinstructRenewal(string MarsRenewalId, string RenewalInstruction, string ClientOrgId) 
    {
        Clients__c objClient = null;
        List<Clients__c> objClients = [SELECT Id FROM Clients__c WHERE Symphony_Org_Id__c= :ClientOrgId];
        if (objClients!= null && objClients.size()>0)
             objClient = objClients[0];
             
        //Client_Order_Id
        Order_Item__c objOrderItem = null;
        List<Order_Item__c> objOrderItems = [SELECT Id, Renewal_Instruction__c FROM Order_Item__c WHERE Name=:MarsRenewalId];
        if (objOrderItems != null && objOrderItems.size()>0) 
           objOrderItem = objOrderItems[0];

        string strResult = '';
        if (objOrderItem != null)
        {
            if (RenewalInstruction == 'Cancel')
            {
                objOrderItem.Cancellation_Approval__c = 'Requested';
                objOrderItem.Cancellation_Requested_On__c = System.today();
                UPDATE objOrderItem;
                strResult = 'Message: Cancellation request received';
            }
            else
            {
                strResult = 'Message: Invalid request';
            }
        }
        else
        {
            strResult = 'Message: Invalid request';
        }
        
        return strResult ;
    }
}