force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Regular Invoice</fullName>
                <default>true</default>
                <label>Regular Invoice</label>
            </value>
            <value>
                <fullName>BU Wise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Late_Fee_Maximum__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee_Maximum__c</fullName>
    <label>Late Fee (Maximum)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Late_Fee_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee_Minimum__c</fullName>
    <label>Late Fee (Minimum)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Late_fee_per_asset__c.field-meta.xml
<CustomField>
    <fullName>Late_fee_per_asset__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Late Fee per Asset</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Rush_Fee_per_Order__c.field-meta.xml
<CustomField>
    <fullName>Rush_Fee_per_Order__c</fullName>
    <label>Rush Fee per Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Late Fee (Added in USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/nRenewals_after_Instruction_Window__c.field-meta.xml
<CustomField>
    <fullName>nRenewals_after_Instruction_Window__c</fullName>
    <inlineHelpText>No. of instructed renewals after instruction due date</inlineHelpText>
    <label>No. of Renewals (Late Fee Applicable)</label>
    <summaryFilterItems>
        <field>Order_Item__c.Is_Instructed_After_Instruction_Window__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Order_Item__c.Renewal_Instruction__c</field>
        <operation>equals</operation>
        <value>Renew</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Agent_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fee_Currency__c</fullName>
    <label>Agent Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Agent_Fee_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Agent_Fee_Unit_Rate_When_Pay__c</fullName>
    <label>Agent Fee Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency_Unit_Rate_When_Pay__c</fullName>
    <label>Billing Currency Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Fee_Currency__c</fullName>
    <label>Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Fee_Unit_Rate_When_Pay__c</fullName>
    <label>Fee Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Instructed_Date__c.field-meta.xml
<CustomField>
    <fullName>Instructed_Date__c</fullName>
    <label>Instructed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Instruction_Date_From__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Date_From__c</fullName>
    <label>Instruction Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Instruction_Date_To__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Date_To__c</fullName>
    <label>Instruction Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name__c</fullName>
    <label>Invoice Type Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Currency__c</fullName>
    <label>Service Fee Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Service_Fee_Unit_Rate_When_Pay__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Unit_Rate_When_Pay__c</fullName>
    <label>Service Fee Unit Rate (When Pay)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Close_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Close_Date_To_Pay__c</fullName>
    <label>Suggested Close Date to Pay</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Suggested_Open_Date_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Open_Date_To_Pay__c</fullName>
    <label>Suggested Payment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_Date_From__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_From__c</fullName>
    <label>Schedule Date From</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_Date_To__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_To__c</fullName>
    <label>Schedule Date To</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Schedule_From__c.field-meta.xml
<CustomField>
    <fullName>Schedule_From__c</fullName>
    <label>Schedule From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Date</fullName>
            </value>
            <value>
                <fullName>Last Day of Week of Due Date</fullName>
            </value>
            <value>
                <fullName>Last Day of Month of Due Date</fullName>
            </value>
            <value>
                <fullName>First Day of Month of Due Date</fullName>
            </value>
            <value>
                <fullName>First Day of Week of Due Date</fullName>
            </value>
            <value>
                <fullName>First Day Of Next Month Of Due Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency_All.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AQD</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <masterLabel>Currency All</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderItemBatch.cls
global with sharing class OrderItemBatch implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    public List<Id> SelectedOrderItemIds {get;set;}
    global OrderItemBatch  ()
    {
    }
    global OrderItemBatch  (List<Id> lstSelectedOrderItemIds)
    {
        SelectedOrderItemIds = lstSelectedOrderItemIds;
    }
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        if (SelectedOrderItemIds !=null && SelectedOrderItemIds.size()>0) 
            return Database.getQueryLocator([SELECT Id, Jurisdiction__c, Path__c, Order__c, Order__r.Client__c, Order__r.Client__r.Invoice_Type__c, Invoice_Type_Name__c, Due_Date__c, Payment_Mode__c, Suggested_Open_Date_To_Pay__c,Suggested_Close_Date_To_Pay__c, Instruction_Date_From__c, Instruction_Date_To__c, Instructed_Date__c, Billing_Currency__c, Fee_Currency__c, Fee_Unit_Rate_When_Pay__c, Service_Fee_Currency__c, Service_Fee_Unit_Rate_When_Pay__c, Agent_Fee_Currency__c, Agent_Fee_Unit_Rate_When_Pay__c FROM Order_Item__c WHERE Id IN :SelectedOrderItemIds]);
        else
            return Database.getQueryLocator([SELECT Id, Jurisdiction__c, Path__c, Order__c, Order__r.Client__c, Order__r.Client__r.Invoice_Type__c, Invoice_Type_Name__c, Due_Date__c, Payment_Mode__c, Suggested_Open_Date_To_Pay__c,Suggested_Close_Date_To_Pay__c, Instruction_Date_From__c, Instruction_Date_To__c, Instructed_Date__c, Billing_Currency__c, Fee_Currency__c, Fee_Unit_Rate_When_Pay__c, Service_Fee_Currency__c, Service_Fee_Unit_Rate_When_Pay__c, Agent_Fee_Currency__c, Agent_Fee_Unit_Rate_When_Pay__c FROM Order_Item__c]);              
    }
    global void execute(Database.BatchableContext BC, List<sObject> objScopeObjectList)
    {
        AuditTrailHelper.UpdateAudit('OrderItemBatch - execution start', 'Start', 'None');
        string strAuditText = '';
        try
        { 
            strAuditText+='Size of items-'+objScopeObjectList.size();
            Map<string, Currency__c> mapCurrency = new Map<string, Currency__c>();
            Payment_Schedule__c paymentSchedule=new Payment_Schedule__c();
            Map<string, Payment_Schedule__c> paymentScheduleMap = new Map<string, Payment_Schedule__c>();
            List<Payment_Schedule__c> objPaymentScheduleList = [SELECT Jurisdiction__c, Payment_Mode__c, Schedule_From__c, Schedule_Date_From__c, Schedule_Date_To__c FROM Payment_Schedule__c];
            List<Currency__c> objCurrencyList = [SELECT Id, Name, Exchange_Rate__c FROM Currency__c];
            for(Currency__c objCurrency : objCurrencyList)
            {
                if (mapCurrency.containsKey(objCurrency.Name)==false)
                    mapCurrency.put(objCurrency.Name, objCurrency);
            }
            for(Payment_Schedule__c objPaymentSchedule:objPaymentScheduleList)
            {
                if (!paymentScheduleMap.containsKey(objPaymentSchedule.Jurisdiction__c))
                    paymentScheduleMap.put(objPaymentSchedule.Jurisdiction__c, objPaymentSchedule);
            }
            Map<Id, Id> mapOrders = new Map<Id, Id>();
            Map<Id, string> mapOrderItemIds = new Map<Id, string>();
            List<Order_Item__c> objOrderItemList = new List<Order_Item__c>();
            for(sObject objScopeObject : objScopeObjectList)
            {
                Order_Item__c objOrderItem = (Order_Item__c) objScopeObject;
                
                if (mapOrders.containsKey(objOrderItem.Order__c)==false)
                    mapOrders.put(objOrderItem.Order__c, objOrderItem.Order__c);
                if(paymentScheduleMap.containsKey(objOrderItem.Jurisdiction__c))
                {
                    paymentSchedule=paymentScheduleMap.get(objOrderItem.Jurisdiction__c);
                    strAuditText+='paymentSchedule-'+paymentSchedule;
                    PaymentScheduleWrapper objPaymentScheduleWrapper = PaymentScheduleHelper.GetScheduledDates(paymentSchedule.Schedule_From__c, objOrderItem.Due_Date__c, Integer.valueOf(paymentSchedule.Schedule_Date_From__c), Integer.valueOf(paymentSchedule.Schedule_Date_To__c));
                    objOrderItem.Suggested_Open_Date_To_Pay__c = objPaymentScheduleWrapper.ScheduleStartDate;
                    objOrderItem.Suggested_Close_Date_To_Pay__c = objPaymentScheduleWrapper.ScheduleCloseDate;
                    objOrderItem.Payment_Mode__c = paymentSchedule.Payment_Mode__c;
                }
                else
                    strAuditText +='Payment Schedule is not available for '+objOrderItem.Jurisdiction__c+' jurisdiction||';
                
                /*List<Payment_Schedule__c> objPaymentSchedule = [SELECT Jurisdiction__c, Payment_Mode__c, Schedule_From__c, Schedule_Date_From__c, Schedule_Date_To__c FROM Payment_Schedule__c WHERE Jurisdiction__c =:objOrderItem.Jurisdiction__c LIMIT 1];
                if(objPaymentSchedule.size()>0){
                    PaymentScheduleWrapper objPaymentScheduleWrapper = PaymentScheduleHelper.GetScheduledDates(objPaymentSchedule[0].Schedule_From__c, objOrderItem.Due_Date__c, Integer.valueOf(objPaymentSchedule[0].Schedule_Date_From__c), Integer.valueOf(objPaymentSchedule[0].Schedule_Date_To__c));
                    objOrderItem.Suggested_Open_Date_To_Pay__c = objPaymentScheduleWrapper.ScheduleStartDate;
                    objOrderItem.Suggested_Close_Date_To_Pay__c = objPaymentScheduleWrapper.ScheduleCloseDate;
                    objOrderItem.Payment_Mode__c = objPaymentSchedule[0].Payment_Mode__c;
                }*/
                                
                strAuditText +='objOrderItem.Billing_Currency__c:' + objOrderItem.Billing_Currency__c;
                if (mapCurrency.containsKey(objOrderItem.Billing_Currency__c))
                {
                    objOrderItem.Billing_Currency_Unit_Rate_When_Pay__c = mapCurrency.get(objOrderItem.Billing_Currency__c).Exchange_Rate__c;
                    strAuditText +='Yes';
                }
                strAuditText +='No';
                if (mapCurrency.containsKey(objOrderItem.Fee_Currency__c))
                    objOrderItem.Fee_Unit_Rate_When_Pay__c = mapCurrency.get(objOrderItem.Fee_Currency__c).Exchange_Rate__c;
                if (mapCurrency.containsKey(objOrderItem.Service_Fee_Currency__c))
                    objOrderItem.Service_Fee_Unit_Rate_When_Pay__c = mapCurrency.get(objOrderItem.Service_Fee_Currency__c).Exchange_Rate__c;
                if (mapCurrency.containsKey(objOrderItem.Agent_Fee_Currency__c))
                    objOrderItem.Agent_Fee_Unit_Rate_When_Pay__c = mapCurrency.get(objOrderItem.Agent_Fee_Currency__c).Exchange_Rate__c;    
                
                WindowConfigurationWrapper objWindowConfigurationWrapper = WindowConfigurationHelper.GetWindowDates(objOrderItem.Order__r.Client__c);
                objOrderItem.Instruction_Date_From__c = objWindowConfigurationWrapper.InstructionWindowStartDate;
                objOrderItem.Instruction_Date_To__c = objWindowConfigurationWrapper.InstructionWindowCloseDate ;
                objOrderItem.Instructed_Date__c = Date.Today();

                //Update UniqueId
                /*
                if (objOrderItem.Path__c == null)
                    objOrderItem.Path__c = '';
                if (objOrderItem.Order__r.Client__r.Invoice_Type__c == 'Regular Invoice')
                    objOrderItem.Invoice_Type_Name__c = objOrderItem.Order__r.Client__c + '_' + objOrderItem.Order__c + '_' + objOrderItem.Billing_Currency__c;
                else if (objOrderItem.Order__r.Client__r.Invoice_Type__c == 'BU Wise')    
                    objOrderItem.Invoice_Type_Name__c = objOrderItem.Order__r.Client__c + '_' + objOrderItem.Order__c + '_' + objOrderItem.Path__c + '_' + objOrderItem.Billing_Currency__c;            
                */
                objOrderItemList.add(objOrderItem);
                
                
                
                if (mapOrderItemIds.containsKey(objOrderItem.Id)==false)
                    mapOrderItemIds.put(objOrderItem.Id, string.valueOf(objOrderItem.Id));
            }
            UPDATE objOrderItemList;
            
            //Read the clients
            Set<Id> setOrderIds = mapOrders.keySet();
            Map<Id, Clients__c> mapClients =  new Map<Id, Clients__c>();
            List<Clients__c> objClients = [SELECT Id, Late_fee_per_asset__c, Late_Fee_Minimum__c, Late_Fee_Maximum__c, Rush_Fee_per_Order__c FROM Clients__c WHERE Id IN (SELECT Client__c FROM Order__c WHERE Id IN :setOrderIds)];
            for(Clients__c objClient : objClients)
            {
                if (mapClients.containsKey(objClient.Id)==false)
                    mapClients.put(objClient.Id, objClient);
            }
            
            //Read the Orders
            List<Order__c> objOrders = [SELECT Id, Client__c, nRenewals_after_Instruction_Window__c, Late_Fee__c, nRush_Renewals__c, Rush_Fee__c  FROM Order__c WHERE Id IN :setOrderIds];
            for(Order__c objOrder : objOrders)
            {
                Clients__c objClient = mapClients.get(objOrder.Client__c);
                if (objOrder.nRenewals_after_Instruction_Window__c >0)
                {
                    decimal LateFeeTotal = objOrder.nRenewals_after_Instruction_Window__c * objClient.Late_fee_per_asset__c;
                    if (LateFeeTotal < objClient.Late_Fee_Minimum__c)
                        LateFeeTotal = objClient.Late_Fee_Minimum__c; 
                    if (LateFeeTotal > objClient.Late_Fee_Maximum__c)
                        LateFeeTotal = objClient.Late_Fee_Maximum__c; 
                    objOrder.Late_Fee__c = LateFeeTotal;
                }
                if (objOrder.nRush_Renewals__c >0)
                    objOrder.Rush_Fee__c= objOrder.nRush_Renewals__c * objClient.Rush_Fee_per_Order__c;
                objOrder.Job_Status__c='Completed';
            }
            UPDATE objOrders;
            strAuditText+='|updated orders|';
             
            List<string> strOrderItemIds = mapOrderItemIds.values();
            if (strOrderItemIds!= null && strOrderItemIds.size()>0)
            {
                List<Batch_Queue__c> objBatchQueueList = [SELECT Id, Status__c FROM Batch_Queue__c WHERE Parent_Id__c IN :strOrderItemIds AND Name = 'Order Item'];
                for(Batch_Queue__c objBatchQueue :objBatchQueueList )
                {
                    objBatchQueue.Status__c = 'Completed';
                }
                if (objBatchQueueList != null && objBatchQueueList.size()>0)
                    UPDATE objBatchQueueList;
            }
            
        }
        catch(Exception exp)
        {
             strAuditText += 'Error:' + exp.getMessage() + '|' + exp.getStackTraceString()+'|'+ exp.getLineNumber();
        }
        finally
        {
            AuditTrailHelper.UpdateAudit('OrderItemBatch', strAuditText, 'None');
        }
    }
    global void finish(Database.BatchableContext BC)
    {
        //AuditTrailHelper.UpdateAudit('Order Item batch', 'SelectedOrderItemIds:' + SelectedOrderItemIds , 'None');
    }
    
}