force-app/main/default/objects/Renewal_Chat__c/Renewal_Chat__c.object-meta.xml
<CustomObject>
    <label>Renewal Chat</label>
    <nameField>
        <displayFormat>RC-{0000000}</displayFormat>
        <label>Renewal Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Renewal_Chat__c/fields/Chat_Text__c.field-meta.xml
<CustomField>
    <fullName>Chat_Text__c</fullName>
    <label>Chat Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/fields/From_Symphony__c.field-meta.xml
<CustomField>
    <fullName>From_Symphony__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Symphony</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/fields/From_UserId__c.field-meta.xml
<CustomField>
    <fullName>From_UserId__c</fullName>
    <label>From UserId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Renewal_Chat__c/fields/MaRS_Reference_ID__c.field-meta.xml
<CustomField>
    <fullName>MaRS_Reference_ID__c</fullName>
    <label>MaRS Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RenewalsChatServiceClass.cls
@RestResource(urlMapping='/renewals/chat/*')
global class RenewalsChatServiceClass
{
    @HttpPost
    global static responsebody RenewalsChat() 
    {
        responsebody resp = NEW responsebody();
        try
        {
            system.debug('RenewalsChatServiceClass service called');
            //responcebody res = (responcebody)RestContext.request.requestBody;
            String jsonString = RestContext.request.requestBody.toString();
            system.debug('Req Body: '+jsonString );
            JSONParser parser = JSON.createParser(jsonString);
            requestbody req = (requestbody)parser.readValueAs(requestbody.class);
            if(req != null)
            {
                Renewal_Chat__c rc = NEW Renewal_Chat__c();
                rc.Chat_Text__c = req.ChatMessage;
                rc.From__c = req.FromName;
                rc.From_UserId__c = req.FromUserID;
                rc.From_Symphony__c = true;
                rc.MaRS_Reference_ID__c = req.MaRSReferenceID;
                insert rc;
                resp.Status = true;
            } 
            else
            {
                resp.Status = false;
                error er = NEW error();
                er.Code = 'NO_DATA_FOUND';
                er.Description= 'No data found';
                resp.Error = er;
            }
        }
        catch(exception e)
        {
            resp.Status = false;
            error er = NEW error();
            er.Code = '-';
            er.Description = e.getMessage();
            resp.Error = er;
        }
        return  resp;        
    }
    
    global class requestbody
    {
        global string MaRSReferenceID{set;get;}
        global string FromUserID{set;get;}
        global string FromName{set;get;}
        global string ChatMessage{set;get;}
    }
    global class responsebody
    {
        public boolean Status{set;get;}
        global error Error{set;get;}
    }
    global class error
    {
        global string Description{set;get;}
        global string Code{set;get;}
    }
}