force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Approval__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approval__c</fullName>
    <label>Cancellation Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RenewalStatusHelper.cls
public with sharing class RenewalStatusHelper
{
    public static List<string> GetRequestedMarsRenewalIds(APIRenewalStatusRequest MarsRenewalIdRequest)
    {
        List<string> lstMarRenewalIds= new List<string>();
        for(APIRenewalStatusLineItemRequest objRequest : MarsRenewalIdRequest.MarsRenewalIds)
        {
            lstMarRenewalIds.add(objRequest.MarsRenewalId);
        }
        return lstMarRenewalIds;
    }
    public static Map<string, Order_Item__c> GetOrderItemsForRequestedMarsRenewalIds(List<string> lstMarRenewalIds)
    {
        Map<string, Order_Item__c> mapOrderItems = new Map<string, Order_Item__c>();
        List<Order_Item__c> objOrderItems = [SELECT Id, Cancellation_Approval__c, Renewal_Instruction__c, Payment_Status__c FROM Order_Item__c WHERE Name IN :lstMarRenewalIds];
        for(Order_Item__c objOrderItem : objOrderItems)
        {
            if (mapOrderItems.containsKey(objOrderItem.Name)==false)
            {
                mapOrderItems.put(objOrderItem.Name, objOrderItem); 
            }
        }
        return mapOrderItems;
    }
}