force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PTO Fee (Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Is_PTO_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Is_PTO_Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PTO fee paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_On__c.field-meta.xml
<CustomField>
    <fullName>Paid_On__c</fullName>
    <label>PTO Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requesting to Pay PTO</fullName>
            </value>
            <value>
                <fullName>Requested to Pay PTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipName>Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Approval_Status__c</fullName>
    <label>Payment Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested to Approve</fullName>
                <label>Awaiting Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approve</fullName>
                <isActive>false</isActive>
                <label>Approve</label>
            </value>
            <value>
                <fullName>Decline</fullName>
                <isActive>false</isActive>
                <label>Decline</label>
            </value>
            <value>
                <fullName>Request to Approve</fullName>
                <isActive>false</isActive>
                <label>Request to Approve</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Payment_Confirmation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Confirmation</label>
    <referenceTo>Payment_Confirmation__c</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/PTO_Validation_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>PTO_Validation_Request_ID__c</fullName>
    <label>PTO Validation Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Status__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Status__c</fullName>
    <label>Renewal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruction Received</fullName>
            </value>
            <value>
                <fullName>Payment Confirmation Sent to PTO</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Ref. No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/Payment_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Payment Confirmation</label>
    <nameField>
        <label>Ref. No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Confirmations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Confirmation__c/fields/Amount_for_selected_Assets__c.field-meta.xml
<CustomField>
    <fullName>Amount_for_selected_Assets__c</fullName>
    <label>Amount for selected Assets</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Memo</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Payment_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Currency__c</fullName>
    <label>Payment Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Wire_Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Wire_Bank_Fee__c</fullName>
    <label>Wire/Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QB_Account__c/QB_Account__c.object-meta.xml
<CustomObject>
    <label>QB Account</label>
    <nameField>
        <label>QB Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>QB Accounts</relationshipLabel>
    <relationshipName>QB_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Account__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QB_Account__c/fields/QB_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Account_Id__c</fullName>
    <label>QB Account Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Currency_All.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AQD</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <masterLabel>Currency All</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/createAttachPaymentConfirmation.cls
public with sharing class createAttachPaymentConfirmation {
    private ApexPages.StandardSetController standardController;
    Public list<String> selectedids{Set;Get;}
    Public String listviewURL{Set;Get;}
    Public Boolean openCmp{Set;Get;}
    Public createAttachPaymentConfirmation(ApexPages.StandardSetController controller) {
        this.standardController = controller;
        /* MARS-753 When user completes Attach Payment Confirmation, System should show the Assets screens with Make Payment Filter.
        Added by Saranyaa */
        //Get the return url if it's in Lightning view
        listviewURL = ApexPages.currentPage().getParameters().get('vfRetURLInSFX');
        If(listviewURL == null || listviewURL == '')
        {
            //Get the return url if it's in classic view
            listviewURL = ApexPages.currentPage().getParameters().get('retURL');
            If(listviewURL == null || listviewURL == ''){
                listviewURL = '/lightning/o/Order_Item__c/list?filterName=All';
            }
        }
        system.debug('listviewURL :'+listviewURL); 
        openCmp = True;
        selectedids = New List < String > ();
        list<Order_Item__c> SelectedrederItems = new list<Order_Item__c>();
        /* MARS-795 Error Message should be Added when User clicks on Attach Payment Confirmation in other List view
        Added by Saranyaa */
        if(listviewURL.contains('00B5e00000AYumVEAT'))//00B5e00000AYumVEAT - id of MakePayments listview; Add order ids only when assets are from Make Payments listview
        {
            SelectedrederItems = (Order_Item__c[])controller.getSelected();
            if(SelectedrederItems!=null && SelectedrederItems.size()>0)
            {            
                for(Order_Item__c orderitem : SelectedrederItems)
                {
                  selectedids.add(orderitem.Id);
                }
            }
        }
    }
    @auraenabled
    public static myDataWrapper getDetails(string sids)
    {
        sids = sids.replaceAll( '\\s+', '');
        system.debug('before: '+sids);
        sids = sids.substring( 1, sids.length()-1);
        system.debug('after: '+sids);
        List<string> ids = NEW List<string>();
        list<myPickListWrapper> pOptions = new list<myPickListWrapper>();
        list<myPickListWrapper> pmOptions = new list<myPickListWrapper>();
        list<myPickListWrapper> bOptions = new list<myPickListWrapper>();
        list<myPickListWrapper> ccOptions = new list<myPickListWrapper>();
        myPickListWrapper nonePickValue= NEW myPickListWrapper(); 
        nonePickValue.label = '--Select--';
        nonePickValue.value = '';
        pOptions.add(nonePickValue);
        pmOptions.add(nonePickValue);            
        bOptions.add(nonePickValue);
        ccOptions.add(nonePickValue);
        if(sids.contains(','))
        {
            list<string> sssids =sids.split(',');
            for(string str : sssids)
            {
                String s = str.trim();
                ids.add(s);
                system.debug(s.length());
            }
        }
        else
            ids.add(sids.trim());
            
        myPayConf pc = NEW myPayConf();
        pc.Name='';
        pc.AmtForSelected=0;
        pc.payCurrency='';
        pc.AmtPaid=0;
        pc.exgRate=0;
        pc.payType='';
        pc.BAcc='';
        pc.CCAcc='';
        pc.WireBankFee=0;
        pc.pdate = date.today();
        pc.pcMemo='';
        myDataWrapper mydata = NEW myDataWrapper();
        Decimal a = 0;
        mydata.AssetIDs = ids;
        if(sids != '')
        {
            list<Order_Item__c> paymentRecievedItems = NEW list<Order_Item__c>();
            list<Order_Item__c> paymentNotRecievedItems = NEW list<Order_Item__c>();
            boolean errorInData = false;
            system.debug('>>Condition');
            set<string> Jurisdictions= NEW set<string>();
            /*MARS-775 Proper Error Message should be shown
            * Added by Saranyaa */
            string orderItemNamewithError = '';
            string paymentConfirmationName = '';
            boolean ispaymentConfirmationAvailable = false;
            boolean isMultipleErrors = false;
            for(Order_Item__c oi : [SELECT id,Name,Fee__c,Jurisdiction__c,Payment__c,Payment_Approval_Status__c,Renewal_Status__c,Payment_Status__c,Payment_Confirmation__c FROM Order_Item__c WHERE ID IN: ids])
            {
                a = a + oi.Fee__c;
                Jurisdictions.add(oi.Jurisdiction__c);    
                if(oi.Payment__c == null && oi.Payment_Approval_Status__c != 'Approved')
                {
                	system.debug('Payment Confirmation can be attached only for assets after Recording the Payment. Payment__c - ' + oi.Renewal_Status__c + ' Payment_Approval_Status__c' + oi.Payment_Approval_Status__c);
                    errorInData = true;
                    mydata.errorMessage = 'Payment Confirmation can be attached only for assets after Recording the Payment.';
                }
                else if(oi.Renewal_Status__c == 'Asset Renewed' || oi.Payment_Status__c == 'PTO/Agent Payments Completed')
                {
                   system.debug('Payment Confirmation cannot be attached for assets that are Renewed. Renewal status - ' + oi.Renewal_Status__c);
                   errorInData = true;
                   mydata.errorMessage = 'Payment Confirmation cannot be attached for assets that are Renewed';
                }
                else if(oi.Payment_Confirmation__c != null){
                   	system.debug('Payment Confirmation already attached.');
                    errorInData = true;
                    orderItemNamewithError = oi.Name;
                    List<Payment_Confirmation__c> pc1 = [SELECT Name FROM Payment_Confirmation__c WHERE Id =: oi.Payment_Confirmation__c];
                    if(pc1.size() > 0){
                        system.debug('RefNo. - ' + pc1[0].Name);
                        paymentConfirmationName = pc1[0].Name;
                        if(ispaymentConfirmationAvailable)
                            isMultipleErrors = true;
                        ispaymentConfirmationAvailable = true;
                    }
                }
            }
            if(errorInData == false)
            {
                system.debug('Selected assets have no error');
                pc.AmtForSelected = a;
            }   
            else if(Jurisdictions.size() > 1)
            {
                system.debug('Assets with different jurisdictions are selected');
                mydata.errorInData = true;
                mydata.errorMessage = 'Please select single jurisdiction assets';
            }            
            else if(ispaymentConfirmationAvailable == true)
            {
                if(isMultipleErrors == true)
                {
                    mydata.errorInData = true;
                    mydata.errorMessage = 'The Assets already have Payment Confirmation Attachment';
                }
                else{                         
                    mydata.errorInData = true;
                    mydata.errorMessage = 'The Asset - '+ orderItemNamewithError +' already has Payment Confirmation Attachment - ' + paymentConfirmationName;
                }
            }else
            {
            	mydata.errorInData = true;
            }
            Schema.DescribeFieldResult fieldResultPC = Payment_Confirmation__c.Payment_Currency__c.getDescribe();
            List<Schema.PicklistEntry> pValuesPC = fieldResultPC.getPicklistValues();
            for (Schema.PicklistEntry p: pValuesPC) {
                myPickListWrapper op = NEW myPickListWrapper();
                op.label = p.getLabel();
                op.value = p.getValue();
                pOptions.add(op);
            }
            Schema.DescribeFieldResult fieldResultPM = Payment_Confirmation__c.Payment_Method__c.getDescribe();
            List<Schema.PicklistEntry> pValuesPM = fieldResultPM.getPicklistValues();
            for (Schema.PicklistEntry p: pValuesPM) {
                myPickListWrapper op = NEW myPickListWrapper();
                op.label = p.getLabel();
                op.value = p.getValue();
                pmOptions.add(op);
            }
            mydata.PaymentCurrencyPickList = pOptions;
            mydata.PaymentMethodPickList = pmOptions;
            List<QB_Account__c> lstQBA = [Select id,Name,QB_Account_Id__c,Account_Type__c FROM QB_Account__c WHERE Account_Type__c IN('Bank','Credit Card')];
            if(lstQBA.size()>0)
            {
                for(QB_Account__c qba : lstQBA)
                {
                    myPickListWrapper op = NEW myPickListWrapper();
                    op.label = qba.Name;
                    op.value = qba.Name+'||'+qba.QB_Account_Id__c;
                    if(qba.Account_Type__c == 'Bank')
                    {
                        bOptions.add(op);
                    }
                    if(qba.Account_Type__c == 'Credit Card')
                    {
                        ccOptions.add(op);
                    }                
                }
                mydata.BankAccsPickList = bOptions;
                mydata.CCAccsPickList = ccOptions;
            }
            else
            {
                //mydata.errorInData = true;
                //mydata.errorMessage = 'There are no Bank/Credit Card QB Accounts';
            }
            mydata.payAtt = pc;            
        }else{
            mydata.errorInData = true;
            mydata.errorMessage = 'Please select atleast one asset from the listview - Make Payments';        
        }
        system.debug(mydata);
        return mydata;
    }
    @auraenabled
    public static string createPaymentConfirmation (List<ID> OIIds, myPayConf pc)
    {
        system.debug('OIIds :'+OIIds+' >> pc : '+pc);
        string returnString = 'Success';
        try
        {
            Payment_Confirmation__c recPC = NEW Payment_Confirmation__c();
            recPC.Name = pc.Name;
            recPC.Amount_for_selected_assets__c = pc.AmtForSelected;
            system.debug('Amount_for_selected_assets__c: '+recPC.Amount_for_selected_assets__c);
            recPC.Payment_Currency__c = pc.payCurrency;
            
            recPC.Payment_Amount__c = pc.AmtPaid;
            recPC.Payment_Method__c = pc.payType;
            system.debug(pc.BAcc +'>>'+pc.CCAcc);
            //recPC.Name = pc.BAcc;
            //recPC.Name = pc.CCAcc;
            recPC.Wire_Bank_Fee__c = pc.WireBankFee;
            recPC.Payment_Date__c = pc.pdate;
            recPC.Description__c = pc.pcMemo;
            insert recPC;
            List<Order_Item__c> listOIs = NEW List<Order_Item__c>();
            for(ID assetId : OIIds)
            {
                Order_Item__c oi =NEW Order_Item__c();
                oi.id = assetId;
                oi.Payment_Confirmation__c = recPC.id;
                oi.Paid_On__c = recPC.Payment_Date__c;
                oi.Is_PTO_Fee_Paid__c = true;	
                listOIs.add(oi);
                system.debug(oi);
            }
            if(listOIs.size() > 0) 
            {
               system.debug('listsize : '+listOIs.size());
               update listOIs; 
            }
                
            List<ptoValidationReqWrapper> wrplst = NEW List<ptoValidationReqWrapper>();
            List<Order_Item__c> listOI = [Select id,Name,Order__r.Client__c,PTO_Validation_Request_ID__c,Paid_Status__c,Surcharge__c,
                                          Payment_Status__c,Order_Number__c,Client__c,Jurisdiction__c,Billing_Currency__c,Entity_Type_Name__c,
                                          Fee_Amount_When_Pay__c,Application_No__c,Patent_No__c,MV_API_Ref_Id__c,
                                          Invoice_Type_Name_Value__c,Invoice__c,Invoice__r.Name,Term_Name__c,Fee__c,Invoice__r.Invoice_No__c,Order__r.Name,Payment_API_Message__c 
                                          ,Payment_Confirmation__c,Payment_Confirmation__r.Payment_API_Message__c,Payment_Confirmation__r.Payment_Amount__c,Payment_Confirmation__r.Payment_Method__c,Payment_Confirmation__r.Description__c,Payment_Confirmation__r.Exchange_Rate__c,Payment_Confirmation__r.Wire_Bank_Fee__c
                                          from Order_Item__c WHERE ID IN: OIIds];
            ptoValidationReqWrapper wrp = NEW ptoValidationReqWrapper();
            wrp.countryCode = listOI[0].Jurisdiction__c;
            wrp.countryAssets = listOI;
            wrplst.add(wrp);
            if(!test.isRunningTest())
            {
                system.debug('pc.BAcc :'+pc.BAcc+' >> pc.CCAcc : '+pc.CCAcc );
                if(pc.BAcc != null && pc.BAcc!='')
                {
                    batchRenewalBillCreate cls = NEW batchRenewalBillCreate(wrplst, pc.BAcc);
                    database.executeBatch(cls,1);
                }
                if(pc.CCAcc != null && pc.CCAcc!='')
                {
                    batchRenewalBillCreate cls = NEW batchRenewalBillCreate(wrplst, pc.CCAcc);
                    database.executeBatch(cls,1);
                }
            }
            returnString = returnString+'-'+recPC.Id;
            return returnString;
        }
        catch(exception e)
        {
            returnString = 'Error : '+ e.getMessage() +' Line: '+e.getLineNumber()+' Cause: '+e.getCause();
            return returnString;
        }
    }
    public class myDataWrapper
    {
        @auraenabled
        public boolean errorInData{set;get;}
        @auraenabled
        public string errorMessage{set;get;}
        @auraenabled
        public List<myPickListWrapper> PaymentCurrencyPickList{set;get;}
        @auraenabled
        public List<myPickListWrapper> PaymentMethodPickList{set;get;}
        @auraenabled
        public List<myPickListWrapper> BankAccsPickList{set;get;}
        @auraenabled
        public List<myPickListWrapper> CCAccsPickList{set;get;}
        @auraenabled
        public List<string> AssetIDs{set;get;}
        @auraenabled
        public myPayConf payAtt{set;get;}
    }
    public class myPickListWrapper
    {
        @auraenabled
        public string label{set;get;}
        @auraenabled
        public string value{set;get;}
    }
    public class myPayConf
    {
        @auraenabled
        public string Name{set;get;}
        @auraenabled
        public Decimal AmtForSelected{set;get;}
        @auraenabled
        public string payCurrency{set;get;}
        @auraenabled
        public Decimal AmtPaid{set;get;}
        @auraenabled
        public Decimal exgRate{set;get;}
        @auraenabled
        public string payType{set;get;}
        @auraenabled
        public string BAcc{set;get;}
        @auraenabled
        public string CCAcc{set;get;}
        @auraenabled
        public Decimal WireBankFee{set;get;}
        @auraenabled
        public date pdate{set;get;}
        @auraenabled
        public string pcMemo{set;get;}
    }
}