force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Text_Message__c.field-meta.xml
<CustomField>
    <fullName>Text_Message__c</fullName>
    <label>Text Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/RenewalsCommentAPIController.cls
@RestResource(urlMapping='/comments/*')
global class RenewalsCommentAPIController 
{
    @HttpPost
    global static void CommentRenewals( string Message) //, string sendBy, string ClientOrgId
    {
        Message__c objmessage = new Message__c();
        objmessage.Text_Message__c =  Message;
        
        INSERT  objmessage;
        
        /*Message__c MessageCreated = [SELECT Id, Text_Message__c FROM Message__c WHERE Id = :objmessage.Id];
        return 'Success';*/
    }
        
        

}