force-app/main/default/objects/APIMessage__c/APIMessage__c.object-meta.xml
<CustomObject>
    <label>APIMessage</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Cancellation_Approval__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approval__c</fullName>
    <label>Cancellation Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Renewal_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Instruction__c</fullName>
    <label>Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Instruction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Renewal_Instruction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Renew</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <masterLabel>Renewal Instruction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RenewalStatusAPIController.cls
@RestResource(urlMapping='/renewalstatus/*')
global class RenewalStatusAPIController
{
    @HttpPost
    global static void GetRenewalStatus() 
    {
        //Read the Request
        APIRenewalStatusRequest MarsRenewalIdRequest= (APIRenewalStatusRequest) JSON.deserialize(RestContext.request.requestBody.toString(), APIRenewalStatusRequest.Class);
        
        //Intiate Response Object
        APIRenewalStatusResponse objMarsRenewalIdResponse = new APIRenewalStatusResponse();
        objMarsRenewalIdResponse.IsSuccess = true;
        objMarsRenewalIdResponse.Messages =  new List<APIMessage>();
        objMarsRenewalIdResponse.MarsRenewalIds = new List<APIRenewalStatusLineItemResponse>();
        
        //Read error messages
        Map<string, APIMessage__c> mapMessages = APIMessageController.GetAllMessages();
        
        
        if (MarsRenewalIdRequest!=null && MarsRenewalIdRequest.MarsRenewalIds != null && MarsRenewalIdRequest.MarsRenewalIds.size()>0)
        {
            //Validation.1. Checck no. of renewals upto 10 in one request
            if (MarsRenewalIdRequest.MarsRenewalIds.size()>10)
            {
                objMarsRenewalIdResponse.IsSuccess = false;
                objMarsRenewalIdResponse.Messages.add(APIMessage.GetMessage(mapMessages, 'API.RS.001'));
            }
            
            //Process
            if (objMarsRenewalIdResponse.IsSuccess)
            {
                List<string> lstMarRenewalIds = RenewalStatusHelper.GetRequestedMarsRenewalIds(MarsRenewalIdRequest);
                Map<string, Order_Item__c> mapOrderItems = RenewalStatusHelper.GetOrderItemsForRequestedMarsRenewalIds(lstMarRenewalIds);
                
                for(APIRenewalStatusLineItemRequest objRequest : MarsRenewalIdRequest.MarsRenewalIds)
                {
                    APIRenewalStatusLineItemResponse objLineItemResponse = new APIRenewalStatusLineItemResponse();
                    objLineItemResponse.IsSuccess = true;
                    objLineItemResponse.MarsRenewalId = objRequest.MarsRenewalId;
                    objLineItemResponse.Messages = new List<APIMessage>();
                    
                    if (mapOrderItems.containsKey(objRequest.MarsRenewalId))
                    {
                        Order_Item__c objOrderItem = mapOrderItems.get(objRequest.MarsRenewalId);
                        if (objOrderItem != null)
                        {
                            objLineItemResponse.RenewalInstruction = objOrderItem.Renewal_Instruction__c;
                            objLineItemResponse.PaymentStatus = objOrderItem.Payment_Status__c;
                            if (objOrderItem.Cancellation_Approval__c == 'Requested')
                            {
                                objLineItemResponse.Messages.add(APIMessage.GetMessage(mapMessages, 'API.RS.003'));
                            }
                            else if (objOrderItem.Renewal_Instruction__c == 'Cancel')
                            {
                                objLineItemResponse.Messages.add(APIMessage.GetMessage(mapMessages, 'API.RS.004'));
                            }
                        }
                        else
                        {
                            objLineItemResponse.IsSuccess = false;
                            objLineItemResponse.Messages.add(APIMessage.GetMessage(mapMessages, 'API.RS.002'));
                        }
                    }
                    else
                    {
                        objLineItemResponse.IsSuccess = false;
                        objLineItemResponse.Messages.add(APIMessage.GetMessage(mapMessages, 'API.RS.002'));
                    }
                    objMarsRenewalIdResponse.MarsRenewalIds.add(objLineItemResponse);
                }
            }
        }
        else
        {
            objMarsRenewalIdResponse.IsSuccess = false;
            objMarsRenewalIdResponse.Messages.add(APIMessage.GetMessage(mapMessages, 'API.CMN.001'));
        }
        
        
        //Set the response
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(objMarsRenewalIdResponse));
        //RestContext.response.responseBody = Blob.valueOf('{ "status" : "' + RenewalStatus + '", "message" : "' + Message + '"  }');
    }
    global static void GetRenewalStatus_notfound(string MarsRenewalId) 
    {
        //Renewal Status
        string RenewalStatus = '';
        string Message = '';
        Order_Item__c objOrderItem = null;
        List<Order_Item__c> objOrderItems = [SELECT Id, Cancellation_Approval__c, Renewal_Instruction__c, Payment_Status__c FROM Order_Item__c WHERE Name=:MarsRenewalId];
        if (objOrderItems != null && objOrderItems.size()>0) 
           objOrderItem = objOrderItems[0];

        string strResult = '';
        if (objOrderItem != null)
        {
            if (objOrderItem.Cancellation_Approval__c == 'Requested')
            {
                Message = 'Cancellation Request Received';
            }
            else if (objOrderItem.Renewal_Instruction__c == 'Cancel')
            {
                Message = 'Cancelled';
                RenewalStatus = objOrderItem.Renewal_Instruction__c ;
            }
            else
            {
                RenewalStatus = objOrderItem.Payment_Status__c;
            }
        }
        else
        {
            Message = 'Invalid request';
        }
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf('{ "status" : "' + RenewalStatus + '", "message" : "' + Message + '"  }');
    }
}