force-app/main/default/objects/APIMessage__c/APIMessage__c.object-meta.xml
<CustomObject>
    <label>APIMessage</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APIMessage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIMessageController.cls
public with sharing class APIMessageController
{
    public static Map<string, APIMessage__c> GetAllMessages()
    {
        Map<string, APIMessage__c> mapMessages =  new Map<string, APIMessage__c>();
        List<APIMessage__c> objMessages = [SELECT Id, Name, Message__c, Message_Type__c FROM APIMessage__c];
        for(APIMessage__c objMessage : objMessages)
        {
            if (mapMessages.containsKey(objMessage.Name) == false)
            {
                mapMessages.put(objMessage.Name, objMessage);
            }
        }
        return mapMessages;
    }
}