force-app/main/default/objects/APIMessage__c/APIMessage__c.object-meta.xml
<CustomObject>
    <label>APIMessage</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APIMessage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIMessage.cls
global with sharing class APIMessage
{
    global string Code {get;set;}
    global string Type {get;set;}
    global string Message {get;set;}
    public static APIMessage GetMessage(Map<string, APIMessage__c> mapMessages, string Code)
    {
        APIMessage objAPIMessage = new APIMessage();
        if (mapMessages.containsKey(Code))
        {
            APIMessage__c objAPIMessageCO = mapMessages.get(code);
            objAPIMessage.Code = objAPIMessageCO.Name;
            objAPIMessage.Message = objAPIMessageCO.Message__c;
            objAPIMessage.Type = objAPIMessageCO.Message_Type__c; 
        }
        return objAPIMessage;
    }
}