force-app/main/default/objects/Batch_Queue__c/Batch_Queue__c.object-meta.xml
<CustomObject>
    <label>Batch Queue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/QB_Customer__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QB Customer</label>
    <referenceTo>QB_Customer__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Payment_Confirmation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Confirmation</label>
    <referenceTo>Payment_Confirmation__c</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Term_Name__c.field-meta.xml
<CustomField>
    <fullName>Term_Name__c</fullName>
    <label>Term</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/Payment_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Payment Confirmation</label>
    <nameField>
        <label>Ref. No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Confirmations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Confirmation__c/fields/Amount_for_selected_Assets__c.field-meta.xml
<CustomField>
    <fullName>Amount_for_selected_Assets__c</fullName>
    <label>Amount for selected Assets</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Payment_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Currency__c</fullName>
    <label>Payment Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_All</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Confirmation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Validation Failed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTOFeeCode__c/PTOFeeCode__c.object-meta.xml
<CustomObject>
    <label>PTO Fee Code</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>S. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTO Fee Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTOFeeCode__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Micro</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTOFeeCode__c/fields/FeeCode__c.field-meta.xml
<CustomField>
    <fullName>FeeCode__c</fullName>
    <label>Fee Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PTOFeeCode__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PTOFeeCode__c/fields/Surcharge_Code__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Code__c</fullName>
    <label>Surcharge Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PTOFeeCode__c/fields/Term_Name__c.field-meta.xml
<CustomField>
    <fullName>Term_Name__c</fullName>
    <label>Term Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Account__c/QB_Account__c.object-meta.xml
<CustomObject>
    <label>QB Account</label>
    <nameField>
        <label>QB Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>QB Accounts</relationshipLabel>
    <relationshipName>QB_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Account__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QB_Account__c/fields/QB_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Account_Id__c</fullName>
    <label>QB Account Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QB_Customer__c/QB_Customer__c.object-meta.xml
<CustomObject>
    <label>QB Customer</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Customer__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>QB Customers</relationshipLabel>
    <relationshipName>QB_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QB_Customer__c/fields/QB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QB_Supplier__c/QB_Supplier__c.object-meta.xml
<CustomObject>
    <label>QB Supplier</label>
    <nameField>
        <label>QB Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QB Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QB_Supplier__c/fields/QB_Supplier_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Supplier_Id__c</fullName>
    <label>QB Supplier Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Currency_All.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>AQD</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <masterLabel>Currency All</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BP</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchRenewalBillCreateTest.cls
@isTest 
global class batchRenewalBillCreateTest 
{
    global class MockHttpResponse implements HttpCalloutMock {
    private Integer statusCode;

    public MockHttpResponse(Integer statusCode){
        this.statusCode = statusCode;
    }

    global HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"foo":"bar"}');
        res.setStatusCode(this.statusCode);
        return res;
    }
}
    static testMethod void testMethod1() 
    {
        PTO_Credentials__c pc  = NEW PTO_Credentials__c();
        pc.Country_Code__c = 'US';
        insert pc;
        PTOFeeCode__c pfc = NEW PTOFeeCode__c();
        pfc.Jurisdiction__c = 'US';
        pfc.Term_Name__c = 'Year 3.7';
        pfc.FeeCode__c = '31';
        pfc.Surcharge_Code__c = '33';
        pfc.Entity_Type__c ='Large';
        insert pfc;
        QB_Account__c qba = NEW QB_Account__c();
        qba.Account_Type__c = 'Bank';
        qba.QB_Account_Id__c = '50';
        insert qba;
        QB_Account__c qba1 = NEW QB_Account__c();
        qba1.Account_Type__c = 'Credit Card';
        qba1.QB_Account_Id__c = '51';
        insert qba1;
        API_Credentials__c ObjAPI = new API_Credentials__c();
        ObjAPI.Password__c ='Test@1234';
        ObjAPI.Username__c ='MaxvalAPI';
        ObjAPI.Name ='Renewal Bill Create';
        ObjAPI.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name ='PTO Payment Validate';
        ObjAPI1.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI1;
        
        Batch_Queue__c objBatchQueue = new  Batch_Queue__c();
        objBatchQueue.Name = 'Order Placed Mail Alert';
        objBatchQueue.Status__c = 'To Do' ;
        insert objBatchQueue;
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
        ClList.add(Cl.id);
        
        List<Id> ListOrd =new List<Id>();
        Set<Id > OrdSet =new Set<Id>();
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Insert Ord;
        OrdSet.add(Ord.id);
        ListOrd.add(Ord.id);
        
        QB_Customer__c qbc1 = NEW QB_Customer__c();
        qbc1.Name = 'QBC1';
        qbc1.QB_Customer_Id__c = '50';
        qbc1.Client__c = Ord.Client__c;
        qbc1.Active__c = true;
        insert qbc1;
        
        QB_Supplier__c qsc1 = NEW QB_Supplier__c();
        qsc1.Name = 'QBC1';
        qsc1.QB_Supplier_Id__c = '50';
        qsc1.Jurisdiction__c = 'US';
        qsc1.Active__c = true;
        insert qsc1;
        
        Payment_Confirmation__c pc1 = NEW Payment_Confirmation__c();
        
        pc1.Name = 'ABC123';
        pc1.Payment_Currency__c = 'USD';
        pc1.Payment_Amount__c = 4848;
        pc1.Amount_for_selected_Assets__c = 24;
        pc1.Payment_Method__c = 'Wire Transfer';
        insert pc1;  
        /*
        List<Payment_Confirmation__c> PaymentC = [SELECT id, Name, Payment_Currency__c, Amount_for_selected_Assets__c, Payment_Method__c, Exchange_Rate__c FROM Payment_Confirmation__c WHERE id =: pc1.id ];
        system.debug('PaymentC:' + PaymentC[0].id + ' ' + PaymentC[0].Payment_Currency__c + ' ' + PaymentC[0].Amount_for_selected_Assets__c + ' ' + PaymentC[0].Payment_Method__c + ' ' + PaymentC[0].Exchange_Rate__c + ' ');
        system.debug('PC1_id:' + pc1.id);
        system.debug('Exchange rate:' + string.ValueOf(pc1.Exchange_Rate__c));
        */
         
        List<Order_Item__c> listOI = NEW List<Order_Item__c>();
        /*
        Order_Item__c OI1 =new Order_Item__c();
        OI1.Order__c =Ord.Id;
        OI1.PTO_Validation_Status__c='Request to Validate';
        OI1.PTO_Validation_Request_ID__c='abcdefg';
        OI1.Jurisdiction__c='US';
        OI1.Application_Date__c=date.today().addyears(-4);
        OI1.Application_No__c='US0000003';
        OI1.Patent_No__c='US0000003';
        OI1.Term_Name__c='Year 3.7';
        OI1.Entity_Type_Name__c='Large';
        OI1.Surcharge__c=13350.00;
        listOI.add(OI1); 
		*/
        
        test.startTest();
       // insert listOI;
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Payment_Mode__c = 'Wire Transfer';
        OI.Payment_Confirmation__c = pc1.id;
        //OI.Payment_Confirmation__r.Payment_Method__c = OI.Payment_Mode__c;
        OI.PTO_Validation_Status__c='Request to Validate';
        OI.PTO_Validation_Request_ID__c='abcdefg';
        OI.Jurisdiction__c='US';
        OI.Application_Date__c=date.today().addyears(-4);
        OI.Application_No__c='US0000001';
        OI.Patent_No__c='US0000001';
        OI.Term_Name__c='Year 3.7';
        OI.Entity_Type_Name__c='Large';
        OI.Surcharge__c=13350.00;
        OI.Fee__c=Double.valueOf('1234');
        //Insert OI;
        listOI.add(OI);
        insert listOI;
        /*
        List<Order_Item__c> Check_Order = [SELECT id, Payment_Confirmation__r.Exchange_Rate__c FROM Order_Item__c WHERE id =: OI.id];
        system.debug(Check_Order[0].id + ' ' + Check_Order[0].Payment_Confirmation__r.Exchange_Rate__c);
        */
        
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        ptoValidationReqWrapper wp = new ptoValidationReqWrapper();
        wp.countryCode = 'US';
        wp.countryAssets = listOI;
        batchRenewalBillCreate cls = New batchRenewalBillCreate(new list<ptoValidationReqWrapper>{wp}, '50');
        
        database.executebatch(cls,1);
        Test.stopTest();
    }
    
    static testMethod void testMethod2() 
    {
        
        PTO_Credentials__c pc  = NEW PTO_Credentials__c();
        pc.Country_Code__c = 'US';
        insert pc;
        PTOFeeCode__c pfc = NEW PTOFeeCode__c();
        pfc.Jurisdiction__c = 'US';
        pfc.Term_Name__c = 'Year 3.7';
        pfc.FeeCode__c = '31';
        pfc.Surcharge_Code__c = '33';
        pfc.Entity_Type__c ='Large';
        insert pfc;
        QB_Account__c qba = NEW QB_Account__c();
        qba.Name = 'QBA1';
        qba.Account_Type__c = 'Bank';
        qba.QB_Account_Id__c = '50';
        qba.Jurisdiction__c = 'US';
        qba.Active__c = true;
        insert qba;
        QB_Account__c qba1 = NEW QB_Account__c();
        qba1.Name = 'QBA1';
        qba1.Account_Type__c = 'Credit Card';
        qba1.QB_Account_Id__c = '51';
        qba1.Jurisdiction__c = 'US';
        qba1.Active__c = true; 
        insert qba1;
        
        API_Credentials__c ObjAPI = new API_Credentials__c();
        ObjAPI.Password__c ='Test@1234';
        ObjAPI.Username__c ='MaxvalAPI';
        ObjAPI.Name ='Renewal Bill Create';
        ObjAPI.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name ='PTO Payment Validate';
        ObjAPI1.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI1;
        
        API_Auth_Detail__c aad = NEW API_Auth_Detail__c();
        aad.Auth_Code__c = 'AAD1';
        aad.ClientId__c	= aad.id;
        
        Batch_Queue__c objBatchQueue = new  Batch_Queue__c();
        objBatchQueue.Name = 'Order Placed Mail Alert ';
        objBatchQueue.Status__c = 'To Do' ;
        insert objBatchQueue;
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
		ClList.add(Cl.id);        
        
        List<Id> ListOrd =new List<Id>();
        Set<Id > OrdSet =new Set<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Insert Ord;
        OrdSet.add(Ord.id);
        ListOrd.add(Ord.id);
        
        QB_Customer__c qbc1 = NEW QB_Customer__c();
        qbc1.Name = 'QBC1';
        qbc1.QB_Customer_Id__c = '50';
        qbc1.Client__c = Ord.Client__c;
        qbc1.Active__c = true;
        insert qbc1;
        
        QB_Supplier__c qsc1 = NEW QB_Supplier__c();
        qsc1.Name = 'QBC1';
        qsc1.QB_Supplier_Id__c = '50';
        qsc1.Jurisdiction__c = 'US';
        qsc1.Active__c = true;
        insert qsc1;
        
        Payment_Confirmation__c pc1 = NEW Payment_Confirmation__c();
        pc1.Payment_Amount__c = 4848;
        pc1.Amount_for_selected_Assets__c = 24;
        pc1.Payment_Method__c = 'Wire Transfer';
        insert pc1;  
        system.debug('Exchange rate:' + string.valueOf(pc1.Exchange_Rate__c));
        
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Payment_Confirmation__c = pc1.id;
        OI.PTO_Validation_Status__c='Request to Validate';
        OI.PTO_Validation_Request_ID__c='abcdefg';
        OI.Jurisdiction__c='US';
        OI.Application_Date__c=date.today().addyears(-4);
        OI.Application_No__c='US0000001';
        OI.Patent_No__c='0000001EP';
        OI.Term_Name__c='Year 3.7';
        OI.Entity_Type_Name__c='Large';
        OI.Fee__c=Double.valueOf('1234');
        OI.Surcharge__c=13350.00;
        Insert OI;
        test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        ptoValidationReqWrapper wp = new ptoValidationReqWrapper();
        wp.countryCode = 'US';
        wp.countryAssets = new List<Order_Item__c>{OI};
        batchRenewalBillCreate cls = New batchRenewalBillCreate(new list<ptoValidationReqWrapper>{wp}, '50||100||150');
        database.executebatch(cls,1);
        
        Test.stopTest();
    }
    
    static testMethod void testMethod3() 
    {
        test.startTest();
        
        batchRenewalBillCreate.ReqData rd = new batchRenewalBillCreate.ReqData();
        rd.APIHandleRef = 'MaxVal123';
        rd.PaymentType = 'Wire Transfer';
        
        batchRenewalBillCreate.objectitem oit = new batchRenewalBillCreate.objectitem();
        oit.Fee = '100';
        
        batchRenewalBillCreate.objBankFee obf = new batchRenewalBillCreate.objBankFee();
        obf.Items = null;
        rd.BankFee = obf;
        
        batchRenewalBillCreate.objBankFeeItem obfi = new batchRenewalBillCreate.objBankFeeItem();
        obfi.AccountToRef = 'String1';
        obfi.Billable = true;
        obfi.Description = 'Empty';
        obfi.Fee = '100';
        obfi.FeeClass = 'USD';
        
        batchRenewalBillCreate.responsebody rb = new batchRenewalBillCreate.responsebody();
        rb.Status = 3;
        rb.RequestID = 'ABC123';
        rb.BankFeeErrorItems = null;
        rb.BankFeeWarningItems = null;
        rb.ErrorItems = null;
        rb.Errors = null;
        rb.WarningItems = null;
        rb.Warnings = null;
        
        batchRenewalBillCreate.responseerror re = new batchRenewalBillCreate.responseerror();
        re.Code = 'Empty';
        re.Description = 'Empty';
        
        batchRenewalBillCreate.responseerroritem rei = new batchRenewalBillCreate.responseerroritem();
        rei.RowNumber = 3;
        rei.Errors = null;
        
        batchRenewalBillCreate.apiResponse aR = new batchRenewalBillCreate.apiResponse();
        aR.Message = 'Empty';
        aR.Description = 'Empty';
        
        Test.stopTest();
    }
    static testMethod void testMethod4() 
    {
        PTO_Credentials__c pc  = NEW PTO_Credentials__c();
        pc.Country_Code__c = 'US';
        insert pc;
        PTOFeeCode__c pfc = NEW PTOFeeCode__c();
        pfc.Jurisdiction__c = 'US';
        pfc.Term_Name__c = 'Year 3.7';
        pfc.FeeCode__c = '31';
        pfc.Surcharge_Code__c = '33';
        pfc.Entity_Type__c ='Large';
        insert pfc;
        QB_Account__c qba = NEW QB_Account__c();
        qba.Name = 'QBA1';
        qba.Account_Type__c = 'Bank';
        qba.QB_Account_Id__c = '50';
        qba.Jurisdiction__c = 'US';
        qba.Active__c = true;
        insert qba;
        QB_Account__c qba1 = NEW QB_Account__c();
        qba1.Name = 'QBA1';
        qba1.Account_Type__c = 'Credit Card';
        qba1.QB_Account_Id__c = '51';
        qba1.Jurisdiction__c = 'US';
        qba1.Active__c = true; 
        insert qba1;
        
        API_Credentials__c ObjAPI = new API_Credentials__c();
        ObjAPI.Password__c ='Test@1234';
        ObjAPI.Username__c ='MaxvalAPI';
        ObjAPI.Name ='Renewal Bill Create';
        ObjAPI.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name ='PTO Payment Validate';
        ObjAPI1.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI1;
        
        API_Auth_Detail__c aad = NEW API_Auth_Detail__c();
        aad.Auth_Code__c = 'AAD1';
        aad.ClientId__c	= aad.id;
        
        Batch_Queue__c objBatchQueue = new  Batch_Queue__c();
        objBatchQueue.Name = 'Order Placed Mail Alert ';
        objBatchQueue.Status__c = 'To Do' ;
        insert objBatchQueue;
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
		ClList.add(Cl.id);        
        
        List<Id> ListOrd =new List<Id>();
        Set<Id > OrdSet =new Set<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Insert Ord;
        OrdSet.add(Ord.id);
        ListOrd.add(Ord.id);
        
        QB_Customer__c qbc1 = NEW QB_Customer__c();
        qbc1.Name = 'QBC1';
        qbc1.QB_Customer_Id__c = '50';
        qbc1.Client__c = Ord.Client__c;
        qbc1.Active__c = true;
        insert qbc1;
        
        QB_Supplier__c qsc1 = NEW QB_Supplier__c();
        qsc1.Name = 'QBC1';
        qsc1.QB_Supplier_Id__c = '50';
        qsc1.Jurisdiction__c = 'US';
        qsc1.Active__c = true;
        insert qsc1;
        
        Payment_Confirmation__c pc1 = NEW Payment_Confirmation__c();
        pc1.Payment_Amount__c = 4848;
        pc1.Amount_for_selected_Assets__c = 24;
        pc1.Payment_Method__c = 'Wire Transfer';
        insert pc1;  
        system.debug('Exchange rate:' + string.valueOf(pc1.Exchange_Rate__c));
        
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Payment_Confirmation__c = pc1.id;
        OI.PTO_Validation_Status__c='Request to Validate';
        OI.PTO_Validation_Request_ID__c='abcdefg';
        OI.Jurisdiction__c='US';
        OI.Application_Date__c=date.today().addyears(-4);
        OI.Application_No__c='US0000001';
        OI.Patent_No__c='0000001EP';
        OI.Term_Name__c='Year 3.7';
        OI.Entity_Type_Name__c='Large';
        OI.Fee__c=Double.valueOf('1234');
        OI.Surcharge__c=13350.00;
        Insert OI;
        test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(404));
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        ptoValidationReqWrapper wp = new ptoValidationReqWrapper();
        wp.countryCode = 'US';
        wp.countryAssets = new List<Order_Item__c>{OI};
        batchRenewalBillCreate cls = New batchRenewalBillCreate(new list<ptoValidationReqWrapper>{wp}, '150');
        database.executebatch(cls,1);
        
        Test.stopTest();
    
    } 
    static testMethod void testMethod5() 
    {
        PTO_Credentials__c pc  = NEW PTO_Credentials__c();
        pc.Country_Code__c = 'US';
        insert pc;
        PTOFeeCode__c pfc = NEW PTOFeeCode__c();
        pfc.Jurisdiction__c = 'US';
        pfc.Term_Name__c = 'Year 3.7';
        pfc.FeeCode__c = '31';
        pfc.Surcharge_Code__c = '33';
        pfc.Entity_Type__c ='Large';
        insert pfc;
        QB_Account__c qba = NEW QB_Account__c();
        qba.Name = 'QBA1';
        qba.Account_Type__c = 'Bank';
        qba.QB_Account_Id__c = '50';
        qba.Jurisdiction__c = 'US';
        qba.Active__c = true;
        insert qba;
        QB_Account__c qba1 = NEW QB_Account__c();
        qba1.Name = 'QBA1';
        qba1.Account_Type__c = 'Credit Card';
        qba1.QB_Account_Id__c = '51';
        qba1.Jurisdiction__c = 'US';
        qba1.Active__c = true; 
        insert qba1;
        
        API_Credentials__c ObjAPI = new API_Credentials__c();
        ObjAPI.Password__c ='Test@1234';
        ObjAPI.Username__c ='MaxvalAPI';
        ObjAPI.Name ='Renewal Bill Create';
        ObjAPI.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI;
        
        API_Credentials__c ObjAPI1 = new API_Credentials__c();
        ObjAPI1.Password__c ='Test@1234';
        ObjAPI1.Username__c ='MaxvalAPI';
        ObjAPI1.Name ='PTO Payment Validate';
        ObjAPI1.URL__c ='https://login.salesforce.com/services/oauth2/token';
        insert ObjAPI1;
        
        API_Auth_Detail__c aad = NEW API_Auth_Detail__c();
        aad.Auth_Code__c = 'AAD1';
        aad.ClientId__c	= aad.id;
        
        Batch_Queue__c objBatchQueue = new  Batch_Queue__c();
        objBatchQueue.Name = 'Order Placed Mail Alert ';
        objBatchQueue.Status__c = 'To Do' ;
        insert objBatchQueue;
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Test Status';
        Cl.Contact_Email_Id__c ='juveria.b@maxval.com';
        Insert Cl;
		ClList.add(Cl.id);        
        
        List<Id> ListOrd =new List<Id>();
        Set<Id > OrdSet =new Set<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Insert Ord;
        OrdSet.add(Ord.id);
        ListOrd.add(Ord.id);
        
        QB_Customer__c qbc1 = NEW QB_Customer__c();
        qbc1.Name = 'QBC1';
        qbc1.QB_Customer_Id__c = '50';
        qbc1.Client__c = Ord.Client__c;
        qbc1.Active__c = true;
        insert qbc1;
        
        QB_Supplier__c qsc1 = NEW QB_Supplier__c();
        qsc1.Name = 'QBC1';
        qsc1.QB_Supplier_Id__c = '50';
        qsc1.Jurisdiction__c = 'US';
        qsc1.Active__c = true;
        insert qsc1;
        
        Payment_Confirmation__c pc1 = NEW Payment_Confirmation__c();
        pc1.Payment_Amount__c = 4848;
        pc1.Amount_for_selected_Assets__c = 24;
        pc1.Payment_Method__c = 'Wire Transfer';
        insert pc1;  
        system.debug('Exchange rate:' + string.valueOf(pc1.Exchange_Rate__c));
        
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Payment_Confirmation__c = pc1.id;
        OI.PTO_Validation_Status__c='Request to Validate';
        OI.PTO_Validation_Request_ID__c='abcdefg';
        OI.Jurisdiction__c='US';
        OI.Application_Date__c=date.today().addyears(-4);
        OI.Application_No__c='US0000001';
        OI.Patent_No__c='0000001EP';
        OI.Term_Name__c='Year 3.7';
        OI.Entity_Type_Name__c='Large';
        OI.Fee__c=Double.valueOf('1234');
        OI.Surcharge__c=13350.00;
        Insert OI;
        test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(500));
        MaxValAPIAuthenticaionHelper.MaxValAPIAuthenticaionHelper();
        ptoValidationReqWrapper wp = new ptoValidationReqWrapper();
        wp.countryCode = 'US';
        wp.countryAssets = new List<Order_Item__c>{OI};
        batchRenewalBillCreate cls = New batchRenewalBillCreate(new list<ptoValidationReqWrapper>{wp}, '150');
        database.executebatch(cls,1);
        
        Test.stopTest();
    
    } 
}