force-app/main/default/objects/Batch_Queue__c/Batch_Queue__c.object-meta.xml
<CustomObject>
    <label>Batch Queue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Queue__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Payment_Received_from_Client__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_from_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Received from Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Send_for_approval_to_pay_PTO_fee__c.field-meta.xml
<CustomField>
    <fullName>Send_for_approval_to_pay_PTO_fee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Are you requesting approval from your manager to pay PTO even if the payment not yet received from the client?</inlineHelpText>
    <label>Send for approval to pay PTO fee?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RecordPaymentBatch.cls
global with sharing class RecordPaymentBatch implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    public List<Id> SelectedOrderItemIds {get;set;}
    global RecordPaymentBatch ()
    {
    }
    global RecordPaymentBatch (List<Id> lstSelectedOrderItemIds)
    {
        SelectedOrderItemIds = lstSelectedOrderItemIds;
    }
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([SELECT Id, Payment_Status__c, Payment_Received_from_Client__c FROM Order_Item__c WHERE Id IN :SelectedOrderItemIds]);
    }
    global void execute(Database.BatchableContext BC, List<sObject> objScopeObjectList)
    {
        Map<Id, string> mapOrderItemIds =  new Map<Id, string>();
        List<Order_Item__c> objOrderItemList = new List<Order_Item__c>();
        for(sObject objScopeObject : objScopeObjectList)
        {
            Order_Item__c objOrderItem = (Order_Item__c) objScopeObject;
            objOrderItem.Payment_Status__c = 'Payment Received';
            objOrderItem.Payment_Received_from_Client__c = true;
            objOrderItem.Send_for_approval_to_pay_PTO_fee__c = false;
            objOrderItemList.add(objOrderItem);
            
            if (mapOrderItemIds.containsKey(objOrderItem.Id)==false)
                    mapOrderItemIds.put(objOrderItem.Id, string.valueOf(objOrderItem.Id));
        }
        UPDATE objOrderItemList;
        
        List<string> strOrderItemIds = mapOrderItemIds.values();
        if (strOrderItemIds!= null && strOrderItemIds.size()>0)
        {
            List<Batch_Queue__c> objBatchQueueList = [SELECT Id, Status__c FROM Batch_Queue__c WHERE Parent_Id__c IN :strOrderItemIds AND Name = 'Record Payments'];
            for(Batch_Queue__c objBatchQueue :objBatchQueueList )
            {
                objBatchQueue.Status__c = 'Completed';
            }
            if (objBatchQueueList != null && objBatchQueueList.size()>0)
                UPDATE objBatchQueueList;
        }
        
    }
    global void finish(Database.BatchableContext BC)
    {
    }
    
}