force-app/main/default/objects/Batch_Queue__c/Batch_Queue__c.object-meta.xml
<CustomObject>
    <label>Batch Queue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Queue__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_EUR__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_EUR__c</fullName>
    <label>Order Amount EUR</label>
    <summarizedField>Order_Item__c.Invoice_Amount_When_Instruct__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Item__c.Billing_Currency__c</field>
        <operation>equals</operation>
        <value>EUR</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Order_Item__c.Renewal_Instruction__c</field>
        <operation>equals</operation>
        <value>Renew</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_USD_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_USD_Total__c</fullName>
    <formula>Order_Amount_USD__c +  Late_Fee__c +  Rush_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Amount USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <displayFormat>OID-{000000000}</displayFormat>
    <label>Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Renewals__c.field-meta.xml
<CustomField>
    <fullName>Total_Renewals__c</fullName>
    <label>Total Renewals</label>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BatchOrderPlacedMailAlert.cls
global with sharing class BatchOrderPlacedMailAlert implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    global string BatchId {get;set;}
    global BatchOrderPlacedMailAlert()
    {
    }
    global BatchOrderPlacedMailAlert (string strBatchId)
    {
        BatchId = strBatchId;
    }
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        if (BatchId != null)
            return Database.getQueryLocator([SELECT Id, Parent_Id__c FROM Batch_Queue__c WHERE Name = 'Order Placed Mail Alert' AND Status__c = 'To Do' AND Id =:BatchId]);
        else
            return Database.getQueryLocator([SELECT Id, Parent_Id__c FROM Batch_Queue__c WHERE Name = 'Order Placed Mail Alert' AND Status__c = 'To Do']);                   
    }
    global void execute(Database.BatchableContext BC, List<sObject> objScopeObjectList)
    {
        try
        {
            //Read the Batches & Clients
            Map<Id, Id> mapClientIds = new Map<Id, Id>();
            List<Batch_Queue__c> objBatchQueueListToBeUpdated = new List<Batch_Queue__c>();
            for(sObject objScopeObject : objScopeObjectList)
            {
                Batch_Queue__c objBatchQueue = (Batch_Queue__c)objScopeObject;
                if (mapClientIds.containsKey(objBatchQueue.Parent_Id__c)==false)
                {
                    mapClientIds.put(objBatchQueue.Parent_Id__c, objBatchQueue.Parent_Id__c);
                    objBatchQueueListToBeUpdated.add(objBatchQueue); 
                }
            }
            
            Map<Id, List<Order__c>> mapClientOrders = new Map<Id, List<Order__c>>();
            Map<Id, string> mapClientEmail = new Map<Id, string>();
            List<Order__c> objOrderList = [SELECT  Id, Name, Payment_Status__c, Order_Number__c, Order_Date__c, Total_Renewals__c, Client__c, Client__r.Client_Name__c, Client__r.Contact_Email_Id__c, Order_Amount_USD_Total__c, Order_Amount_EUR__c FROM Order__c WHERE Client__c IN :mapClientIds.keySet()];
            for(Order__c objOrder : objOrderList)
            {
                if (mapClientOrders.containsKey(objOrder.Client__c)==false)
                {
                    List<Order__c> objClientOrderList =  new List<Order__c>();
                    objClientOrderList.add(objOrder);
                    mapClientOrders.put(objOrder.Client__c,objClientOrderList);
                    mapClientEmail.put(objOrder.Client__c, objOrder.Client__r.Contact_Email_Id__c);
                }
                else
                {
                    List<Order__c> objClientOrderList =  mapClientOrders.get(objOrder.Client__c);
                    objClientOrderList.add(objOrder);
                    mapClientOrders.put(objOrder.Client__c,objClientOrderList);
                }
            }
            
            List<Messaging.SingleEmailMessage> objMessageList = new List<Messaging.SingleEmailMessage>();
            Set<Id> objClientIds = mapClientOrders.keySet();
            for(Id ClientId : objClientIds)
            {
                if (mapClientOrders.containsKey(ClientId))
                {
                    List<Order__c> objClientOrderList = mapClientOrders.get(ClientId); 
                    List<String> Receivers = new List<String>();
                    if (mapClientEmail.containsKey(ClientId))
                        Receivers.add(mapClientEmail.get(ClientId));
                    
                    string strMessageBody = EmailHelper.Body_Client_WhenNewOrderReceived(objClientOrderList);
                    Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
                    objMail.setSubject('Orders placed to MaxVal successfully');
                    objMail.setToAddresses(Receivers);
                    objMail.setHtmlBody(strMessageBody); 
                    objMessageList.add(objMail);
                }
            }
            Messaging.sendEmail(objMessageList);
            
            UPDATE objBatchQueueListToBeUpdated;
        }
        catch(Exception exp)
        {
        }
        finally
        {
        }
    }
    global void finish(Database.BatchableContext BC)
    {
    }
}