force-app/main/default/objects/Batch_Queue__c/Batch_Queue__c.object-meta.xml
<CustomObject>
    <label>Batch Queue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Queue__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clients__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Regular Invoice</fullName>
                <default>true</default>
                <label>Regular Invoice</label>
            </value>
            <value>
                <fullName>BU Wise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request to be Sent</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Sent to Client</fullName>
            </value>
            <value>
                <fullName>Invoice Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Jurisdiction Wise</fullName>
            </value>
            <value>
                <fullName>Business Unit Wise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name__c</fullName>
    <label>Invoice Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Is_Late_Rush_Fee_Included__c.field-meta.xml
<CustomField>
    <fullName>Is_Late_Rush_Fee_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Late &amp; Rush Fee Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <formula>Order__r.Late_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Late Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Type_Configuration__c/Invoice_Type_Configuration__c.object-meta.xml
<CustomObject>
    <label>Invoice Type Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Type Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Type_Configuration__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipLabel>Invoice Type Configurations</relationshipLabel>
    <relationshipName>Invoice_Type_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Type_Configuration__c/fields/Contact_Persons__c.field-meta.xml
<CustomField>
    <fullName>Contact_Persons__c</fullName>
    <label>Contact Persons</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Type_Configuration__c/fields/Invoice_Currency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Currency__c</fullName>
    <label>Invoice Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Clients__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Late Fee (Added in USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Invoicing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice to be modified</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoice Generated</fullName>
                <isActive>false</isActive>
                <label>Invoice Generated</label>
            </value>
            <value>
                <fullName>Invoice In Progress</fullName>
                <isActive>false</isActive>
                <label>Invoice In Progress</label>
            </value>
            <value>
                <fullName>Payment Received (Full)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Full)</label>
            </value>
            <value>
                <fullName>Payment Received (Partial)</fullName>
                <isActive>false</isActive>
                <label>Payment Received (Partial)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Order__r.Client__r.Client_Name__c</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Invoice_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_Name__c</fullName>
    <label>Invoice Type Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruct Failed</fullName>
            </value>
            <value>
                <fullName>Waiting to Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Requested</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>PTO/Agent Payments Completed</fullName>
            </value>
            <value>
                <fullName>Asset Renewed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateInvoiceBatchTest.cls
@isTest
public class GenerateInvoiceBatchTest {
    static testMethod void testMethod1() 
    {
        test.startTest();
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Sample';
        Insert Cl;
        ClList.add(Cl.id);
        List<Id> ListOrd =new List<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Ord.Late_Fee__c = 100.00;
        Ord.Payment_Status__c = 'To be Invoiced';
        Insert Ord;
        ListOrd.add(Ord.id);
        
        /*Invoice__c inv = new Invoice__c();
        inv.Order__c = ord.id;
        inv.Invoice_Amount__c = 100;
        inv.Is_Late_Rush_Fee_Included__c = true;
        insert inv;*/
        
        Batch_Queue__c objBatchQueue = new  Batch_Queue__c();
        objBatchQueue.Name = 'Generate Invoice';
        objBatchQueue.Status__c = 'To Do' ;
        objBatchQueue.Parent_Id__c = ord.Id;
        insert objBatchQueue;
        
        GenerateInvoiceBatch objGenerateInvoiceBatch = new GenerateInvoiceBatch(ListOrd);
        Database.executeBatch(objGenerateInvoiceBatch,1);
        
        test.stopTest();
    }
    static testMethod void testMethod2() 
    {
        
        test.startTest();
        GenerateInvoiceBatch objGenerateInvoiceBatch = new GenerateInvoiceBatch();
        ID batchprocessid = Database.executeBatch(objGenerateInvoiceBatch,1);
        test.stopTest();
    }
    static testMethod void testMethod3() 
    {
        
        test.startTest();
        GenerateInvoiceBatch objGenerateInvoiceBatch = new GenerateInvoiceBatch();
        ID batchprocessid = Database.executeBatch(objGenerateInvoiceBatch,1);
        GenerateInvoiceBatch gib = new GenerateInvoiceBatch(batchprocessid);
        test.stopTest();
    }
    
    static testMethod void testMethod4() 
    {
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Sample';
        Cl.Invoice_Type__c = 'Regular Invoice';
        Insert Cl;
        ClList.add(Cl.id);
        
        Invoice_Type_Configuration__c ITC =new Invoice_Type_Configuration__c();
        ITC.Contact_Persons__c = 'pratyush.r@maxval.com';
        ITC.Client__c =Cl.id;
        insert ITC;
        
        List<Id> ListOrd =new List<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Ord.Payment_Status__c = 'Invoiced';
        Insert Ord;
        ListOrd.add(Ord.id);
        
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Billing_Currency__c = 'USD';
        OI.Path__c = null;
        OI.Invoice_Type_Name__c = '-';
        Insert OI;
        
        Currency__c cur = new Currency__c();
        cur.Name = 'US';
        cur.Exchange_Rate__c = 75;
        Insert cur;
        
        Invoice__c inv = new Invoice__c();
        inv.Order__c = ord.id;
        inv.Invoice_Date__c = Datetime.now();
        inv.Invoice_Status__c = 'Created';
        inv.Is_Active__c = true;
        inv.Invoice_Currency__c = 'USD';
        inv.Invoice_Type__c = 'ABC123';
        inv.Invoice_Type_Name__c = ord.Client__r.Id + '_' + ord.Id + '_' + oi.Billing_Currency__c;
        inv.Invoice_No__c = 'INV001';
        inv.Invoice_Amount__c = 100.00;
        inv.Invoice_Config_Type__c = 'Maxval123';
        inv.Is_Late_Rush_Fee_Included__c = true;
        inv.API_Status__c = 'Completed';
        Insert inv;
        
        test.startTest();
        GenerateInvoiceBatch objGenerateInvoiceBatch = new GenerateInvoiceBatch(ListOrd);
        Database.executeBatch(objGenerateInvoiceBatch,1);
        
        test.stopTest();
    }
    static testMethod void testMethod5() 
    {
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Sample';
        Cl.Invoice_Type__c = 'Regular Invoice';
        Insert Cl;
        ClList.add(Cl.id);
        
        Invoice_Type_Configuration__c ITC =new Invoice_Type_Configuration__c();
        ITC.Contact_Persons__c = 'pratyush.r@maxval.com';
        ITC.Client__c =Cl.id;
        insert ITC;
        
        List<Id> ListOrd =new List<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Ord.Payment_Status__c = 'Invoiced';
        Insert Ord;
        ListOrd.add(Ord.id);
        
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Billing_Currency__c = 'USD';
        OI.Path__c = null;
        OI.Invoice_Type_Name__c = 'INV001_';
        Insert OI;
        
        Currency__c cur = new Currency__c();
        cur.Name = 'US';
        cur.Exchange_Rate__c = 75;
        Insert cur;
        
        Invoice__c inv = new Invoice__c();
        inv.Order__c = ord.id;
        inv.Invoice_Date__c = Datetime.now();
        inv.Invoice_Status__c = 'Created';
        inv.Is_Active__c = true;
        inv.Invoice_Currency__c = 'USD';
        inv.Invoice_Type__c = 'ABC123';
        inv.Invoice_Type_Name__c = ord.Client__r.Id + '_' + ord.Id + '_' + oi.Billing_Currency__c;
        inv.Invoice_No__c = 'INV001';
        inv.Invoice_Amount__c = 100.00;
        inv.Invoice_Config_Type__c = 'Maxval123';
        inv.Is_Late_Rush_Fee_Included__c = true;
        inv.API_Status__c = 'Completed';
        Insert inv;
        
        test.startTest();
        GenerateInvoiceBatch objGenerateInvoiceBatch = new GenerateInvoiceBatch(ListOrd);
        Database.executeBatch(objGenerateInvoiceBatch,1);
        
        test.stopTest();
    }
    static testMethod void testMethod6() 
    {
        
        List<Id > ClList =new List<Id>();
        Clients__c  Cl =new Clients__c ();
        Cl.Client_Name__c = 'Sample';
        Cl.Invoice_Type__c = 'Regular Invoice';
        Insert Cl;
        ClList.add(Cl.id);
        
        Invoice_Type_Configuration__c ITC =new Invoice_Type_Configuration__c();
        ITC.Contact_Persons__c = 'pratyush.r@maxval.com';
        ITC.Client__c =Cl.id;
        insert ITC;
        
        List<Id> ListOrd =new List<Id>();
        
        Order__c  Ord =new Order__c ();
        Ord.Client__c =Cl.id;
        Ord.Payment_Status__c = 'Invoiced';
        Insert Ord;
        ListOrd.add(Ord.id);
        
        Order_Item__c OI =new Order_Item__c();
        OI.Order__c =Ord.Id;
        OI.Billing_Currency__c = 'USD';
        OI.Path__c = null;
        OI.Invoice_Type_Name__c = '_INV001';
        Insert OI;
        
        Currency__c cur = new Currency__c();
        cur.Name = 'US';
        cur.Exchange_Rate__c = 75;
        Insert cur;
        
        Invoice__c inv = new Invoice__c();
        inv.Order__c = ord.id;
        inv.Invoice_Date__c = Datetime.now();
        inv.Invoice_Status__c = 'Created';
        inv.Is_Active__c = true;
        inv.Invoice_Currency__c = 'USD';
        inv.Invoice_Type__c = 'ABC123';
        inv.Invoice_Type_Name__c = ord.Client__r.Id + '_' + ord.Id + '_' + oi.Billing_Currency__c;
        inv.Invoice_No__c = 'INV001';
        inv.Invoice_Amount__c = 100.00;
        inv.Invoice_Config_Type__c = 'Maxval123';
        inv.Is_Late_Rush_Fee_Included__c = true;
        inv.API_Status__c = 'Completed';
        Insert inv;
        
        test.startTest();
        GenerateInvoiceBatch objGenerateInvoiceBatch = new GenerateInvoiceBatch(ListOrd);
        Database.executeBatch(objGenerateInvoiceBatch,1);
        
        test.stopTest();
    }
}