force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Amount_EUR__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_EUR__c</fullName>
    <label>Order Amount EUR</label>
    <summarizedField>Order_Item__c.Invoice_Amount_When_Instruct__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Item__c.Billing_Currency__c</field>
        <operation>equals</operation>
        <value>EUR</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Order_Item__c.Renewal_Instruction__c</field>
        <operation>equals</operation>
        <value>Renew</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount_USD__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_USD__c</fullName>
    <label>Order Amount</label>
    <summarizedField>Order_Item__c.Invoice_Amount_When_Instruct__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Item__c.Billing_Currency__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Order_Item__c.Renewal_Instruction__c</field>
        <operation>equals</operation>
        <value>Renew</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORDI-{0}</displayFormat>
        <label>Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Billing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billing_Amount__c</fullName>
    <label>Billing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Billing Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderItemHelper.cls
public with sharing class OrderItemHelper
{
    public static void UpdateOrderAmount(Set<Id> setOrderIds)
    {
        //Fetch the newly created Orders
        Map<Id, Order__c> mapOrders = new Map<Id, Order__c>();
        List<Order__c> objOrderList = [SELECT Id FROM Order__c WHERE Id IN :setOrderIds];
        for(Order__c objOrder : objOrderList)
        {
            if (mapOrders.containsKey(objOrder.Id)==false) 
                mapOrders.put(objOrder.Id, objOrder);
        }
        
        List<Order_Item__c> objOrderItemList = [SELECT Id, Order__c, Billing_Currency__c, Billing_Amount__c FROM Order_Item__c WHERE Order__c IN :setOrderIds];
        for(Order_Item__c objOrderItem : objOrderItemList)
        {
            if (mapOrders.containsKey(objOrderItem.Order__c)==true) 
            {
                Order__c objOrder = mapOrders.get(objOrderItem.Order__c);
                //if (objOrderItem.Billing_Currency__c == 'USD')
                //    objOrder.Order_Amount_USD__c +=  objOrderItem.Billing_Amount__c; 
                //if (objOrderItem.Billing_Currency__c == 'EUR')
                //    objOrder.Order_Amount_EUR__c +=  objOrderItem.Billing_Amount__c; 
            }
        } 
        UPDATE mapOrders.values();       
        
    }
}